### ISSUE TITLE
Analysis Engine Breaks when opening a new game from the Explorer

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#1013]
### What is the problem?

During live engine analysis after a game, if you open the opening explorer and choose a game from there to analyze with the engine, the engine breaks and shows the previous analysis from the game you played before.

Recording:

https://github.com/user-attachments/assets/3b4e71ec-da6c-4ca4-890e-54c62f03d1e7

### Steps to reproduce the bug

Go to the analysis board.
Turn on the engine and play a series of moves
From within the analysis board open the opening explorer
Choose any game from the Explorer
Choose to analyze that game

Expected: Engine works properly
What Happened: Engine is stuck on previous position, and the app must be restarted to fix it.

### App version

10.3

### Device Info

Pixel 6 and Android 14

### Additional information

I believe this is caused because the previous analysis was not stopped when you entered the different pages. When trying to analyze a different game things break with the engine overlap.

**Comment by veloce** [comment]
Yes, known bug. Thanks for creating the detailed issue anyway.

This is probably due to the engine not properly closed indeed.

**Comment by HaonRekcef** [comment]
This is also a very annoying bug now with the new player screen in broadcasts. Because it allows to open multiple broadcast games on top of each other and then the engine breaks.

**Comment by veloce** [comment]
Definitely need a fix yeah. Hopefully should be "easy" to fix.
