### ISSUE TITLE
{Coordinate Trainer} Add the option to disable / enable board highlights

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#1018]
Some users may prefer to not see the highlights as they tap, so keeping it as a toggle option would be nice.

**Comment by veloce** [comment]
I don't think we should introduce new settings for such trivial things. We should keep it simple as much as we can.

**Comment by EmmetSchuler** [comment]
That's fair - just felt that because it differs from what people are used to we should support it. But I agree, definitely don't want to clog up settings.
