### ISSUE TITLE
Pieces sometimes disappearing in opening explorer

### ISSUE THREAD

**Issue by js31415926** [lichess-org/mobile#1027]
### What is the problem?

Sometimes pieces disappear in the opening explorer. Unable to reproduce in other tools. 

### Steps to reproduce the bug

Open Lichess
Open analysis board
Play e4 e5
Switch to opening explorer and back several times with explorer button and back button
Undo e4 e5 in explorer
Undo in analysis board
Go back to explorer
Exit app
Wait 10s
Re-open
Pieces are missing about 10% of the time

### App version

0.11.0

### Device Info

iPhone 14 Pro / iOS 17.6.1

### Additional information

I have had this happen using simpler methods but this method is the only one where I could get it to happen a second time and confirm what I did.

**Comment by js31415926** [comment]
While I was writing this I left lichess open and the bishops were gone when I came back.

**Comment by veloce** [comment]
Not sure to understand how to reproduce this.

When you say "exit app", I assume you want to say "put the app in background", right? (not killing it).

**Comment by js31415926** [comment]
Yes my bad

**Comment by veloce** [comment]
So far I can't reproduce the problem, and I find it weird that such actions could lead to disappearing pieces.

If you can post a screen recording of the issue, that'd be great! Thanks.

**Comment by js31415926** [comment]
Lmk if this worked.

https://github.com/user-attachments/assets/eb816575-2e1d-4902-a1ca-c294b9f97bbd
