### ISSUE TITLE
Audio from other apps is corrupted when Lichess app opens

### ISSUE THREAD

**Issue by Bundar** [lichess-org/mobile#1033]
### What is the problem?

When listening to audio from Youtube or Spotify through my wired headphones and I open the Lichess app the audio is very corrupted and it forces me to close the Lichess app. The Lichess app works normally apart from the audio. 

### Steps to reproduce the bug

1. Play music/audio through wired headphones
2. open lichess app
3. observe corrupted audio

### App version

8.0.0

### Device Info

pixel 9

**Comment by veloce** [comment]
Indeed... good catch! Closing because wrong repo.
