### ISSUE TITLE
Board scaling issues

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#1048]
From discord:

> I have an issue on my Flip phone where pieces are not aligned with the chessboard in game and problems mode, but everything seems fine in the other modes of the app(like analysis, openings Explorer)

But other issues have been reported. This is due to how we provide a fixed size to the board, that on some case conflict with parent's constraints.

We need a definitive solution to this problem.

**Comment by bhavikpanchal1111** [comment]
I am willing to solve this issue, so I would need developer access

**Comment by C4tw41k** [comment]
> Sorry for asking this here, do you think #979 might be related?

I think it is the same problem, and it happens on my Huawei tablet too.

https://github.com/lichess-org/mobile/issues/1021

I posted a picture to make it more clear.
