### ISSUE TITLE
Promote to queen automatically doesn't work when premoving

### ISSUE THREAD

**Issue by njamund** [lichess-org/mobile#1052]
### What is the problem?

I have "promote to queen automatically" set to Always, but when I premove a pawn promotion, it pops up the piece selection dialog instead of promoting to a queen automatically. If I do the pawn promotion without premoving, it promotes to queen automatically as expected. This issue occurs in the Lichess Beta mobile app on Android, but it does not occur in the web app using the Firefox Android browser; in the web app, it promotes to queen automatically even when premoving.

This issue started occurring with a recent update to Lichess Beta. 

### Steps to reproduce the bug

1. In the web app, go to Preferences. In the Game behavior tab, ensure that "promote to queen automatically" is set to Always.
2. In the Lichess Beta app, play a live game. (I played the computer on the lowest level in a 3/0 game.)
3. In the live game, make a premove to promote a pawn. 

### App version

0.11.0

### Device Info

Samsung Galaxy S20+ / Android 13

**Comment by veloce** [comment]
Thanks for reporting this! Will make a release soon with the fix.
