### ISSUE TITLE
Weird bug in game with various pieces disappearing (see videos)

### ISSUE THREAD

**Issue by ijm8710** [lichess-org/mobile#1055]
Reviewing the game after shows no proof of it happening but I did have a video of it

Only noteworthy thing was I was on a call while playing but doubt that's related 

https://github.com/user-attachments/assets/75d8d2c0-a809-45f2-98cb-ce6ea4673d19

**Comment by ijm8710** [comment]
Few more examples each is a different game https://github.com/user-attachments/assets/b362c103-ba92-4ad0-a8a2-8f176b7cb95f![image](https://github.com/user-attachments/assets/208cbfd2-c550-4275-92da-4139dab9853c)

**Comment by bhavikpanchal1111** [comment]
I am willing to solve this issue, so I would need developer access

**Comment by veloce** [comment]
Thanks for reporting, I believe this is the same bug as #1027 

It is an annoying one, but hard to reproduce. If you find a way to reproduce reliably please share.

**Comment by veloce** [comment]
> I am willing to solve this issue, so I would need developer access

there is no such thing as developer access. Feel free to fork the repo, you can find how to setup the project in the docs.

**Comment by ijm8710** [comment]
Hmmm @veloce one thing about me is I'm very heavy all over the place and bounce around apps a ton. Coincidentally, suspecting that may be a partial related cause, I just looked at other ticket and see them too had it happen when multitasking out of app.

So if I had to guess this probably can be best reproduced by multitasking and maybe lower ram? I know I was also on a phone call at same time. So I feel a bunch of things happening at once influenced it. Not sure if it helps catch it but still felt worth it to share this once.

**Comment by veloce** [comment]
I feel this is a regression, because this issue appeared only after I released a new version of flutter-chessground.

**Comment by veloce** [comment]
@ijm8710 I'm trying to understand this bug. In your game against `mezopeter`, in the screenshot we can see the knight disappeared. Could you finish the game normally? Was the knight captured at some point?

Another way to ask: is it purely a display bug that prevents the piece to be shown? but the engine knows that the piece exists and it doesn't prevent the game to be played?

**Comment by ijm8710** [comment]
Correct, seems most display as the disappearing piece was captured and also returned to show during post-game analysis

**Comment by EmmetSchuler** [comment]
I want to share this here as I've been seeing a lot of these posts in the Lichess Forum recently. Here are a few examples:

https://lichess.org/forum/lichess-feedback/bug-during-a-game-leads-to-a-loss

https://lichess.org/forum/lichess-feedback/crazy-phantom-moves-YGZN

https://lichess.org/forum/lichess-feedback/missing-moves

If these are linked to the bug here, possibly this could be more than just an app issue. Could loading and unloading the beta app and these network issues connecting to the website be linked?

**Comment by veloce** [comment]
Not sure it's related. They don't precise it is on the application, and missing moves are not the same as missing pieces.

**Comment by EmmetSchuler** [comment]
The first forum poster says "Hi, I was playing a game and my oponents knight on f3 was literally invisible on the board the whole game, so my pieces where dissapearing unexplicably. I found out about the knight only in the review when pieces appear"

This seems like more than just missing moves, but it's still hard to tell if they are related. However they share some commonalities.

**Comment by tom-anders** [comment]
Maybe it's also related to the impeller engine being disabled now?

**Comment by ijm8710** [comment]
Is there anything helpful to do if I reproduce again? Or would it help to have a special beta with log compiler?
