### ISSUE TITLE
Can't castle in real time Chess960 game

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#1095]
### What is the problem?

I encountered a bug in a Chess960 game today that makes castling impossible. In the past there were several issues with castling that are fixed by now but it seems like it's starting to get problematic again.

In #1024 I was writing about how it's not even possible to try castling in Over the Board Chess960 games. In that issue it was mentioned that there are problems with castling in real time Chess960 games too. Today I experienced that bug myself as well.

In a real time Chess960 game when I tried to castle, the clocks froze and after like 10 seconds my king and rook were literally put back to their original squares, exactly how it was described in the previous issue.

I want to bring attention to these issues because I really enjoy playing Chess960 and because it is supposed to be fully supported by now in the new app. Castling is a key element of the game of course, so this has to be fixed as soon as possible.

### Steps to reproduce the bug

1. Play a real time Chess960 game
2. Try to castle
3. Clocks freeze, the king and rook are forced back to their original squares

Please refer to the following screen recording:

https://github.com/user-attachments/assets/e7d00c83-283d-4240-869d-c9ac0a387607

The pieces getting forced back to the original squares had to be cut off from the recording because of the GitHub file size limit but you can see the clocks freezing immediately after trying to castle. 

### App version

0.12.2

### Device Info

Redmi Note 10 5G / Android 13

### Additional information

Link to the game if it's helpful somehow:

https://lichess.org/pihATFW4

I think it was around the 10th move or so when I tried to castle kingside which I couldn't do. On the 17th move the app let me castle queenside somehow.

**Comment by veloce** [comment]
Thanks for the detailed report.
