### ISSUE TITLE
Update not available in Google Play Store

### ISSUE THREAD

**Issue by njamund** [lichess-org/mobile#1097]
As of 2024-10-19, the Google Play Store shows version 0.11.0 as the latest for the Lichess beta app. However, I see in this repo that version 0.12.2 was created on 2024-10-15 and the "Deploy to Play Store" workflow was run. Is it expected that the Play Store's version appears to be from run 72 of the workflow even though there have been three runs after that? 

Screenshot from the Play Store:
![Screenshot_20241019_135416_Google Play Store](https://github.com/user-attachments/assets/451752a0-6f5f-4e92-918a-2fc49b26b7b8)

**Comment by veloce** [comment]
GitHub issues are not the right place to ask such questions. Use discord.
