### ISSUE TITLE
[Feature] change clock position (left/right) 

### ISSUE THREAD

**Issue by tom-anders** [lichess-org/mobile#1098]
Scrolled through Google Play reviews recently, and at least two people mentioned this feature. The argument is that your right thumb will obscure the clock while playing. Having an option to move the clock to the other side would fix this.

Apparently the old app has this feature as well.

**Comment by JozefSlawinski** [comment]
Hi, I can take on this one. 
![image](https://github.com/user-attachments/assets/3ced3f46-cbec-4020-a060-94f94f77db02)

Please take a look

**Comment by Jimima** [comment]
Added in #1136, I think this can now be closed
