### ISSUE TITLE
Kids mode

### ISSUE THREAD

**Issue by scaillib** [lichess-org/mobile#1099]
### What is the problem?

I cannot find settings to enable Kids mode (especially to disable chat in games). It is available on website and the legacy client under profile settings. And when applied it displays a smiley next to the login.

### Steps to reproduce the bug

1. Go to settings
2. No "kids mode" option

### App version

0.11.0

### Device Info

Android 12

**Comment by veloce** [comment]
Please don't open issues without searching first if the same issue exist.
