### ISSUE TITLE
On the join game page, the "Days per turn" displays "null" when the chosen time is infinite

### ISSUE THREAD

**Issue by miguelvg27** [lichess-org/mobile#1107]
### What is the problem?

On the join game page, the "Days per turn" displays "null" when the chosen time is infinite

### Steps to reproduce the bug

1. Open app
2. Press Play button
3. Choose Custom
4. Choose Join a game
5. Game list displayed

### App version

0.12.2

### Device Info

Pixel 8 / Android 15

### Additional information

Mobile app:
![WhatsApp Image 2024-10-21 at 12 19 25](https://github.com/user-attachments/assets/6c22995f-3932-4b1e-9616-51dedd75f0c5)

Web app:
![WhatsApp Image 2024-10-21 at 12 14 47](https://github.com/user-attachments/assets/5d15b71c-f8b3-4d4e-9142-6a7fe0e7aa12)

**Comment by veloce** [comment]
Thanks for the report!
