### ISSUE TITLE
Feature request: propose puzzle

### ISSUE THREAD

**Issue by stevexyz** [lichess-org/mobile#1124]
Many time it happens that when I analyze my games I find a position that I consider could be an interesting puzzle.
Would it be possible to add the possibility to propose that puzzle?
I think that this happens to many people, and puzzle will be then evaluated with the preference.
Surely it would be good also then to be able to search for all the puzzle proposed by some particular person.

**Comment by Boubou78000** [comment]
> Many time it happens that when I analyze my games I find a position that I consider could be an interesting puzzle.
> Would it be possible to add the possibility to propose that puzzle?
> I think that this happens to many people, and puzzle will be then evaluated with the preference.
> Surely it would be good also then to be able to search for all the puzzle proposed by some particular person.

I think it should more be a change to the web app than the new mobile app...

**Comment by stevexyz** [comment]
> I think it should more be a change to the web app than the new mobile app...

Do you mean https://github.com/lichess-org/lila ?

**Comment by Boubou78000** [comment]
Yes

**Comment by HaonRekcef** [comment]
Yes can be closed. Would be a feature for lila and has been discussed there already: https://github.com/lichess-org/lila/issues/8640
