### ISSUE TITLE
Broken layout on a square screen

### ISSUE THREAD

**Issue by slavaaaaaaaaaa** [lichess-org/mobile#1163]
### What is the problem?

On the full screen of a Samsung Fold 6, the in-game layout isn't quite usable as the move confirmation query and timers fall outside the visible area.

![Screenshot_20241117_181957](https://github.com/user-attachments/assets/1daeaa80-b79b-45e3-9c25-1cfc934abe7a)

### Steps to reproduce the bug

1. Start a game
2. Open the game on a fully open Samsung Fold 6
3. Struggle

### App version

0.12.5

### Device Info

Samsung Fold 6 / Android 14

**Comment by veloce** [comment]
To be sure: that is the unfolded screen here?

**Comment by veloce** [comment]
Do you have the dimensions of the screen please?
