### ISSUE TITLE
Studies - lag

### ISSUE THREAD

**Issue by Boubou78000** [lichess-org/mobile#1174]
### What is the problem?

When we click on next chapter, the screen blinks a few milliseconds...

### Steps to reproduce the bug

-

### App version

0.13.2 prerelease

### Device Info

android 14

### Additional information

-

**Comment by tom-anders** [comment]
@veloce this happens because we replace the whole screen with a circular loading indicator (and if the next chapter loads quickly, it looks like the screen flashes). My idea would be to instead only replace the "next chapter" button with a loading indicator while the next chapter loads. Wdyt?
