### ISSUE TITLE
Unable to open Private studies that I own

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#1175]
### What is the problem?

When opening a private study that you own, an error appears
![IMG_0266](https://github.com/user-attachments/assets/f8740311-1375-44c2-b58e-707c98cb0a55)

### Steps to reproduce the bug

Go to studies section
Filter by “my studies”

The user should have access to their studies, but instead an error appears as shown above.

### App version

0.13.2

### Device Info

iPhone 13 mini and IOS 18

**Comment by EmmetSchuler** [comment]
Edit: make sure the study is a private one, that you otherwise would have access to. Not just any study from 'my studies' list.

**Comment by miguelvg27** [comment]
Same un Android

**Comment by tom-anders** [comment]
@ornicar I think this is an API issue. I tried with `curl -X GET` and my API token, and also got `{"error":"This study is now private"}` back

**Comment by tom-anders** [comment]
The `lichess.org/api/study/<id>/<chapterId>.pgn` endpoint apparently has the same issue

**Comment by ornicar** [comment]
```
GET https://lichess.org/api/study/9ZwnBcW1/HQ8gEOdQ.pgn
Authorization: Bearer lip_prodtoken
```
works for me

**Comment by tom-anders** [comment]
Yes I have to correct myself, then PGN endpoint works, but the internal `lichess.org/study/<id>/<chapterId>` does not

**Comment by tom-anders** [comment]
Closed via https://github.com/lichess-org/lila/commit/57a715d478a0e02f8f7d1fa3804549c284f9a53d, thanks!
