### ISSUE TITLE
Computer Analysis shows wins as draws.

### ISSUE THREAD

**Issue by Mudhasi** [lichess-org/mobile#1181]
### What is the problem?

When you request a computer analysis. It shows a draw sign (½-½) for games which ended in wins.

### Steps to reproduce the bug

1. Play a blitz game
2. Request for a computer analysis
3. Navigate to the graph

### App version

0.13.2

### Device Info

Samsung A54 5G/ Android 14

### Additional information

![Screenshot_20241124_134440](https://github.com/user-attachments/assets/a347d3fe-f25a-4f94-8a29-a0c31a47abfa)

**Comment by NewSupKaizo55** [comment]
Does this happen with freshly completed games only or with older games as well? I tried to reproduce the bug and couldn't do it either way.

**Comment by Mudhasi** [comment]
> Does this happen with freshly completed games only or with older games as well? I tried to reproduce the bug and couldn't do it either way.

It happens for all games both new and old.

**Comment by Mudhasi** [comment]
This seems to have been solved in version 0.13.3
