### ISSUE TITLE
Board + moves list crashes

### ISSUE THREAD

**Issue by ghost** [lichess-org/mobile#1182]
### What is the problem?

When a study incorporates crazyhouse moves, the screen goes white...

### Steps to reproduce the bug

1. Go to a crazyhouse study
2. Click next move to a piece apparition

### App version

0.13.2 prerelease

### Device Info

android 14

### Additional information

![Before](https://github.com/user-attachments/assets/c5319fe5-050a-4c1b-80f6-d3cac3e72a11)

![After](https://github.com/user-attachments/assets/40ebcda7-d566-414e-990a-eccd28459cf2)

**Comment by tom-anders** [comment]
@veloce study chapters of the same study can contain different variants, so in theory your fix is a bit too aggressive - but I guess there aren't really any (popular) studies that mix crazy house and some other variant, so it's fine imo

**Comment by veloce** [comment]
Oh indeed. Displaying the chapters menu would be an easy way to solve this, what do you think? @tom-anders

**Comment by tom-anders** [comment]
> Oh indeed. Displaying the chapters menu would be an easy way to solve this, what do you think? @tom-anders

Yeah that sounds like a good solution. Maybe disable all the entries that have unsupported variants? Or show a Snackbar when selecting them

**Comment by veloce** [comment]
> > Oh indeed. Displaying the chapters menu would be an easy way to solve this, what do you think? @tom-anders
> 
> Yeah that sounds like a good solution. Maybe disable all the entries that have unsupported variants? Or show a Snackbar when selecting them

I tried to do that first, but the entries themselves don't have the variant info, just the study chapter ID.

**Comment by tom-anders** [comment]
> > > Oh indeed. Displaying the chapters menu would be an easy way to solve this, what do you think? @tom-anders
> > 
> > 
> > Yeah that sounds like a good solution. Maybe disable all the entries that have unsupported variants? Or show a Snackbar when selecting them
> 
> I tried to do that first, but the entries themselves don't have the variant info, just the study chapter ID.

Ahh right, forgot about that.
