### ISSUE TITLE
 ui is smaller than screen

### ISSUE THREAD

**Issue by moonfight1** [lichess-org/mobile#1186]
### What is the problem?

the apps ui is smaller than the screen 
![Screenshot_20241125-213825](https://github.com/user-attachments/assets/26757b00-9f40-4988-9d57-57c0f97c2e9c)

### Steps to reproduce the bug

1. open the app

### App version

0.12.5

### Device Info

Galaxy A8+ / android 9

**Comment by Boubou78000** [comment]
Maybe upgrade to 0.13.2 (using the apk file)

**Comment by moonfight1** [comment]
doesnt fix the issue

**Comment by Boubou78000** [comment]
👍
