### ISSUE TITLE
Missing the apk file of the 0.13.4

### ISSUE THREAD

**Issue by Boubou78000** [lichess-org/mobile#1194]
@veloce Can you add the apk file of the 0.13.4 release please?

**Comment by veloce** [comment]
No, I'm not adding anymore the apk for pre-releases. It is a pre-release, you'd have to wait for the release.

**Comment by Boubou78000** [comment]
> No, I'm not adding anymore the apk for pre-releases. It is a pre-release, you'd have to wait for the release.

Oh... How can I compile it as an apk file?
