### ISSUE TITLE
Study: Bring Navigation Arrows Together

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#1195]
Currently within studies, the navigation arrows are placed on the far opposite sides of the screen, with the next chapter button in the middle. This isn't consistent with the rest of the app design, and makes it tedious to navigate through the move list, which is especially necessary in studies.
![image](https://github.com/user-attachments/assets/d2c6936c-6147-4601-87ef-25f45c7015e2)
Bringing these arrows together on the right side of the screen with the next chapter button on the left feels like the way to go.

**Comment by Boubou78000** [comment]
Totally with you (I just did not want to spam veloce with enhancement suggestions 😁)
