### ISSUE TITLE
[Broadcast] Design inconsistency in the Round selector Menu

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#1205]
When viewing different broadcasts, the menu that pops up to switch rounds is not consistent. Sometimes it appears as the iOS selector widget, and other times as a dropdown list.
![image](https://github.com/user-attachments/assets/a888e894-255e-45bf-926d-36231e61df89)
![image](https://github.com/user-attachments/assets/43c1d9d5-72c1-48d1-8db2-6e30949a266a)
I feel the iOS widget should always appear, as it works well for broadcasts with many rounds, as well as those with less.

**Comment by Boubou78000** [comment]
> I mentioned this earlier on discord but from my finding it appears the cutoff is 10 whereby it will switch between the two types

Maybe the ios widget is worse when it has 10+ elements? Indeed, this would be a better approach than having 2 different widgets 😅

**Comment by ijm8710** [comment]
Although inconsistent with other parts of the app, I prefer ![image](https://github.com/user-attachments/assets/66d2352e-8da9-4b17-af5b-029e1d34c11f)

It allows it to be scrollable and it avoids the sliding picker format that's used on like iOS alarm which is a format I really hate. 

I also think it'll better support when more info is added on the elements such as the round's date/start time and completion/countdown status (such that you see on the mobile web version )

**Comment by Boubou78000** [comment]
@ijm8710 perfect 👍

But where did you find this week selection widget?

**Comment by EmmetSchuler** [comment]
> I mentioned this earlier on discord but from my finding it appears the cutoff is 10 whereby it will switch between the two types

There are broadcasts with less than 9 rounds that use each type. I don't think believe its round dependent, or at the very least more complex than that

**Comment by ijm8710** [comment]
Can you share one? I've looked at enough that I'd be very surprised if it wasn't round dependent 

The selector from Yahoo fantasy app

**Comment by EmmetSchuler** [comment]
It seems like you are correct with the cap of 10. I thought I had remembered seeing shorter using the iOS widget, but after looking around I can't find any matches

**Comment by Boubou78000** [comment]
> The selector example is from Yahoo fantasy app boubou

I don’t think we should take the design of a yahoo app...
