### ISSUE TITLE
[Study] Move Notation Highlights cause surrounding comments to jitter

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#1206]
When a move notation is highlighted, it slightly increases in size and as a result the surrounding text jitters along with it.
Although this is extremely minor, I think fixing this would improve the readability of the comments while shuffling through moves.

**Comment by veloce** [comment]
I don't see it, can you provide a screen recording please?

**Comment by EmmetSchuler** [comment]
https://github.com/user-attachments/assets/0e077a5f-3984-4d05-8f08-dbf389936bfd

One thing to note is this is recorded on an iPhone 13 Mini

**Comment by veloce** [comment]
https://github.com/user-attachments/assets/32f524e2-f1d4-4f79-a603-77834e959fe4

Just recorded that with my iPhone 13 mini on app v0.13.4 and the comments are not shifting. You did not provide the app version,  I assume it is the same?

Have you changed the system font size? that could perhaps explain the difference.

**Comment by EmmetSchuler** [comment]
Same version, 0.13.4, and my text sizes appear to be default Running iOS 18

**Comment by EmmetSchuler** [comment]
Fiddling around in settings and I found the difference! It doesn't jitter when using piece notation, but when using letter notation it does.

**Comment by veloce** [comment]
Good catch! Thanks for the investigation!
