### ISSUE TITLE
Broadcast keeps reloading when scrolling on watch tab screen

### ISSUE THREAD

**Issue by julien4215** [lichess-org/mobile#1221]
When scrolling past the broadcast widgets in the watch tab screen, the broadcast state is lost and reloads when scrolling up again. 

I don't know what is causing. Maybe it is linked to broadcast images ?

https://github.com/user-attachments/assets/c047e5ca-eade-4690-bb5c-ced22ea542cf

App version : 0.13.4

**Comment by veloce** [comment]
Because in a `ListView`, widgets that are not visible anymore are usually destroyed. If you initiate the provider in the widget, state is lost. It may be what we want, but if we don't want that behavior, the provider must be initialised in the parent of the list (here the screen widget).
