### ISSUE TITLE
Broadcast webscoket issue

### ISSUE THREAD

**Issue by julien4215** [lichess-org/mobile#1222]
When putting the app in the background while watching a broadcast game, the websocket connection may close after some time (several users reported this on Android and iOS but I can't reproduce myself consistently). The problem is that when putting the app in the foreground, the broadcast game controller is not invalidated and so some moves have been lost while the app was in the background.

Reproduce steps :
1. Watch a broadcast game that is live
2. Put the app in the background 
3. Wait
4. Put the app in the foreground
5. Compare with the website and see that moves were not updated in the mobile app

App version : 0.13.4

**Comment by veloce** [comment]
This can be solved with an `AppLifecycleListener`, and on app resume, fetch the whole state again.

You can find examples of this in the game controller for instance.
