### ISSUE TITLE
There seems to be a failure to recognize a game starting when searching for a game causing ban/timeout.

### ISSUE THREAD

**Issue by coredatarecovery** [lichess-org/mobile#1234]
### What is the problem?

Last 2 weeks I've been getting in timeout for no apparent reason, I'm DryIce username.
What I've discovered is when I search for a 1-0 game the window appears to be searching for a game forever, 
sometimes the corner board comes up with a ! in the upper right and if I hit cancel fast enough, I've got 3 seonds to make a move before it times out and locks me out of the system for an hour or so. I'm certain it's the only reason I keep getting knocked off line. This happens with a selection of 5-0 less frequently but a sort of work around is search for a game, then wait 10 seconds, then cancel the request, then wait 2 seconds, then click the board in the corner to see if there's a game in progress, then wait about a minuite to see if the request is fullfilled and pops up. Sometimes waiting works, and sometimes it just goes to a ban/timeout screen and locks me out of the ability to play and the time seems to increase for the timeout.
Can you fix this, and can you reset my timeout counter? 
I really do not ever ignore started games and I don't do obnoxious things ever (except winning).

### Steps to reproduce the bug

Open lichess
Select 1-0 game
wait for a game to be found.
Get banned for an hour and a half.
No ding, no pop up, no signal whatsoever a game was found.

open lichess,
select a 5-0 game
wait for a game to be found,
no sound, sometimes a board appears in the upper right corner with a ! or bang. Click cancel
click the board in the corner with the ! symbol.
Move within 3 seconds or I time out and get banned for an hour.

workaround:
open lichess
Select 1-0
Wait 10 seconds then select cancel
open the corner board, sometimes nothing is there.
Wait up to a minuite and sometimes a game pops up and opens and sometimes I go to the ban/timeout screen for an hour.

### App version

8.0.0

### Device Info

android 15, Pixel 8 Pro

### Additional information

I have no Idea how to appeal the obnoxious timeout for non starting a game,
I'm not trying to be obnoxious, just trying to use the app.
I also can't change to the web version and play as I'm also locked out there.

**Comment by EmmetSchuler** [comment]
From your version number, this seems to be an issue regarding the "lichoble," or original lichess app. This repository is for the new beta app that Lichess is working on. I would recommend posting this in https://github.com/lichess-org/lichobile if it isn't already a known issue.
In the meantime it might be better to stick to the website or give this beta app a try.

**Comment by HaonRekcef** [comment]
From lichobile, can be closed

**Comment by tom-anders** [comment]
@HaonRekcef thanks :)
