### ISSUE TITLE
PLEASE APK FİLE PLEASE 

### ISSUE THREAD

**Issue by AizenSuigetsu** [lichess-org/mobile#1244]
Can you add the apk file please?

**Comment by miguelvg27** [comment]
please 🙏🏼

**Comment by Boubou78000** [comment]
@veloce you've said the prereleases won’t be published as an APK file bcz we'd have to wait for the main release.

Would it make sense to make a beta program on Google Play, like Apple's TestFlight?

**Comment by tom-anders** [comment]
New 0.13.12 has an apk (as it's a regular release)
