### ISSUE TITLE
The biography resets when reducing the keyboard

### ISSUE THREAD

**Issue by Boubou78000** [lichess-org/mobile#1245]
### What is the problem?

When modifying your biography, if you reduce your keyboard it will revert your changes.

### Steps to reproduce the bug

1. Go to your profile
2. Change your biography 
3. Reduce the keyboard

### App version

0.13.2

### Device Info

Android 14

### Additional information

![Screenshot_20241209_083133](https://github.com/user-attachments/assets/9ca112b6-1443-4768-8ac8-a3a42cd836f8)
![Screenshot_20241209_083139](https://github.com/user-attachments/assets/bbad5baf-bd3b-4108-bab8-bd4246f3b860)

**Comment by nunibye** [comment]
I can try to fix this
