### ISSUE TITLE
Opening variation name is no longer present in the Explorer

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#1247]
### What is the problem?

If you go to any Opening Explorer screen, the name of the openings are no longer there.

### Steps to reproduce the bug

1. Open the Opening Explorer from the Tools tab or swipe to the Explorer from the Analysis or Broadcast screen
2. Play something on the board and check the name of the opening
3. _it's not there_

![Screenshot_2024-12-09-22-43-57-000_org lichess mobileV2](https://github.com/user-attachments/assets/a7f40021-2db3-49d9-a6f5-853d8f375b99)

### App version

0.13.6

### Device Info

Redmi Note 10 5G / Android 13

### Additional information

I really hope this is a bug and not an intentional removal. Seeing the name of a variation you've seen for the first time is obviously useful.

**Comment by ijm8710** [comment]
Yeah I tried bringing this up 3 weeks ago on discord but never heard anything back 

- also lost the wikibooks link
- not directly related but I also mentioned in that same update that we lost ability to drag the summary chart which I'm very disappointed about

**Comment by NewSupKaizo55** [comment]
Yeah the summary graph too. I wanted to mention that sometime as well but there are so many great things we get "instead" and I didn't want to flood the issues list 😅

**Comment by veloce** [comment]
You have the opening name in the move tab already, so I don't think it is needed here. There's a lack of vertical space in a lot of devices, so adding the opening name is more an inconvenient imo.
If you go to the standalone opening explorer screen, you still get the opening name, and the Wikibooks link.

**Comment by NewSupKaizo55** [comment]
This is the problem, it's not there in the standalone Opening Explorer screen either, so you can't reach the Wikibook link at all too.

![Screenshot_2024-12-10-12-55-34-957_org.lichess.mobileV2.jpg](https://github.com/user-attachments/assets/5995dd14-f7be-4ec6-9052-862ac3e4210e)
