### ISSUE TITLE
Add "Jump to next puzzle immediately" setting

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#125]
![Screenshot_2023-04-27-08-56-32-261-edit_com android chrome](https://user-images.githubusercontent.com/118524250/235244825-a7c715c4-ced9-4c69-a8c9-d2162bd2a5f2.jpg)
I'd like to suggest a feature that already exists on the Lichess website:

"Jump to the next puzzle immediately"

It's a very simple but very useful setting: if it's enabled, the user gets a new puzzle immediately after solving one correctly. It makes solving puzzles a much faster and smoother experience.

I don't have to knowledge to do it, nor do I know how difficult it is to implement, but in my opinion a lot of users would find it useful. Let me know what you think, if it's possible and if there is someone who could/would implement it. Thanks!

**Comment by EmmetSchuler** [comment]
This issue can be closed now
