### ISSUE TITLE
puzzle themes ignore app language set 

### ISSUE THREAD

**Issue by SergioGlorias** [lichess-org/mobile#1252]
### What is the problem?

puzzle themes ignore app language set 

### Steps to reproduce the bug

1. (Example) set your phone to portuguese
2. Set app in english
3. Go puzzle themes****

### App version

0.13.6

### Device Info

Samsung A34 / Android 14

### Additional information

https://github.com/user-attachments/assets/c514bb2e-119a-47fe-8f4d-ebc55aad0bea

**Comment by veloce** [comment]
Thanks for the report!
