### ISSUE TITLE
[broadcast] if move is already analysed, clock is not displayed after the move is played

### ISSUE THREAD

**Issue by HaonRekcef** [lichess-org/mobile#1257]
### What is the problem?

If the move in the live game matches a move already made on the analysis board, the chess clock doesn’t update, and the time for that player isn’t shown.

### Steps to reproduce the bug

1. go to a broadcast game
2. predict a move 
3. hope that this move happens in the game
4. observe the clock of the player that just moved and see that it is not present

### App version

0.13.6

### Device Info

-

### Additional information

Video:

[move-already-analysed.webm](https://github.com/user-attachments/assets/188c7123-e8cc-4c74-8bac-9d2ab5a96460)

I predicted that Nxd4 would happen and had already analyzed it. When it was played in the game, the white player's clock was not displayed, even though the position after Nxd4 was now on the board.

**Comment by veloce** [comment]
Thanks for all your precious reports!

This last one, I haven't tested it, hopefully it should work.
