### ISSUE TITLE
Multiple premoves 

### ISSUE THREAD

**Issue by Boubou78000** [lichess-org/mobile#1258]
Add the very useful option to make several premoves (that play in the order)

This feature already exists on chess com, and the only small complexity is to handle the new pieces’ positions when doing multiple premives.

**Comment by HaonRekcef** [comment]
This is something that would need to be on the main website first. It has been discussed there a lot: https://github.com/lichess-org/lila/issues/3890
This issue can be closed.

**Comment by tom-anders** [comment]
agreed, won't be added to the app unless the website gets it first
