### ISSUE TITLE
Broadcasts: BOT title does not have a different color 

### ISSUE THREAD

**Issue by SergioGlorias** [lichess-org/mobile#1261]
![Screenshot_20241213_071431.png](https://github.com/user-attachments/assets/7a0b4e3e-ee44-498b-b37d-82a41247f992)

 just a quick note as it is usually different

**Comment by julien4215** [comment]
Note for Veloce : this is already fixed in the broadcast player screen pull request.

**Comment by julien4215** [comment]
Can be closed
