### ISSUE TITLE
Puzzle Streak Reset after app Update

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#1262]
### What is the problem?

Updated the app from version 0.13.4 to 0.13.9 and my puzzle streak score had reset back to 0.

### Steps to reproduce the bug

Play a few puzzles on puzzle streak
Update the app
Check the streak 

### App version

0.13.4 / 0.13.9

### Device Info

iPhone 13 Mini iOS 18

**Comment by tom-anders** [comment]
Oh no, my bad probably, sorry for resetting your streak :(

@veloce it's possibly the good old issue of the preference key not being present yet after update

**Comment by ijm8710** [comment]
Should puzzle streak preserve if one force quits app/phone dies while playing. Meaning is it necessary to back out to get it to save or should it be saving progress after every puzzle player incrementally

Hopefully this is not considered a hijack. Slightly different from the op but I think it's related enough

**Comment by EmmetSchuler** [comment]
No worries, remember when just a week ago we couldn't even save streaks :) Thanks for all the work you do!

**Comment by tom-anders** [comment]
> Should puzzle streak preserve if one force quits app/phone dies while playing. Meaning is it necessary to back out to get it to save or should it be saving progress after every puzzle you succeed on incrementally
> 
> Hopefully this is not considered a hijack. Slightly different from the op but I think it's related enough

The answer is probably "yes, it should be saved after each solve".

But, Emmet's issue is different, if I understand correctly it's about the value in the server being reset back to 0, isn't it?

So please open a new issue for that

**Comment by tom-anders** [comment]
Oh, or did I mi

> > Oh no, my bad probably, sorry for resetting your streak :(
> 
> No worries, remember when just a week ago we couldn't even save streaks :) Thanks for all the work you do!

Oh, or did I misunderstand? Just the local score was reset?

**Comment by EmmetSchuler** [comment]
> Oh, or did I misunderstand? Just the local score was reset? 

The puzzle streak in the beta app was wiped back to 0, even though it was previously saved, yes.
On another note, do the saved streaks on the beta app sync to the website? Due to the way puzzles are batched it might be more complex, but from what I can see it doesn't.

**Comment by tom-anders** [comment]
On another note, do the saved streaks on the beta app sync to the website? Due to the way puzzles are batched it might be more complex, but from what I can see it doesn't.

Yeah it does not sync - but IIRC the website also does not sync between sessions. If you start a streak on your computer, and then open streak on you mobile browser, you start from 0 again as well.

**Comment by veloce** [comment]
We certainly don't want to sync streak session with the server. Streak session saving comes only as a convenience and must stay local.

**Comment by tom-anders** [comment]
@veloce was there any change that would reset preferences between 0.13.6 and 0.13.9?

**Comment by veloce** [comment]
Since you used a separate storage key, it could not have been deleted by any other prefs in the app @tom-anders 
So I don't know why it was deleted after app update.

**Comment by tom-anders** [comment]
Weird, @EmmetSchuler can you check if it happens in the next update as well, once it is available? Let's keep the issue open until then

**Comment by EmmetSchuler** [comment]
Fixed in 0.13.10
