### ISSUE TITLE
Suggestion: A Chess960 "tool" for OTB play

### ISSUE THREAD

**Issue by stephanhuebsch** [lichess-org/mobile#1320]
I'd like to propose a simple, small addition to the tools section of the app for OTB Chess960, which generates a valid starting position. Copying this position to a physical chess board ensures (1) a valid position and (2) a truly random position (as opposed to the players manually choosing pieces "at random").

**Comment by tom-anders** [comment]
You can use the "over the board" feature for this, see #618

(just select chess960 as the variant and hit "play", you'll get a random starting position every time
