### ISSUE TITLE
Center puzzles and decrease puzzle prompt size

### ISSUE THREAD

**Issue by marwanbayoumi** [lichess-org/mobile#140]
As seen in the screenshot, the puzzle prompt takes up too much space and puts the chess board way too high on the screen. This makes it very uncomfortable to do play the puzzles, given that phone screens are getting bigger. If I want to move a piece a large distance, I always have to awkwardly tilt my phone to be able to reach the intended spot. Which is very uncomfortable. Maybe by decreasing the prompt size, the ergonomics could be improved. 

![image](https://user-images.githubusercontent.com/27970739/235993176-40fa78f3-8608-427a-9031-d5fca62a9c09.png)

**Comment by nav-28** [comment]
The screenshot is from the old app. This repo is for the new app currently in development

**Comment by marwanbayoumi** [comment]
oh thank you can you tell me anything about an estimated release or if this issue will be fixed with the new app?

**Comment by nav-28** [comment]
I believe this is already fixed in the new app

**Comment by marwanbayoumi** [comment]
perfect thank you very much hope the new app drops soon 😃
