### ISSUE TITLE
Disabling "show legal moves" still show premoves

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#142]
From discord.

**Comment by csdodd** [comment]
FYI - I was unable to repro. This was working correctly for me on 0e665e69a30d5533cb7b2add6e361fcabd2efbe6

**Comment by veloce** [comment]
Yeah, actually I don't think there is a way to show premoves in the app right now. Closing then.

**Comment by eliogilvy** [comment]
I looked at this and it seems the board object shows valid premoves when showvalidmoves is false. Is this intended, or is showing valid moves different than showing valid premoves? If they are the same, then the bug exists and I have a fix for it that I can share...

**Comment by veloce** [comment]
If you look at the code yes, but since there is no way to have premoves right now, there's no bug.
