### ISSUE TITLE
Text is cut off by "..." on Puzzle Themes screen 

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#147]
In certain languages, the explanations of some puzzle themes are cut off by three dots, making the remaining text unreadable.

Example on the screenshot: Hungarian![Screenshot_2023-05-04-22-12-05-046-edit_org.lichess.mobileV2.jpg](https://user-images.githubusercontent.com/118524250/236319353-067c0015-b60e-4fdc-b845-5a3dd650f6a3.jpg)

**Comment by veloce** [comment]
You can long press to see the full text with a tooltip.
