### ISSUE TITLE
Bug with the evaluation bar

### ISSUE THREAD

**Issue by Malorra** [lichess-org/mobile#182]
After i solved the puzzle [https://lichess.org/training/oAK8V](url) there was a bug with the evaluation bar, when castling. When i tapped on the rook (h1) when castling, everything was right (+4.2), but when i tappped on the g1-square the evaluation bar jumped to -4.2.
I use version 0.1.1 on an android device.

https://github.com/lichess-org/mobile/assets/134768835/ac594c29-4e4e-4167-b626-7c5275652909

**Comment by veloce** [comment]
Looks like a bug with castling, thanks for the report!
