### ISSUE TITLE
Use another background colour on iOS

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#188]
Pitch black isn't ideal for a chess app.
Colors should be less contrasted, as in android.

**Comment by ijm8710** [comment]
Hey Veloce on this one, any chance to revisit real quick? One of the issues I raised on this one original is on iOS, the dark black that's used throughout the most of the app can be a bit much.

I know you added a bit more theming earlier in year so the board color matched some buttons but I'm talking the overall background.

On android, it seems the background actually absorbs that color more all-encompassing as part of its material theme and hence the pitch black isn't as abundant.

The screen this impacts most is game screen where 80% of background is still pitch black and overcontrasts the board.

While I'd love some it to be more in-line with how android gets themed, another alternative is to do what a lot of apps do where they provide 4 background color options:
- Device theme
- Light
- Dark
- dark Grey (this 4th one being the new one that's a dark but not pitch black)

Notice on chesscom how they are a few rows that are super dark but when you stare at game board, most of background around is it grayer than full black

![image](https://github.com/user-attachments/assets/1304c078-f6d8-4c2f-a2a6-e6c1ac4cfd9d)

**Comment by veloce** [comment]
I closed this as completed... because it is completed. The background color on iOS is not pitch black (far from it).

**Comment by ijm8710** [comment]
I hear you, I know accessibility has mattered and for some reason (maybe it's just me) the contrast is the biggest reason why I can only play 3 or 4 games on lichess before my eyes hurt and need to take a break but on chesscom I can play 3 hours in a row without issue. Generally like to be pretty level headed about issues but the greyer contrasted bg from chesscom does make a difference if there was a way to ever add a fourth background theme that was slightly less black

![image](https://github.com/user-attachments/assets/19551b04-3be0-4753-b4ae-b464b0a6aaed)

**Comment by veloce** [comment]
I agree it could be improved, but then it's another issue. All the background and text colors must be changed, so it's not "just" changing the background.

**Comment by ijm8710** [comment]
To be honest I actually think captured material should show as white/black as opposed to grey. Not sure if you agree that's worth ticketing? Besides that and maybe the notation up top, I don't think anything else would contrast poorly with a lesser black background on game screen. That's the only screen where I'd have much care for a change
