### ISSUE TITLE
Bottom bar issue due to Immersive Mode

### ISSUE THREAD

**Issue by nav-28** [lichess-org/mobile#199]
After the immersive mode update the bottom bar on archived game screen has been shitted below on Android

# Steps to reproduce 
1. Go to a fullscreen page e.g. Puzzle Storm 
2. Go to any archived game screen.

# Device
Pixel 6 emulator 
Reproduced on other android devices as well
![Screenshot_1686195494](https://github.com/lichess-org/mobile/assets/54973703/de125e7d-d8e7-4bcf-9047-14f07523b895)

**Comment by veloce** [comment]
Thanks for the report. I can reproduce too.
