### ISSUE TITLE
Desktop Support

### ISSUE THREAD

**Issue by ozbonus** [lichess-org/mobile#2]
Would it be worthwhile to add MacOS/Windows/Linux as supported platforms? It would allow for these platforms to play even without an internet connection, and Flutter would make it simple to build anyway.

**Comment by ffxsam** [comment]
It's a cool idea, but the website works pretty well as is. I can't see any particular advantages of having a dedicated desktop app (except maybe easier/better DGT e-board integration?).

**Comment by semog** [comment]
I've had a certain amount of experience with compiling native Flutter app for Windows/Linux/macOS as well as web app, so this is something that I will be taking a close look at contributing to the project. Having a nice standalone native application with the stockfish engine running would be great.
The biggest current drawback to Flutter cross-platform support is the lack of cross-compilation. You have to build on the platform you are targeting. Luckily, I have access to all three platforms.

**Comment by ffxsam** [comment]
What would you see as the advantages of having a native desktop app, compared to just using the website in a browser?

**Comment by schlawg** [comment]
The flutter app will be heavily geared towards touch.  I don't think the mac, windows, and linux targets that flutter puts in the starter project would even survive the dependencies we'll be adding, and I'm not sure Vincent wants to worry about supporting mouse & keyboard.  

If you can't use a browser because you don't have internet on your computer, there is always catalyst and android compatibility layers if you must run lichess mobile on desktop to get at the puzzles.

**Comment by ozbonus** [comment]
> The flutter app will be heavily geared towards touch. I don't think the mac, windows, and linux targets that flutter puts in the starter project would even survive the dependencies we'll be adding, and I'm not sure Vincent wants to worry about supporting mouse & keyboard.
> 
> If you can't use a browser because you don't have internet on your computer, there is always catalyst and android compatibility layers if you must run lichess mobile on desktop to get at the puzzles.

That's reasonable. I guess after the mobile app is stable someone can take a shot at a desktop fork if they really want.

**Comment by M7rc7ry** [comment]
The main dartchess package used in this app can not have 64bit Int types published for web via flutter due to current javascripts ^54 limitation. The package have would to be converted to use fixnum package or strings before you could begin converting this app for web. If anyone has done this conversion please let us know.

**Comment by PunchCakee** [comment]
> The main dartchess package used in this app can not have 64bit Int types published for web via flutter due to current javascripts ^54 limitation. The package have would to be converted to use fixnum package or strings before you could begin converting this app for web. If anyone has done this conversion please let us know.

No point in making a webapp when lichess.org already serves the same exact purpose. A desktop app would be a killer feature though

**Comment by veloce** [comment]
Closing because out of scope, as explained in the comments.

**Comment by christianfl** [comment]
Hey @veloce Would you by any chance re-evaluate that decision?

There is a growing community of people with Linux phones such as the Librem 5 or the PinePhone. The hardware is a bit limited so native applications are usually the better way there (if possible). I'd have to admit, it is very niche at this moment but the community is appreciative.

I could already test that LichessV2 works on Linux Desktop with a few modifications. If you would contemplate merging something, I'd work on a PR for Linux support.

The devs did a great job here, there seem to be only a few modifications possible, e.g.:

- Adding linux target for Flutter
- A current bug in flutter_secure_storage leads to a few necessary string changes until upstream fix is present (https://github.com/juliansteenbakker/flutter_secure_storage/issues/920)
- Init sqlite db
- Add TargetPlatform.linux in your `platform.dart`
- Remove Firebase on Linux for now (could be replaced with [Unified Push](https://pub.dev/packages/unifiedpush) in the future if wanted) and adapt LocalNotifications
- Deactivate your SoundService for now, supporting Linux should be no problem to add I guess

All in all it was well usable then! Puzzle Streak was a lot of fun 🕺

**Comment by Henry-Hiles** [comment]
I agree, I'd love a nice app to play chess on my Linux phone! Would you at least accept a PR?

Also @christianfl, do you have that build as a flatpak or smth?

**Comment by veloce** [comment]
> Hey [@veloce](https://github.com/veloce) Would you by any chance re-evaluate that decision?
> 
> There is a growing community of people with Linux phones such as the Librem 5 or the PinePhone. The hardware is a bit limited so native applications are usually the better way there (if possible). I'd have to admit, it is very niche at this moment but the community is appreciative.
> 
> I could already test that LichessV2 works on Linux Desktop with a few modifications. If you would contemplate merging something, I'd work on a PR for Linux support.
> 
> The devs did a great job here, there seem to be only a few modifications necessary, e.g.:
> 
> * Adding linux target for Flutter
> * A current bug in flutter_secure_storage leads to a few necessary string changes until upstream fix is present ([Linux deprecated literal operator juliansteenbakker/flutter_secure_storage#920](https://github.com/juliansteenbakker/flutter_secure_storage/issues/920))
> * Init sqlite db
> * Add TargetPlatform.linux in your `platform.dart`
> * Remove Firebase on Linux for now (could be replaced with [Unified Push](https://pub.dev/packages/unifiedpush) in the future if wanted) and adapt LocalNotifications
> * Deactivate your SoundService for now, supporting Linux should be no problem to add I guess
> 
> All in all it was well usable then! Puzzle Streak was a lot of fun 🕺

Sorry @christianfl for the late reply on this.

I have nothing against adding another target as long as it doesn't bring more maintenance work. We could have a flutter linux target indeed it might be useful also for devs who want to simply try the app on linux.
We would have to make clear that we don't deal with bug reports for unsupported targets.
I don't make any promise, but you can try a PR if you want; if it is not adding extra complexity in the app code I might accept it.

**Comment by christianfl** [comment]
You're welcome @veloce I created a PR for initial linux support.

@Henry-Hiles Currently only as an executable. But let's see what happens here first 🙂

**Comment by veloce** [comment]
Note that it was perhaps not that clear in my previous message, if we add extra target, it is only for devs usage. Meaning that no effort will be made on lichess side to maintain the other targets than iOS and android. I shall add documentation about that anyway if we merge the pr.

**Comment by Henry-Hiles** [comment]
> Note that it was perhaps not that clear in my previous message, if we add extra target, it is only for devs usage. Meaning that no effort will be made on lichess side to maintain the other targets than iOS and android. I shall add documentation about that anyway if we merge the pr.

Sure, but if it's merged it'd be easy to make unofficial packages elsewhere on  Linux.

**Comment by Henry-Hiles** [comment]
Hi @christianfl, did you ever make a flatpak?

**Comment by christianfl** [comment]
Not yet @Henry-Hiles 

I think it would be nice to have a third party Flatpak (the developer stated, Linux is not planned to be supported officially) that gives the same experience as the Android/iOS apps. Afaik there are 2 things needed:

- adding Linux support for the https://pub.dev/packages/sound_effect plugin if the developers would merge something
- enabling Unified Push for Linux (in the meantime it seems, UP support has been added for Android, so the code changes should be contained again, here)

With those changes, no further patches are needed if things haven't changed and only a manifest / builds would be needed
