### ISSUE TITLE
Dev apk for testing

### ISSUE THREAD

**Issue by HarshilPatel007** [lichess-org/mobile#208]
Hello devs,

I want to test this on-going dev version of the app. It'll be easy for end users to test the dev app if provided a dev builds. We can utilise the GitHub actions to do this automatically for us.

**Comment by vaibhavsection** [comment]
@HarshilPatel007 
Yes
I want too...

**Comment by tedzards509** [comment]
Can't you just build the app for yourselves then? It sounds a bit tideous to build the app with every change.

**Comment by nav-28** [comment]
Hello I appreciate the enthusiasm about the app but please don't create issue just to ask questions. Thats's what discussions are for. 

Currently there is a testing program for the app in Lichess Discord. You can get the instructions to join the testers group from the welcome page when you join the discord.

**Comment by PunchCakee** [comment]
Check my fork
