### ISSUE TITLE
Immersive Mode gets disabled in Storm

### ISSUE THREAD

**Issue by nav-28** [lichess-org/mobile#209]
# Steps to reproduce 
1. Play a run of storm
2. Go to puzzle screen from storm result 
3. Go back to storm screen. 

Immersive mode gets disabled after exiting puzzle screen and stays disabled in storm screen as well.

**Comment by veloce** [comment]
Only disabled in Storm? not in other board screens?

**Comment by nav-28** [comment]
Haven't seen it in other screens. I think it is cause when puzzle screen is popped off it disables immersive mode and then it goes back to storm.
