### ISSUE TITLE
Haptic feedback settings not applied everywhere

### ISSUE THREAD

**Issue by kneuner** [lichess-org/mobile#210]
iOS 17 beta 1

1. Disable haptic feedback in profile > settings > board settings
2. Haptic feedback still occurs some places, such as after completing a puzzle in training, the _next_ button (to replay moves) is haptic.

**Comment by veloce** [comment]
Well, yes but that's board settings, not general haptic settings so that's normal.

**Comment by kneuner** [comment]
Okay, thank you. That makes sense. I thought I noticed that it disabled haptic feedback in other places too but it seems I was mistaken.

**Comment by veloce** [comment]
Closing then.
