### ISSUE TITLE
Hide rating settings

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#219]
Create a "hide rating" switch (discord request). Same as in the website:

> This allows hiding all ratings from the website, to help focus on the chess. Games can still be rated, this is only about what you get to see.

This preference should be sync with server so this issue cannot be done until user prefs sync is in place.

**Comment by EchedelleLR** [comment]
When a user is challenged, the rating of the challenger is still showed before accepting or refusing even if this switch is enabled to hide it.

**Comment by EchedelleLR** [comment]
@veloce could you reopen?
