### ISSUE TITLE
Misaligned piece on the board when viewing app in an android popup window

### ISSUE THREAD

**Issue by S1M0N38** [lichess-org/mobile#220]
![IMAGE 2023-06-27 14:30:40](https://github.com/lichess-org/mobile/assets/22257750/f9423ed3-039a-4226-9b37-87629d4cb9bd)

Puzzle in popup window with the device in the landscape orientation has misaligned pieces.
In this example I've open a game that use landscape mode (e.g. fruit ninja) and the open lichess in a popup window. Then I've started a new puzzle streak. 

I'm on an android phone

**Comment by ZTL-UwU** [comment]
![Screenshot_2023-06-27-21-55-57-944_org.lichess.mobileV2.jpg](https://github.com/lichess-org/mobile/assets/49156174/25c190c0-e865-42c9-a0ec-599aaf96956d)

There are overflow problems as well.

**Comment by veloce** [comment]
Thanks for the report. I did not even know you could do that on android!

I think we should fix the misaligned pieces but not the overflow. This is an edge case and people using that feature can just make a window geometry that avoid overflows.

**Comment by ZTL-UwU** [comment]
> This is an edge case and people using that feature can just make a window geometry that avoid overflows.

The size and aspect ratio of the popup window is not actually adjustable.

**Comment by nav-28** [comment]
> > This is an edge case and people using that feature can just make a window geometry that avoid overflows.
> 
> The size and aspect ratio of the popup window is not actually adjustable.

Is there a use case for the app to be used as a popup? I think we should disable the app for split screens and popup windows.

**Comment by veloce** [comment]
Ah yes certainly, if we can do that let's just disable it. There's certainly no use case for split screen.
