### ISSUE TITLE
Next/Previous move buttons long press behavior

### ISSUE THREAD

**Issue by tedzards509** [lichess-org/mobile#228]
In the screen on puzzle completion, the next/previous move RepeatButtons (puzzle_screen.dart line 339-364) have a child BottomBarButton with a label. The expected onLongPress behavior should be skimming through the moves, but if you press on the icon, the label is shown instead.

**Comment by nav-28** [comment]
Thanks for the report. Seems like this issue is only on android with the tooltip and the repeat buttons conflicting for long press.
