### ISSUE TITLE
When the board is flipped, the nicknames of the players change, but the value remains from the previous player

### ISSUE THREAD

**Issue by Tevajs** [lichess-org/mobile#232]
Here you can see video:

https://github.com/lichess-org/mobile/assets/131544628/62b5f229-371b-4607-94d5-cdbdff3ed12a

**Comment by nav-28** [comment]
Hello thanks for the report. This repo is for the new mobile app, and this issue is for the old. 
You can file it in the other repo https://github.com/lichess-org/lichobile
