### ISSUE TITLE
Blinking pieces

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#236]
Can reproduce on android, when resuming the app from pause in puzzle screen.
Probably happen elsewhere as well.

**Comment by nav-28** [comment]
Also reproducible on the example app of chessground, when resuming the app after playing a move.

**Comment by nav-28** [comment]
Yes, probably it's clearing the image cache when stopped and reloading it when resuming. I couldn't find an issue on the flutter repo which relates to this problem.

**Comment by veloce** [comment]
I haven't reproduced in a while, so I'm closing this. Perhaps fixed by recent chessground update.

**Comment by veloce** [comment]
I still see the issue from time to time. Mostly when resuming the app from pause.

Not a blocker for a beta app, but we should address this eventually.
