### ISSUE TITLE
Puzzle rating doesn't change after puzzle is solved/failed

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#238]
After a rated puzzle is solved or failed, the icon of the puzzle on the bottom of the screen shows the rating change but the puzzle rating doesn't change. It stays the same even after a new puzzle was shown.

The only temporary fix is to "refresh" by changing the puzzle difficulty.

Screen recording of the bug (it is too large for GitHub) :

https://streamable.com/80u14i

**Comment by veloce** [comment]
Closing since a fix was made server side.
