### ISSUE TITLE
Provide apk file in every release.

### ISSUE THREAD

**Issue by TheAlphaApp** [lichess-org/mobile#239]
I can see that in the release page there are two versions 0.3.1 and 0.3.2 available. An apk file should be provided with every release in the that page so that "non-technical" people can use and provide feedback.

**Comment by vaibhavsection** [comment]
Yes please provide alpha/beta apk

**Comment by veloce** [comment]
Perhaps we'll do that later, but the easiest way to test the app right now is to go to the lichess discord as ask to be part of the user testing program.

**Comment by PunchCakee** [comment]
my fork has a CI script that provides debug binaries for android
https://github.com/PunchCakee/mobile

**Comment by nav-28** [comment]
> my fork has a CI script that provides debug binaries for android
> https://github.com/PunchCakee/mobile

I would not recommend building the app against prod cause it might be flagged if you try to play games on it as it is not the official app.

**Comment by PunchCakee** [comment]
> > my fork has a CI script that provides debug binaries for android
> > https://github.com/PunchCakee/mobile
> 
> I would not recommend building the app against prod cause it might be flagged if you try to play games on it as it is not the official app.

So far i didnt encounter any issues, its open source after all its a huge problem if i get banned because i compiled my own mobile app.

**Comment by Mansour-J** [comment]
Yes I don't 

> > > my fork has a CI script that provides debug binaries for android
> > > https://github.com/PunchCakee/mobile
> > 
> > 
> > I would not recommend building the app against prod cause it might be flagged if you try to play games on it as it is not the official app.
> 
> So far i didnt encounter any issues, its open source after all its a huge problem if i get banned because i compiled my own mobile app.

I agree, I don't understand why would they ban. I am planning to build my own version of the app with more themes. Like Neo pieces and etc. Why would they ban it?

**Comment by HaonRekcef** [comment]
can be closed, APKs are included in the releases now

**Comment by landry314** [comment]
apks for 0.15.14 and now 0.15.16 both have not been released on github. i use obtanium to download updates and id love to go right to the source.

**Comment by landry314** [comment]
oh they are prereleases. how would i install the prerelease? compile it myself?
