### ISSUE TITLE
User activity feed

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#24]
Add the user activity feed section on profile screen.

See it on lichess: https://lichess.org/@/veloce

API reference: https://lichess.org/api#tag/Users/operation/apiUserActivity

Design notes: the list should stay short, so we should show only the most important items, and keep one line per item. Example: don't show the followers in the "Gain X followers" item.

Ideally it should be place above the "recent games" section:

<img width="411" alt="Capture d’écran 2023-01-09 à 15 37 06" src="https://user-images.githubusercontent.com/423393/211333345-add85255-d066-44a0-8c10-bb6935c29344.png">

**Comment by vrund297** [comment]
I am chess Player with around 1900 lichess & backend developer too.
can you please assign this issue to me?

**Comment by vrund297** [comment]
@veloce

**Comment by schlawg** [comment]
You can work on it without being assigned.

**Comment by veloce** [comment]
Here you are @vrund297 . I missed your ping, and indeed you can work on it without being assigned but if you do so the best is to inform me on discord.

If I don't respond on GitHub, you can also reach on discord.

**Comment by veloce** [comment]
Closed by https://github.com/lichess-org/mobile/pull/116
