### ISSUE TITLE
Friends popup

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#242]
Implement friends popup.

![Home friends](https://github.com/lichess-org/mobile/assets/423393/a3e25d25-df31-429a-b739-39ca973c09e4)

This is a full screen popup accessible from the home tab button in the top right.

Online friends are fetched with a websocket API.

Suggestions need a server endpoint that does not exist yet, so it can be done later.

Tapping "More" goes to another popup with all friends. If no friends are online, a "Friends" button should be displayed under the "0 friend online" title.

This endpoint can be used to fetch all friends for the 2nd popup: https://lichess.org/api#tag/Relations/operation/apiUserFollowing

In order to unfollow someone, we'd swipe the tile to the left to uncover the unfollow action, as shown in the wireframe.

More actions will be available later, when available, like "challenge", "PM", etc.

Follow and unfollow endpoints are also documented.

**Comment by BeardedAmbivert** [comment]
I would like to implement this if someone hasn't started working on this. Thanks!

**Comment by papo1011** [comment]
Hi everyone! I'm working on this issue and I'm making good progress.
I started to open draft pr #337 and maybe you want to give some feedback :)

**Comment by veloce** [comment]
Sure, will do asap!

**Comment by NewSupKaizo55** [comment]
Is there going to be a "Challenge friend" button like in the old app? Is a new separate PR for the challenge user function needed?
