### ISSUE TITLE
Leaderboard screen

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#25]
Corresponding lichess page: https://lichess.org/player

Lichess API reference: https://lichess.org/api#tag/Users/operation/player

**Comment by nav-28** [comment]
The screen would be added to the bottom nav for now, right?

**Comment by veloce** [comment]
No I don't think we'll add it to the bottom nav. I have to figure out where to put it indeed :)

**Comment by veloce** [comment]
See: https://github.com/lichess-org/mobile/commit/4eef5df186d53c49c62eb4da8692f035df3d1ba7

Now there's a home page. Put the leaderboard here (one line per perf, as in lichess.org home), and a link to the detailed leaderboard.
