### ISSUE TITLE
Puzzle rating lag

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#258]
Discord report:

Expected behavior: puzzle rating sits at 1704. Player fails puzzle that was worth -19. Next puzzle loads and puzzle rating is showing 1685.

Current behavior:  puzzle rating sits at 1704. Player fails puzzle that was worth -19. Next puzzle loads and puzzle rating is still showing 1704. Player wins next puzzle for +34. The next puzzle loads, you would expect the rating to go up since he succeeded on his last puzzle. It’s actually gone down, it’s showing 1685 since it’s registering the -19 (the subsequent +34 puzzle hasn’t processed yet and only will on the next next puzzle)

More info: puzzle rating adjustments are registering with a t+2 lag rather than a T+1 lag. This has only started happening in the latest public beta

**Comment by NewSupKaizo55** [comment]
Please check #238, this was already happening in the previous version. Thanks!

**Comment by veloce** [comment]
Indeed it's a duplicate.
