### ISSUE TITLE
In game chat

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#279]
![Game chat](https://github.com/lichess-org/mobile/assets/423393/927f6eef-90f1-45d8-a442-18badf800527)

TODO:

- [ ] show chat in archived game screen
- [ ] consider a settings to disable chat by default

**Comment by julien4215** [comment]
#339

**Comment by kkorus** [comment]
I would like to consider giving option to disable in game chat for every game so it would be applied for each live game, thanks!

**Comment by nav-28** [comment]
@veloce this can be closed now right?

**Comment by veloce** [comment]
I'm waiting to add chat in the archived game screen before closing the issue. And I needed some server update before doing it.
