### ISSUE TITLE
Puzzle themes' description are cut out

### ISSUE THREAD

**Issue by NovaliX-Dev** [lichess-org/mobile#286]
Here are some screenshots of the problem (translated in French, not sure if that happen in other languages)

![image](https://github.com/lichess-org/mobile/assets/79244938/901420c1-54a0-4981-a63a-4b1df7e46188)
![image](https://github.com/lichess-org/mobile/assets/79244938/8ad9547b-bc0d-4c95-8454-8cc096d588a0)

The description of some of the catégories are not shown entierly, ending with "..." instead.

**Comment by NewSupKaizo55** [comment]
iirc it is called a "tooltip" or something like that, you have to long press it and a small textbox appears with the full text for a few seconds. Pretty cool stuff.

**Comment by NovaliX-Dev** [comment]
Oooh i didn't know about that. Thank you !

But shouldn't be the description shown entirely beneath the category titles ? It would make far more sense imo.

I guess it's cut out to make the categories' height more consistent ?

**Comment by NovaliX-Dev** [comment]
Or we can add a small info icon at the top left corner, to explain how to show the full description, but this will be less great from a UX perspective

**Comment by NewSupKaizo55** [comment]
> I guess it's cut out to make the categories' height more consistent ?

That makes sense, yeah I think that's the reason why tooltips are used there. If you think about it, it's consistent and not too difficult to use if you know that you have to long press it. Maybe there should be a hint so everyone knows how to actually use it.

**Comment by NovaliX-Dev** [comment]
> Maybe there should be a hint so everyone knows how to actually use it.

We agree on that.

**Comment by veloce** [comment]
The reason it's cut is that flutter list tile widget requires a subtitle of 2 lines on android. 

Better than a tooltip would be an expand maybe. And a hint would be nice. 

I'll rework that list soon maybe i can improve that

**Comment by NovaliX-Dev** [comment]
We should try the two versions to see which is the best for the most people though, both have advantages and drawbacks.

I find kinda frustrating to click long and not see the description directly, especially when the description is like only one line longer. Maybe i'm a UX nerd to complain about that lol.

I'm not sure if the consistency of the themes height is such a big deal. For example, most of the descriptions fill 2 lines, some 3 and rarely 4 in my language. So if we show all the lines that would be pretty consistent imo. I didn't check the descriptions in the other language, so i can't guarantee this consistency for them. 

We should check if the translations are small enough. Maybe adding a limit of words for the translation can fix the consistency problem.

**Comment by NovaliX-Dev** [comment]
> Better than a tooltip would be an expand maybe.

On one hand this can resolve or height consistency issue and we can add mores things (for example a chessboard of the current puzzle on this theme) to show when an element is expanded.

On the other hand this would require two touch instead of one, so from a UX this will be worse than the way it's currently.

> And a hint would be nice.

Another idea (derived from veloce's proposal) what adding a little icon aside each title.

When we click on them, either the description is expanded or shown as a dialog. If we click on the titles or the rest of the element's body, we should be conducted to the puzzle.

The icon is will difer (a hint on the right if it's a dialog, or a small arrow on the left (like the "Plus" on the puzzle tab) if it's an expand).

**Comment by veloce** [comment]
Fixed now.
