### ISSUE TITLE
Text size of previous puzzle rating changes is inconsistent

### ISSUE THREAD

**Issue by kneuner** [lichess-org/mobile#289]
When solving a series of puzzles, the icons that are added below the board to indicate rating change sometimes have inconsistent text sizing.

![IMG_8251](https://github.com/lichess-org/mobile/assets/133548179/717a1af7-d053-44ac-b2c9-fec6aac9b0d6)

(E.g. the -7 and the -3)

Version 0.3.5, iOS 17

**Comment by HaonRekcef** [comment]
can also be closed due to #1241
