### ISSUE TITLE
"Daily Puzzle" in navigation bar should change to "Puzzle Training"

### ISSUE THREAD

**Issue by kneuner** [lichess-org/mobile#290]
After attempting the daily puzzle from the main screen and continuing to solve more puzzles, the title in the navigation bar continues to display the "Daily Puzzle" title, but it would make more sense to change to "Puzzle Training" as is displayed when starting a puzzle session from the puzzles screen.

**Comment by veloce** [comment]
Would be nice indeed but it's not a trivial change unfortunately. 
That's why I left it that way because I felt it was not worth the trouble.
