### ISSUE TITLE
Rework puzzle themes

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#310]
![Puzzle custom](https://github.com/lichess-org/mobile/assets/423393/0c8b6d05-5a4b-457b-bc38-f5b6f0d9df0d)

There are 2 new endpoints to handle this:

- GET 'https://lichess.org/training/themes' 'Accept:application/json'
- GET 'https://lichess.org/training/openings' 'Accept:application/json'

Both will get theme (or opening) keys and associated puzzle count. 

Attention points:
- [ ] execute these requests first time the screen is accessed and then cache data in memory. 
- [ ] if the screen is accessed offline, then only themes where a batch has been saved should be displayed (without expansion tile)
- [ ] icon set visible in this page should be used: https://lichess.org/training/themes
- [ ] [ExpansionTile](https://api.flutter.dev/flutter/material/ExpansionTile-class.html) widget should be used
- [ ] inner lists should be implemented with existing app `PlatformListTile` and `ListSection` widgets
- [ ] `PuzzleBatchStorage` is using the `PuzzleTheme` as key right now, it should be refactored to use a `PuzzleAngle` which can be either a theme or an opening

**Comment by Mansour-J** [comment]
https://lichess.org/training/themes has icons for all the categories - maybe we could leverage these icons in the app as visual guide as well. I just noticed these icons and I think they're new. They're looking god.

**Comment by veloce** [comment]
Yes this is one of the bullet point.
