### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#311]
I don't want to complain at all, but there are some issues with the translation in the app right now.

![Screenshot_2023-09-15-15-39-54-308_org.lichess.mobileV2-edit.jpg](https://github.com/lichess-org/mobile/assets/118524250/c9476136-bbf8-453e-9604-3337b928ba58)

On the puzzle screen, the descriptions of the  Storm and Training modes are not translated at all.

On the navigation bar, "Home" should be translated as well (in this case I recommend "Kezdőlap" which means "starting page" in Hungarian.)

![Screenshot_2023-09-15-15-39-32-091_org.lichess.mobileV2-edit.jpg](https://github.com/lichess-org/mobile/assets/118524250/c31f2daf-cf21-4686-8a49-e6d659fbe6f8)

On the Home page and on the Profile page, the displayed timeago is very wrong.
(in this case "ezelött egy nap e" means "before one day e" which could be translated as "egy napja", that simply means "a day ago"). The character "ö" in "ezelőtt" should be "ő" (I know it's not that important now, apologies for making such a fuss about it!). 

On the game analysis page, the title of the page could be much better translated (in this case "Játék elemzés" means literally "game analysis" but a much better "Elemzőtábla", meaning "Analysis board" is used almost everywhere on Lichess.)

I know this is a very special case and I can't speak every language - I can only tell about what I see. Thank you for caring about translations this much!

**Comment by veloce** [comment]
Some translations are just not available yet.

But for timeago, this is a dependency, there's not much I can do here.

You could try to open a PR in their repo though: https://github.com/andresaraujo/timeago.dart

**Comment by NewSupKaizo55** [comment]
> But for timeago, this is a dependency, there's not much I can do here.
> 
> You could try to open a PR in their repo though: https://github.com/andresaraujo/timeago.dart

Thanks for telling me about this, I opened an issue about the incorrect translations there. I hope they will notice it.

**Comment by veloce** [comment]
Closing it because we already have #98 for missing translations.
