### ISSUE TITLE
Puzzle Storm timer doesn't start

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#312]
I just noticed this bug randomly while playing Puzzle Storm. Please refer to the attached screen recording:
https://github.com/lichess-org/mobile/assets/118524250/5dcf9757-f93a-4418-b9e1-dc07e5cacea3

Out of nowhere after starting a new run after finishing one, the timer didn't start counting down but I was able to freely solve the puzzles.

Expected behavior: The Puzzle Storm timer starts counting down after making the first move on the board.

What happened instead: The Puzzle Storm timer did not start counting down while solving the puzzles was allowed.

Method to recreate the bug: unknown

After starting a new run, the bug was still present, I had to exit and restart the app to resolve the issue. I have no idea how to recreate this.

**Comment by nav-28** [comment]
Thanks for the report. Looks like regression from the new changes. I can reproduce it. Basically on the new run on storm screen the timer doesn't work.

**Comment by NewSupKaizo55** [comment]
Wow, that was fast. Thanks for your work!
