### ISSUE TITLE
Puzzle Streak Save

### ISSUE THREAD

**Issue by TheHypnotist333** [lichess-org/mobile#324]
The expected behavior of puzzle Streak is that it saves your progress until you get one wrong. This is how it always worked online but the way it is in this app it ends the streak as soon as you close out. This will make it pretty much impossible for us to beat our high scores. We should be able to close out and let our minds rest for a moment and pick up where we left off with the puzzle. My high score is 46, I cannot approach this in one sitting. Some people have over 100.

**Comment by TheHypnotist333** [comment]
Imagine having a very high high score and so the only time you can play is if you have 4 uninterrupted hours on your phone to play the streak. It is unrealistic. It becomes more about how much time you have and less about how many you can get correct in a row

**Comment by csaavedra** [comment]
Support this request.
