### ISSUE TITLE
Analysis context actions

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#338]
Add the following context actions to analysis screen:

- delete variation
- promote variation
- make variation mainline

![Analysis context actions](https://github.com/lichess-org/mobile/assets/423393/af997b2d-b646-4922-9c16-279a07e8861f)

Notes:
- [ ] trigger context menu by a long press on any move from the variation in the tree view
- [ ] use `showAdaptiveActionSheet` to display the context menu
- [ ] add any missing method to `Node` and corresponding unit test

**Comment by nikonoel** [comment]
I suggest adding "delete this move" as an option. It allows the user to delete the end of the variation instead of deleting everything. Very useful in my experience.

**Comment by veloce** [comment]
A "delete from here" I think: if you're on the last move it deletes one move, or it can delete several moves.

**Comment by nikonoel** [comment]
Agreed on the wording
