### ISSUE TITLE
Improve mouse support (on iPadOS)

### ISSUE THREAD

**Issue by tedzards509** [lichess-org/mobile#343]
From [the discord](https://discord.com/channels/280713822073913354/1063362438491291708/1163246102120763502):
The mouse control on iPadOS is a little off. The piece and the control for where it goes are offset (the control is significantly underneath) from the way it works on the desktop. Also, the piece is zoomed significantly making it hard to see the destination. Here's a screen shot showing the control point and the zoomed piece (actually, I can't post images apparently). The piece looks like it will block check but the square below it is actually chosen as the destination. In this case, it would be an illegal move, but, otherwise, there is a high likelihood of dropping the piece in the wrong place. Could the control be centred on the piece and the piece zoom be lessened?

**Comment by veloce** [comment]
Since we have a desktop site it was never intended to add mouse support to this app.

This is very low priority.

**Comment by HaonRekcef** [comment]
This can be closed. The magnifying setting can be deactivated at Settings->Board->Magnify dragged piece.
With it being deactivated it behaves as expected
