### ISSUE TITLE
TV: White king incorrectly marked as in check

### ISSUE THREAD

**Issue by trevorbayless** [lichess-org/mobile#348]
Watching any TV channel, when white delivers a check the white king is being marked as in check instead of the black king.

![image](https://github.com/lichess-org/mobile/assets/3620552/54157ae4-17f8-4eb0-9dc6-ab1ceb19cd99)

**Comment by nav-28** [comment]
Thanks for the report. Flutter chessground uses `sideToMove` to select the king square and looks like its not being set in the  tv screen
