### ISSUE TITLE
Add support for interactive lessons for studies.

### ISSUE THREAD

**Issue by PixelPerfectJenna** [lichess-org/mobile#35]
It would be very helpful if the mobile app had the ability to do interactive lessons. It would be useful for people on the go or just testing their knowledge when they have a few moments to spare.

**Comment by vetricodes** [comment]
I would like for this feature to be added too!

**Comment by tom-anders** [comment]
@veloce and this one can be closed as well. If we had managers, they would be really happy right now :D
