### ISSUE TITLE
Buisness of itlichess , make good money out of it

### ISSUE THREAD

**Issue by AnshuMishra01** [lichess-org/mobile#351]
Hi I am Anshu Mishra, Currently running 2 startups in India and they are profitable, I am quite interested in doing one with you on itlichess Application. We can reach a good number of people if you take my business advices, I am ready to be your partner, You handle the tech and I the business, but first we need to talk so here's one of my Linkedin profile [Link](https://www.linkedin.com/in/anshu-mishra023129/) or you can mail me at - [anshum.ug21.ee@nitp.ac.in](mailto:anshum.ug21.ee@nitp.ac.in)

**Comment by nav-28** [comment]
Hello, please use the GitHub issues only for Lichess mobile related problems.
