### ISSUE TITLE
Feature request: share/export GIF from the app

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#359]
I'm not sure how this could be implemented but I'm sure a lot of people would like it. It's obvious how game gifs are a great, super easy, fast and straightforward way to share a game.

If not export, maybe a one-click way to copy the link of the game gif to the clipboard would be enough as these gifs are almost exclusively used to quickly post the game somewhere online.

**Comment by vaibhavsection** [comment]
Please make option share pgn to other app
