### ISSUE TITLE
Draw board shapes with 2 fingers

### ISSUE THREAD

**Issue by ducketyduck** [lichess-org/mobile#363]
Some people have suggested adding a feature to draw lines by long pressing a square, but I think that could create conflicts with the piece drag and drop since you could be just trying to drag a piece, so instead I suggest adding a button, that allows to draw lines WHILE it is PRESSED. So the idea is that you use 2 fingers to draw, one finger is pressing the button and the other is actually drawing, so that if you wanted to stop drawing to quickly play a move you could just release the button and make the move

**Comment by veloce** [comment]
That could work indeed. 

Better than a button imo would be only using board. While one finger is touching board (not on a piece) the other finger draws. 
It would not conflict with moves since dragging is disabled when 2 simultaneous touches are detected.

**Comment by ducketyduck** [comment]
Yeah, this could also work and I guess it's better visually to not have a button, although having to keep a finger on the board could make drawing with the other finger a bit more difficult, but I guess you could just move the first finger away from the board without having the "drawing mode" turned off. One criticism I could think of is that if for some reason someone were to make a custom game where all the squares have pieces it could not be possible to draw lines, although this is such a rare case scenario that I still think this idea could be viable.

**Comment by vaibhavsection** [comment]
Please try to implement this feature asap

**Comment by HaonRekcef** [comment]
closed by #833
