### ISSUE TITLE
To revert the change which replaces "Lichess" with username

### ISSUE THREAD

**Issue by TheAlphaApp** [lichess-org/mobile#365]
[Here](https://github.com/lichess-org/mobile/commit/5bb5c05346298e5111aaa387f9ffe9939741f56a#commitcomment-132300260) is the comment which explains this issue.

**Comment by veloce** [comment]
I don't care about brand placement. Could you elaborate why you think a majority of users wouldn't like the username at the top? (which was there on the old profile tab).
