### ISSUE TITLE
Puzzle Dashboard UX issue

### ISSUE THREAD

**Issue by TheAlphaApp** [lichess-org/mobile#372]
It took me a significant amount of time to realize what this "days button" does at the top.
I think it should be placed next to "Puzzle Dashboard" text.

![Screenshot_2023-11-21-18-37-51-61_cbee2060dbe813f67358565f077e6954](https://github.com/lichess-org/mobile/assets/38341694/631d262f-4c89-4b73-9497-eabcb7011a1e)

![IMG_20231121_184349](https://github.com/lichess-org/mobile/assets/38341694/b66fc730-6433-4992-a7df-84ed7628c09a)

**Comment by veloce** [comment]
I know this is an issue right now.

Thing is, in some languages, like French, title can be long: "Tableau de bord des problèmes". So there is a space issue. I could force a short title, but I'd like to solve it differently.

I made a change so the puzzle screen looks like this
<img width="414" alt="Capture d’écran 2023-11-22 à 10 02 05" src="https://github.com/lichess-org/mobile/assets/423393/bd1d104a-19dd-4edd-bf25-571da9565f66">

I will be more obvious like this that the days are changing the dashboard.

Another reason I'd like to leave days at the top is for the coming (no eta) replay feature and improvement areas that will need the days selector too.

**Comment by TheAlphaApp** [comment]
It is better now. Thank you.
