### ISSUE TITLE
Misplaced pieces

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#375]
From discord report: 

![Screenshot_20231126-120818](https://github.com/lichess-org/mobile/assets/423393/17a4ade7-2466-4f49-8dea-5b0baf8c6577)

This happens on a kindle fire. I cannot reproduce so far on any tablet emulator that I tested.

**Comment by anongithubuser12345** [comment]
Can reproduce. App v0.6.13. Amazon fire max 11 (13th generation). Side-loaded Google Play Services/Store. Only in landscape mode. Choose any game from the "recent games" list. Let me know if you need me to perform additional checks etc.

**Comment by veloce** [comment]
Bug also found on a xiaomi tablet: https://m.gsmarena.com/xiaomi_pad_5-11042.php

**Comment by veloce** [comment]
Thanks for the tip @anongithubuser12345 now I can reproduce on an emulator by changing the display size.
