### ISSUE TITLE
Arrow Buttons Rework

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#392]
I really appreciate the design of the Mobile V2 app, but something that slightly bothers me is the placement and size of the Arrow Buttons to move around in a chess game.
For my hands, even on a 6.4 inch screen, I feel like I keep missing the arrow buttons when navigating my games. I'm pretty sure this is due to the small size of the hit area for the arrow buttons.
I would appreciate a larger hit area for the navigation keys, to avoid missing the buttons, even when it looks as if you are clicking on them.

 https://github.com/lichess-org/mobile/assets/108140722/1b75be39-9420-468f-8089-a30a8bc3fb4f

In the video you can see the small size of the clickable area for the arrow buttons.

There also seems to be inconsistencies in the spacing between the arrows, as seen in the game analysis screen and the game itself, the latter shown below.

![Screenshot_20231214-201935.png](https://github.com/lichess-org/mobile/assets/108140722/57898cf7-cae2-4aa6-accf-c2b647530bca)

I appreciate all the hard work everyone is putting in to make this app happen!

**Comment by veloce** [comment]
Yes I know this is a problem. Size of the icons doesn't represent the hit area, and normally I tried to keep flutter defaults in that regard. But I must have done something wrong here.
