### ISSUE TITLE
Correspondence move notifications

### ISSUE THREAD

**Issue by InaTaffe** [lichess-org/mobile#393]
What an amazing app! 

I was eagerly waiting for the addition of correspondence chess since that is my favorite time control to play at the moment. This made me delete the lichess PWA and chess.com since I have now everything I need in this new app. 

The only issue that that came up was that I don't get a notification when the opponent makes a move. This issue made me download chess.com again, but when fixed, I am fully on this app. Appreciate everything and am eagerly waiting again

**Comment by veloce** [comment]
Done https://github.com/lichess-org/mobile/commit/2b65b35e0193b44f0f513d3fcee11ac0ccdaf359
