### ISSUE TITLE
Feat - Black and White King Icon in Puzzles

### ISSUE THREAD

**Issue by TheHypnotist333** [lichess-org/mobile#398]
This is minor but when in the flow of a puzzle solving session I found it helpful that the king icon shows who's turn it is in the puzzles.  I always quickly glance at the king's icon instead of reading the "find the best move for black". Also it looks better aesthetically that the king icon was of the same piece set that is on the board instead of a grey king that looks different from the kings on the board.
![Screenshot_20231218-152609](https://github.com/lichess-org/mobile/assets/104811236/96dd52b1-d287-4e2a-9675-90dac48e1932)
![Screenshot_20231218-152643](https://github.com/lichess-org/mobile/assets/104811236/7c19f602-1977-485f-8b2b-99f87c6d0219)

**Comment by veloce** [comment]
Yes. The problem is that some piece sets are hard too distinguish from the background.
