### ISSUE TITLE
Draw offer not received in Correspondence Chess

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#401]
When playing a Correspondence Chess Game, my opponent offered me a draw, which was not received through the new app.

![Screenshot_20231219-182603.png](https://github.com/lichess-org/mobile/assets/108140722/fc84be34-8122-4abb-a10b-012417cb967d)

![Screenshot_20231219-182619.png](https://github.com/lichess-org/mobile/assets/108140722/924302f3-3c80-4b22-954e-390db0abdf5b)

Above: The new mobile app Correspondence Game and the Context Menu, not showing a draw offer.

![Screenshot_20231219-182808.png](https://github.com/lichess-org/mobile/assets/108140722/a704c657-5a96-4ff7-b7b9-263e027ef331)

Above: The older app showing a draw offered. This also appears on the mobile / desktop website.

From what I've tested, the New Lichess App (V2) only receives the draw offer when actively in the correspondence game, and even then if you exit out and enter back in it disappears.

When you try to offer a draw from the V2 app even when it doesn't show that your opponent has previously offered a draw, it simply kicks you out of the game, not accepting the draw offer from the opponent.

Here's a final video showing the bug:
https://github.com/lichess-org/mobile/assets/108140722/cd1374b7-7c91-464e-9015-e84cf842a55b

**Comment by veloce** [comment]
This is a server side issue: https://github.com/lichess-org/lila/issues/14258

**Comment by veloce** [comment]
Closing as the server issue is closed.
