### ISSUE TITLE
Improve TV with variants

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#41]
![TV screen](https://user-images.githubusercontent.com/423393/216275881-e80522b9-12bb-4196-9df0-fd74312730c5.png)

For this you have the lichess API: 

- https://lichess.org/api#tag/TV/operation/tvChannels
- https://lichess.org/api#tag/Games/operation/streamGame

It should replace the existing stream that only shows the main TV.

It should filter out unsupported variants (crazy house, racing kings, horde).

TV channel selector at the top should use a widget adapted to the platform, that can be something similar to what is implemented here:

https://github.com/flutter/samples/blob/main/platform_design/lib/widgets.dart#L289

**Comment by nav-28** [comment]
Had a question about the API's. The tv channels API only has the username of one player and the game stream also doesn't have the username of the opponent. 

And the game stream is 3 moves behind would that be acceptable?

**Comment by ryg-git** [comment]
I would like to work on this issue if it is still open
