### ISSUE TITLE
After logging in and authorizing, personal information cannot be obtained

### ISSUE THREAD

**Issue by BodenTide** [lichess-org/mobile#411]
flutter version: 3.16.5

I can get the token after logging in and authorizing it, but after requesting https://lichess.org/api/account, I can't get the token. It prompts me that I don't have a token. I need help!

It gives the following error！
![1703666827253](https://github.com/lichess-org/mobile/assets/137751112/d0ac4ba2-5e5b-4ac9-b019-7762cf531368)

the problem code is below
![1703666879736](https://github.com/lichess-org/mobile/assets/137751112/39b1adc9-688f-4a85-935f-cee892777cb2)

**Comment by veloce** [comment]
It doesn't look like an issue or an app bug but a request for help. You should go to discord instead: https://discord.gg/lichess

I have no clue why it's going wrong in your case given the info needed, sorry, but I'm closing for the reason mentioned above.
