### ISSUE TITLE
Suggestion: Add ELO rating in the analysis

### ISSUE THREAD

**Issue by COD3BREAK3R** [lichess-org/mobile#413]
I would like Lichess to display the approximate ELO scores with which both players performed when showing the analysis results, and how well they played in the opening, middlegame, and endgame. It would be beneficial to show the ELO level for each of these phases, similar to what chess.com does but improved

**Comment by EmmetSchuler** [comment]
It's difficult to judge elo (or glicko, in this case) accurately based on one game. I think Lichess's current system of centipawn loss and accuracy are more important metrics to focus on.

**Comment by COD3BREAK3R** [comment]
> It's difficult to judge elo (or glicko, in this case) accurately based on one game. I think Lichess's current system of centipawn loss and accuracy are more important metrics to focus on.

It doesn't need to be precise, just an approximation based on the game to know at what level each of the players played

**Comment by veloce** [comment]
This is not a request specific to the mobile app, so it does not belong here but rather in https://github.com/lichess-org/lila, so I'm closing it.
Feel free to create an issue in Lila repo, but for the reason mentioned by EmmetSchuler I don't think it is within the scope of lichess to do this.
