### ISSUE TITLE
Suggestion: Update the stockfish version of the app to version 16

### ISSUE THREAD

**Issue by COD3BREAK3R** [lichess-org/mobile#414]
I would like the mobile app to consistently match the website's features and always include the latest version used by the website. It doesn't make sense for the website to have more features than the app; both the website and the app should be synchronized in terms of functionality

**Comment by EmmetSchuler** [comment]
Are you referring to the older app? In the new app, Stockfish 16 appears in the analysis screen. The old Lichess app is out of development, and these issues are for the new Lichess app currently being built.

**Comment by nav-28** [comment]
The new app already uses stockfish 16. You can tap engine depth icon in the analysis screen to see the stockfish version popup.

**Comment by COD3BREAK3R** [comment]
> Are you referring to the older app? In the new app, Stockfish 16 appears in the analysis screen. The old Lichess app is out of development, and these issues are for the new Lichess app currently being built.

Hi, I don't know what is new app, I'm using the app of lichess that's available on Play Store

**Comment by nav-28** [comment]
This repo is for the new app in development which is currently in beta. So it is not released on the play store. 

Here is the repo for the old app. https://github.com/lichess-org/lichobile
