### ISSUE TITLE
Suggestion: Show how good the move played is

### ISSUE THREAD

**Issue by COD3BREAK3R** [lichess-org/mobile#417]
Lichess could implement a feature that shows if the move played is the best according to the engine. This could be indicated with a green circle and a star icon for the best move, a like icon for the second-best move, and a check icon for the third-best move, all in the same color as the best move

I know it's difficult to determine if a move is excellent or brilliant, but one way to do it could be the following:

An excellent move would be the only good move in the position when there are no other good moves, highlighted in a dark blue shade with an exclamation mark icon.

A brilliant move would involve sacrificing a higher-value piece for a lesser one, whether by capturing, moving, or allowing it to be captured. It should be the best move in the position with a positive engine evaluation, marked with a bright blue circle and a double exclamation mark.

I hope these features are implemented in the future

**Comment by nav-28** [comment]
This feature is outside the scope of the app and needs to be implemented for the website first. This has already been discussed before (see https://github.com/lichess-org/lila/discussions/8987#discussioncomment-767931). 

There is not good way to automatically detect a "brilliant move" and it is pretty subjective. Closing this for the above reason.

**Comment by COD3BREAK3R** [comment]
> This feature is outside the scope of the app and needs to be implemented for the website first. This has already been discussed before (see [lichess-org/lila#8987 (comment)](https://github.com/lichess-org/lila/discussions/8987#discussioncomment-767931)).
> 
> There is not good way to automatically detect a "brilliant move" and it is pretty subjective. Closing this for the above reason.

Hi, I understand your point, but at least the first part of the suggestion can be implemented and is perfectly easy to apply based on the data provided by the module, an excellent move would be when the engine only gives 1 move as good which is also perfectly measurable. The brilliant movement is more complicated and I understand that it may be difficult for them to implement it, but based on the idea I gave, although it may not be 100% accurate, I think it can be a good start
