### ISSUE TITLE
Remove kTabletThreshold constant

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#426]
Remove the constant defined here: https://github.com/lichess-org/mobile/blob/main/lib/src/constants.dart#L36

And use `FormFactor` as defined here instead: https://github.com/lichess-org/mobile/blob/main/lib/src/utils/layout.dart, or `getScreenType`, depending on the use case.

**Comment by BAW2501** [comment]
seems easy enough could i get this assigned to me ?

**Comment by veloce** [comment]
Feel free to open a PR anytime yes :)
