### ISSUE TITLE
Live Streamers platform icons UI support

### ISSUE THREAD

**Issue by jalpp** [lichess-org/mobile#43]
the Live streamers UI page in #42 should also be able to support the streamers' streaming platform icon below/above "English"

Free Twitch Icon:
https://www.flaticon.com/free-icon/twitch_4494567?term=twitch&page=1&position=9&origin=tag&related_id=4494567

Free YouTube Icon:
https://www.flaticon.com/free-icon/youtube_3670147?term=youtube&page=1&position=1&origin=search&related_id=3670147

Should be able to get the streamers' platform under "service" in https://lichess.org/api#tag/Users/operation/streamerLive

Thanks.

**Comment by veloce** [comment]
See my comment on the original issue. Closing it then.
