### ISSUE TITLE
Add a privacy settings section in profile preferences screen

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#433]
Add the same section as the website one: https://lichess.org/account/preferences/privacy

All items should not be done at once, but depending on the availability of the feature. For instance, once #432 is done, we should add here the items related to challenges. Same for PM, study, etc.

So only this item should be displayed first:

- [ ] let other player follow you

**Comment by HaonRekcef** [comment]
This can be closed, was merged in https://github.com/lichess-org/mobile/commit/34a3a7418acd0a646d1b3306d3b16b907cd5a62a
