### ISSUE TITLE
New Opponent Button Failing

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#441]
### What is the problem?

After a game finishes, both the new opponent button in the game result menu and the Context Menu fail to requeue a game. Instead, it simply exits you out of the menu.

### Steps to reproduce the bug

Play a 3+0 match against someone
Either win or lose
When the game ends, press the new opponent button (either in the game result menu or in the context menu)

### What did you expect to happen?

The app should begin to search for a new game of your given time control.

### What happened instead?

The app exits you out of the menu, without initiating the pairing process.
Here's an example of using the context menu after a game to find a new opponent and failing.

https://github.com/lichess-org/mobile/assets/108140722/4154bcec-4f81-4648-ae10-36f44182ebe8

The same issue occurs if using the game result menu, which in the video I exit out of intentionally to show the context menu.

### Device Info

Pixel 6

### Operating System Version

Android 14

### Additional information

The bug only appears for me if tried directly after a game. If exiting a game and revisiting the game, the button works as expected.

**Comment by veloce** [comment]
Thanks for reporting!
