### ISSUE TITLE
Add an online bots screen to allow playing against online bots

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#444]
This screen is also on the website: https://lichess.org/player/bots

The endpoint is available at: https://lichess.org/api#tag/Bot/operation/apiBotOnline

This screen should be accessible from the "Create a game" screen, through another button below "Correspondence".

Playing against an online bot is like playing an online game, so this part is already implemented. In order to start the game one should use the challenge API: https://lichess.org/api#tag/Challenges/operation/challengeCreate and directly challenge the bot user.

TODO: describe screen.

**Comment by HaonRekcef** [comment]
closed by #772
