### ISSUE TITLE
Add an option to show captured pieces instead of material imbalance

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#468]

**Comment by VaibhavKukreti-Kathud** [comment]
Can I work on this issue?

**Comment by veloce** [comment]
Yes you can open a PR when you're ready.

**Comment by arjun1194** [comment]
Hey @VaibhavKukreti-Kathud are you working on this ? if not i would like to pick this up :)

**Comment by arjun1194** [comment]
what is the process of developing such features ? is there a PRD or a Proposal ?

**Comment by HaonRekcef** [comment]
No its simlle, just fork the project, code your features, improvements, or bug fixes, and then create a pull request. The maintainer will then take a look at it, provide feedback, and approve it. However, note that the maintainer is currently on vacation, so it might take some time for the PR to be merged.

**Comment by saurabhffs** [comment]
@veloce I am working on this issue

**Comment by sandeep-adireddi** [comment]
Hey @veloce , Where is the best place to add a toggle option for showing or hiding this enhancement?.

**Comment by veloce** [comment]
Well I'm not sure, because there is a conflict with the "Material imbalance" option, which is already a toggle. We can't have both true at the same time.

**Comment by sandeep-adireddi** [comment]
Yeah, I asked this because i noticed this conflict. One option i found is similar to current app .
![Screenshot_20240513-211449](https://github.com/lichess-org/mobile/assets/16081707/0eb8fd01-ea5e-434c-b10a-94618b6a2c2e)

**Comment by HaonRekcef** [comment]
Closed by #1142
