### ISSUE TITLE
Replace `defaultTargetPlatform` with `Theme.of(context).platform`

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#470]
According to the official doc: https://api.flutter.dev/flutter/foundation/defaultTargetPlatform.html

`Theme.of(context).platform` is the preferred choice to get the current platform inside a Widget.

- [ ] Replace all `defaultTargetPlatform` where it is possible in the code
- [ ] make sure the tests are passing

**Comment by gantanikhilraj** [comment]
Hello @veloce , I would like to work on this issue, assign this to me.
