### ISSUE TITLE
Improve navigation in game analysis

### ISSUE THREAD

**Issue by ZTL-UwU** [lichess-org/mobile#471]
One should be able to click on the `AcplChart` to jump to the move.

<img src="https://github.com/lichess-org/mobile/assets/49156174/0114d7c7-8e6b-45eb-9a0f-50a5ab5a5f60" width="400">

**Comment by veloce** [comment]
Useful documentation in fl_chart library: https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/handle_touches.md
