### ISSUE TITLE
offering draw in a correspondence game does not work

### ISSUE THREAD

**Issue by HaonRekcef** [lichess-org/mobile#472]
### What is the problem?

offering draw in a correspondence game does not work as it closes the game and the draw offer is not send

### Steps to reproduce the bug

1. play a corr game
2. try to offer a draw

### What did you expect to happen?

I expected that a draw offer is sent and game remains open

### What happened instead?

No draw offer is sent and the game is closed

### Device Info

Pixel 6a

### Operating System Version

Android 14

### Additional information

https://github.com/lichess-org/mobile/assets/78898963/e1e44bd0-66d2-4c57-9217-694de42f2bc9

**Comment by veloce** [comment]
Thanks for reporting it.
