### ISSUE TITLE
Share button not working on iPad Pro 2017 

### ISSUE THREAD

**Issue by HaonRekcef** [lichess-org/mobile#474]
### What is the problem?

Share button not working on iPad Pro 2017. There is nothing that appears when pressing share pgn on iPad Pro 2017

### Steps to reproduce the bug

1. go to Analysis Screen or solve a puzzle
2. click share pgn or share

### What did you expect to happen?

a pop up comes up like on android with the options where to share

### What happened instead?

nothing happens, no pop up or error message

### Device Info

iPad Pro 2017

### Operating System Version

iPadOS 17.2

**Comment by veloce** [comment]
Probable crash report associated:

```
PlatformException(error, sharePositionOrigin: argument must be set, {{0, 0}, {0, 0}} must be non-zero and within coordinate space of source view: {{0, 0}, {834, 1112}}, null, null)
```
