### ISSUE TITLE
Add color coding to analysis moves/text

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#479]
Everywhere on Lichess (and in other chess websites/software too) the text of the evaluated moves are color coded, just like the NAG icons. 

This helps finding the key moments of the game a lot. I mean, having the analysis text in a separate line is great and I love that the current change in the eval number is shown, but I'm sure a lot of people are used to having this very useful feature.

In my opinion even the eval text (for example "Blunder. ... was best") could be colored as well, making the important information even more visible and easier to notice.

Just in case I'll attach a screenshot from old Lichobile. Thanks again as always!

![Screenshot_2024-01-16-16-10-37-990_org.lichess.mobileapp-edit.jpg](https://github.com/lichess-org/mobile/assets/118524250/0d98eb0d-993a-4401-9008-4c5cf92aca3d)

**Comment by veloce** [comment]
Yes it is planned.
