### ISSUE TITLE
add Broadcast feature

### ISSUE THREAD

**Issue by PuzzlingDecision** [lichess-org/mobile#480]
Add a broadcast feature

IMO this is very important feature, as soon there will be no comfortable app to follow live tournaments. I hope this implemented soon.

**Comment by dedekind125** [comment]
This feature needs to be prioritized in my opinion. 

With chess24 removing their services there is not a good app to follow over the board tournaments with a mobile device. Lichess can fill this gap before competition arrives!

**Comment by HaonRekcef** [comment]
Can be closed aswell)
