### ISSUE TITLE
names in analysis screen not on same height

### ISSUE THREAD

**Issue by HaonRekcef** [lichess-org/mobile#484]
### What is the problem?

![Screenshot_20240117-220349](https://github.com/lichess-org/mobile/assets/78898963/7048fc0f-6b92-4a76-b7f0-55ffe87c1441)
The name of Penguinggm seems to be lower than the one of his opponent

### Steps to reproduce the bug

1.Search a game between players with a long name and a short name
2. Go to analysis screen

### What did you expect to happen?

The names or the points should be on the same height.

### What happened instead?

One name is lower.

### Device Info

Pixel 6a

### Operating System Version

Android 14

### Additional information

@ZTL-UwU

**Comment by ZTL-UwU** [comment]
Thanks for your report! By design the bottom of the names should be aligned rather than the points.
As for why the bottom of the names are not aligned, my assumption is that the text wrap is messing up the line height. I'll try to fix it later.

**Comment by HaonRekcef** [comment]
Thanks for fixing! Any reason why you removed the info button about the accuracy in your last update?
