### ISSUE TITLE
Social Media link's not showing properly.

### ISSUE THREAD

**Issue by 0xNaimulHasanTaky** [lichess-org/mobile#502]
### What is the problem?

Not all the social media link's are visible. and one is shown incorrectly. Marked on the picture with # 1
![IMG_20240126_122259](https://github.com/lichess-org/mobile/assets/147870580/14847776-fc88-4362-b9be-533489916baa)

While editing social media link's keyboard doesn't have button to add new lines for adding new social media link's. Marked on the picture with # 2
![IMG_20240126_124747](https://github.com/lichess-org/mobile/assets/147870580/0c5dd64e-1f87-4d1b-9635-7e560c0989b1)

### Steps to reproduce the bug

1. Go to profile
2. Click edit icon

### What did you expect to happen?

All social media link's should be shown properly.
![IMG_20240126_124110](https://github.com/lichess-org/mobile/assets/147870580/2ca2a311-ef20-4e38-beba-5fe68f6de1f5)
While editing social media link's keyboard should have button to add new lines for adding new social media link's.
![IMG_20240126_124607](https://github.com/lichess-org/mobile/assets/147870580/8cae4336-5445-4124-8883-096e9c9588d2)

### What happened instead?

Not all the social media link's are visible. and one is shown incorrectly 
![IMG_20240126_124047](https://github.com/lichess-org/mobile/assets/147870580/96b16e61-45bb-4d33-9f73-8be202c4ed72)
While editing social media link's keyboard doesn't have button to add new lines for adding new social media link's.
![IMG_20240126_124725](https://github.com/lichess-org/mobile/assets/147870580/55eab9da-3c94-4a65-a65c-3efaad59b078)

### Device Info

Realme C20A

### Operating System Version

Android 10

**Comment by ZTL-UwU** [comment]
The links can actually scroll horizontally.

**Comment by 0xNaimulHasanTaky** [comment]
Ohh i didn't notice it but there's still a problem. It should show chess.com, Facebook instead of the full url
