### ISSUE TITLE
Possible Timing issue

### ISSUE THREAD

**Issue by jjcampos** [lichess-org/mobile#506]
Hi there,

I'm on IOS, latest version 17.2.1
iPhone 12 max
Lichess App v8.0.0

I'm usually playing from home with an internet connection of 1Gb and it usually are around 500Mb on my phone.
I mostly play Bullet 1 minute rated.

From the last few days I've noticed in my games that my opponents are having an advantage on time. I'm not sure whether this is just me taking more time or a bug on the app. The most recent case for me was this one:
https://lichess.org/j2xAYY6L/white#60

As you can see black time only started to count after the 10th move on.

**Comment by HaonRekcef** [comment]
This is intended behavior, your opponent is doing a premove, meaning he determines his move before he has even seen your move. For more information take a look here: [wikipedia premove](https://en.m.wikipedia.org/wiki/Premove#:~:text=In%20online%20chess%2C%20a%20premove,and%20then%20clicking%20its%20destination.)

You can enable this setting for yourself too in settings--> game behavior--> enable premoves

**Comment by veloce** [comment]
Indeed.
