### ISSUE TITLE
Sound theme picker

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#51]
Add a new settings section to choose a sound theme (or silent).

Available sounds are listed here: https://github.com/lichess-org/lila/blob/master/modules/pref/src/main/SoundSet.scala

And the assets are here: https://github.com/lichess-org/lila/tree/master/public/sound

**Comment by Kirito-Excalibur** [comment]
Can you please assign me this?

**Comment by veloce** [comment]
done!

**Comment by youngunand** [comment]
Could you assign me?
 I suppose this issue is still open.

**Comment by brandonpl8** [comment]
Should the sound theme setting belong the boardPreferences or generalPreferences? An argument can be made for both depending on how the sound is used in the rest of the app.

**Comment by veloce** [comment]
Closed by #152
