### ISSUE TITLE
Disable Chat Send Button while Signed Out

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#520]
Lichess disables chat for anonymous players on Lichoble and its website.
Currently in Mobile V2, a signed out player can access the chat and type during a game, although no messages are sent through.
I feel that the chat button should either be disabled during anonymous play, or display a message that it is disabled, in order to avoid confusion.

**Comment by HaonRekcef** [comment]
There are still some messages (draw offers, takebacks and time additions) that get sent in the chat. Not sure how important these are though.

**Comment by veloce** [comment]
We should not disable the chat but the send button then.
