### ISSUE TITLE
Undefined name 'FontFeature'

### ISSUE THREAD

**Issue by okmsbun** [lichess-org/mobile#536]
Hello, I am trying to run the application for the first time. I did all the requirements. I have only one problem; Why wasn't 'dart:ui' imported for "FontFeature.tabularFigures"? Is there something I missed? I get the error "Undefined name 'FontFeature'". When I manually import 'dart:ui' to all pages, I can run the application without any problems. But do I need to do this every time I pull?

**Comment by veloce** [comment]
Hi, sorry I don't really understand why you have this problem but it's probably due to a wrong setup on your side.
I'm closing this because such technical help demands don't belong to issues. You can ask for help in discord instead if you still have trouble. Thanks.
