### ISSUE TITLE
Move Blindfold setting to Board Menu

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#540]
The Lichess website recently underwent changes to the blindfold mode, putting the Blindfold toggle in the board menu instead of deep within the settings pages. This makes it more convenient for users to toggle between modes. I suggest that the blindfold toggle should also be moved in the mobile V2 app, possibly to the settings menu available to those playing a game, next to the sound toggle, haptic piece animation toggle, etc.
![Screenshot_20240207-203951.png](https://github.com/lichess-org/mobile/assets/108140722/e558b319-cf63-4f3c-876b-3236512e4090)

In the future I assume other settings will be moved here as well, such as voice and keyboard input.

**Comment by veloce** [comment]
We can put it here yes.
