### ISSUE TITLE
New game opponent elo range

### ISSUE THREAD

**Issue by nk-alex** [lichess-org/mobile#541]
Hi, first of all, congratulations for this amazing platform to anyone who has contributed to make it what is today. For years now lichess has become my only chess tool.

My question is about creating a new game. Right now, you can select the opponent elo range between (-500 -> 0) for the inferior range, and (0 -> 500) for the superior range . I'm wondering if there are any plans of modifying that inferior range so you can also select positive values. If I'm not mistaken, years ago (on lichess.org at least) I could create an elo range inbetween (+100 -> +500). 

This was really helpful since with that configuration, no matter what, I was playing against stronger opponents. That made me improve a lot my chess.

**Comment by veloce** [comment]
I understand your request. But such decision cannot be taken from a mobile only perspective. It is global to lichess, and thus belong to Lila project.
