### ISSUE TITLE
Annotation symbols displayed on wrong square if castling

### ISSUE THREAD

**Issue by HaonRekcef** [lichess-org/mobile#543]
### What is the problem?

Annotation symbols displayed on wrong square if castling was the last move

### Steps to reproduce the bug

1. Find a game where castling is an inaccuracy, mistake or blunder
2. Go to analysis

### What did you expect to happen?

The shape should be displayed on the square the king moved to

### What happened instead?

The shape was displayed on the square the rook moved from

### Device Info

Pixel 6a

### Operating System Version

Android 14

### Additional information

<details>
<summary>Screenshot</summary>

![Screenshot_20240207-233949](https://github.com/lichess-org/mobile/assets/78898963/cd4c2090-a0af-45f0-8e91-8788866572dd)
</details>

**Comment by okmsbun** [comment]
Yes I tested it and it seems wrong. It's not like Lischess.org. In fact, in different forms of castling, it is sometimes not shown at all. In the video below, when I do the same castling in different ways, 'annotation' is shown (incorrectly) in one and not shown at all in the other.

Here for that 
https://github.com/lichess-org/mobile/blob/3c6d1105b3ec2a2d46efa529eb9f8fb23cf2f0b7/lib/src/view/analysis/analysis_screen.dart#L317

than
https://github.com/lichess-org/mobile/blob/3c6d1105b3ec2a2d46efa529eb9f8fb23cf2f0b7/lib/src/model/common/chess.dart#L42
and checking whether castling is done or not, it seems like it can be solved.


https://github.com/lichess-org/mobile/assets/49310621/58af79d6-92b6-4ccf-afe1-51ad3fd5c468

**Comment by okmsbun** [comment]
When I leave the king to c8, the 'currentNode.nags' list ([]) [here](https://github.com/lichess-org/mobile/blob/3c6d1105b3ec2a2d46efa529eb9f8fb23cf2f0b7/lib/src/view/analysis/analysis_screen.dart#L283) appears empty. This list should not be empty. The list should be the same as the list ([2]) that comes when the king is left on a8.

Game = https://lichess.org/407v1JxQ/black#29
