### ISSUE TITLE
Screen is blinking when playing a game

### ISSUE THREAD

**Issue by PuzzlingDecision** [lichess-org/mobile#544]
### What is the problem?

Screen is blinking sometimes during gameplay

### Steps to reproduce the bug

not sure

### What did you expect to happen?

screen does not blink

### What happened instead?

screen blinks

### Device Info

Redmi 9A

### Operating System Version

Android 11

### Additional information

See here: https://www.youtube.com/watch?v=_xaxesiiHsQ
Time stamps 18s, 27s and 1:04

**Comment by veloce** [comment]
Thanks for the report and the video, this is a known bug: #236 , so I'm closing as duplicate.

Unfortunately I don't know how to fix the bug right now.
