### ISSUE TITLE
a  few visual glitches in Puzzles

### ISSUE THREAD

**Issue by StentMan** [lichess-org/mobile#548]
### What is the problem?

Visual glitches in puzzle solving:
1. Sometimes the rating change following solving a problem isn't displayed, it remains a red x or a green checkmark.
2. The rating change display isn't consistent, it's size (the font size) changes according to the content displayed. Single-digit rating change is more prominent, especially when the rating change is 1 (yes, this actually happened, I don't think I ever saw anything like that when the difficulty is normal).
3. The player's rating is sometimes visible and sometimes not, probably the rating changes overlaps it and hides it.

Some screenshots from a puzzle solving session that demonstrate those issues.

btw, I totally lost a few for the report, I didn't, ahm, make any unintentional mistakes. Kappa.
![signal-2024-02-09-113012_002](https://github.com/lichess-org/mobile/assets/6360751/8281b73c-a39a-4ac4-ab36-000c67119657)

![signal-2024-02-09-113012_003](https://github.com/lichess-org/mobile/assets/6360751/41b0122b-0014-4616-bfb8-65cb4b7df92d)

![signal-2024-02-09-113012_004](https://github.com/lichess-org/mobile/assets/6360751/7137ac58-8312-4beb-b3e8-9619ca8d5caa)

![signal-2024-02-09-113012_005](https://github.com/lichess-org/mobile/assets/6360751/015962ca-a42b-4085-94ed-4659f1c2ad8a)

![signal-2024-02-09-113012_006](https://github.com/lichess-org/mobile/assets/6360751/0866db88-e5df-49bc-9977-966708a407df)

![signal-2024-02-09-113012_007](https://github.com/lichess-org/mobile/assets/6360751/515ac72b-02e7-4a1f-91c5-44e236f9f0de)

### Steps to reproduce the bug

1. Solve some problems.
2. Win some loose some.

### What did you expect to happen?

That I'll be able to report a bug

### What happened instead?

I was forced to fill these two fields that, normally, I understand, are important to verbalize what's going on, only in this case it's redundant but I still need to write something up in order to press the submit button

### Device Info

Poco X5 Pro 5G

### Operating System Version

Android 13

**Comment by veloce** [comment]
I've fixed the font size inconsistencies.

For the rest I'm closing this issue because these are not visual glitches but normal behaviour. This is the server that returns the rating. If you already solved the puzzle you don't get one, in that case it would display a check mark or a cross.
