### ISSUE TITLE
Tournament Feature Request

### ISSUE THREAD

**Issue by vaibhavsection** [lichess-org/mobile#551]
Like older app and website please add tournaments screen.
App is now in beta stage, 
So please consider this feature.

**Comment by vaibhavsection** [comment]
![IMG_20240213_134704](https://github.com/lichess-org/mobile/assets/131532744/5089236c-d25c-4d0d-803c-3f2ea5abef15)

**Comment by NameLessGO** [comment]
Duplicated of https://github.com/lichess-org/mobile/issues/535

Please continue Discussion in the link above

**Comment by HaonRekcef** [comment]
duplicate of #535 can be closed
