### ISSUE TITLE
Use consistent icon style

### ISSUE THREAD

**Issue by LSeelig** [lichess-org/mobile#559]
The four icons at the bottom on the screen have an inconsistent styling. They each use different line thicknesses and detail levels. Please consider using more consistent and modern icons, especially for puzzles and tools.
![Screenshot_20240217_110216.png](https://github.com/lichess-org/mobile/assets/37001137/41c45613-82a1-4d77-8af8-72ae415d6c41)

**Comment by veloce** [comment]
You're totally right about the tools icon. 

I don't really want to change the puzzles icons though, as it is the one used in lichess website.

**Comment by LSeelig** [comment]
> You're totally right about the tools icon.
> 
> I don't really want to change the puzzles icons though, as it is the one used in lichess website.

It's not egregious, but I do think it's a tad skeuomorphic, and the style of the app already heavily departs from the website. Consistency is important. If you aren't going to switch it with, say, a puzzle piece, consider tweaking the line thickness while keeping the metaphor.
