### ISSUE TITLE
[Android] Option (if not default) For Material You Theme

### ISSUE THREAD

**Issue by LSeelig** [lichess-org/mobile#560]
Please consider adding a theming option to color the app with the user's Material You palette (derived by the OS from the wallpaper color palette). This already seems to be partially implemented, but instead of using system colors, it uses the board colors.

Please either add a toggle in appearance settings or make Material You the default.

Also consider adding a Material You tint to the board theme as an option or default.

Lichess by default:
![Screenshot_20240217_110508.png](https://github.com/lichess-org/mobile/assets/37001137/5fd511c3-9fcd-410c-83fc-9c4e2f2e430d)

Other Material You/3 apps (My color palette):

![Screenshot_20240217_111250_Mastodon.png](https://github.com/lichess-org/mobile/assets/37001137/849c607c-03e0-43d3-9827-12f74562b424)

**Comment by veloce** [comment]
This is indeed possible using this plugin: https://pub.dev/packages/dynamic_color

**Comment by LSeelig** [comment]
> This is indeed possible using this plugin: https://pub.dev/packages/dynamic_color

I do think a slightly tinted board that reflects the material you color palette would be a nice touch, even if it's not the default board, but I get that it's unnecessary.

**Comment by veloce** [comment]
I've started to work on that: https://github.com/lichess-org/mobile/tree/android_system_colors

If you have any competence, help is appreciated to complete that work. I think the board is doable by using the `TonalPalette` directly, which can be obtained from this package.

**Comment by veloce** [comment]
I think this feature is a nice improvement indeed. My only slight concerns are how to handle the settings (because I want to keep the possibility to have the palette of the board).

If we can make a nice tinted board using os default color, I don't mind making it the default.

**Comment by LSeelig** [comment]
> I think this feature is a nice improvement indeed. My only slight concerns are how to handle the settings (because I want to keep the possibility to have the palette of the board).
> 
> If we can make a nice tinted board using os default color, I don't mind making it the default.

The settings should keep it simple. It doesn't need brand/technical terms like "Material You" or "Material 3.0". Simply calling it "dynamic" would do.

This is how another app (Feeder) does app theming:
![Screenshot_20240220_125052_Feeder](https://github.com/lichess-org/mobile/assets/37001137/85ac977c-d3f6-45c2-ac83-4e3196cef313)

As for the board, I'm glad you agree about the default tint. If you do make the tinted board default, just label it "default" in the board menu. If dynamic color is disabled, rename "Blue" to "default".

If that's too confusing or you don't want to make it default, just add a "dynamic" board to Board Theme and remove it from the menu if the user disables dynamic color.

![Screenshot_20240220_125112](https://github.com/lichess-org/mobile/assets/37001137/b2ecbd9c-99ce-49f9-b4b6-b37e6dc5fb4e)

**Comment by veloce** [comment]
You can have a look at the current WIP: https://github.com/lichess-org/mobile/pull/565 (screenshots attached).

Board with system colours is not that obvious (to make it look nice whatever the color seed is).
