### ISSUE TITLE
[enhancement] make the "shapes" pieces less white

### ISSUE THREAD

**Issue by InaTaffe** [lichess-org/mobile#568]
This also concerns the website. 

The white pieces of the "Shapes" set is very white and not good for eyes.

Something like the color of the "Governor" pieces would be perfect if possible.

I love the shapes so it is hard to find a replacement

**Comment by tom-anders** [comment]
Piece sets in the mobile app are kept in sync with the website, so the issue should be raised over at https://github.com/lichess-org/lila

**Comment by veloce** [comment]
And now there is the brightness filter.
