### ISSUE TITLE
Missing Feedback for Forfeiting a Disconnected Game.

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#577]
### What is the problem?

When a user disconnects from the app, after a certain amount of time the opponent can claim either a draw or win. However, for the side that disconnected, no feedback is provided, and they are met with a game that seems to still be in play.
There should be a popup explaining the game was forfeited as either a draw or win, depending on the opponent's choice.
As shown, no information is provided for the side which disconnected:
![Screenshot_20240226-183656](https://github.com/lichess-org/mobile/assets/108140722/dc86c623-68eb-4614-b70d-9052195ec808)
![Screenshot_20240226-183708](https://github.com/lichess-org/mobile/assets/108140722/9feb9000-2231-4984-93d8-151b1185e643)

### Steps to reproduce the bug

Play a (casual) match against a friend
Leave the app, or disconnect from the Internet
Opponent should claim one of the two options of ending the game
Enter back into the app, or turn on internet

### What did you expect to happen?

A popup should show that the game was forfeited through either a draw or loss.

### What happened instead?

No feedback is given to the opponent who disconnected.

### Device Info

Pixel 6

### Operating System Version

Android 14

**Comment by veloce** [comment]
I fixed the issue for the losing connection case.

I don't think you can reproduce the problem by leaving the app in a blitz game, since the socket connection stays alive for 5 minutes when the app is in background.
