### ISSUE TITLE
Total puzzle count incorrect after syncing offline puzzles

### ISSUE THREAD

**Issue by Robmonster** [lichess-org/mobile#578]
### What is the problem?

There seems to be an issue with offline puzzles syncing.

Today I carried out 3 offline puzzles. When I went back online I can see those three puzzles show up in my Profile timeline.

https://i.imgur.com/kKT0JpM.png

However, the stats along the left only show an increase of 1 in puzzle count

https://i.imgur.com/IsY2ypU.png

This previously said 1058. I'd expect it to read 1061

I cannot post this in the Googlegroups since it says I do not have permission to see the Conversations even though I am a group member.
[BaronVonChickenpants](https://lichess.org/@/BaronVonChickenpants)
[1 week ago](https://lichess.org/forum/team-lichess-beta-testers/issue-with-total-puzzle-count-after-syncing-offline-puzzles-android#2)
[#2](https://lichess.org/forum/team-lichess-beta-testers/issue-with-total-puzzle-count-after-syncing-offline-puzzles-android#2)
Repeatable :-

Before syncing

https://i.imgur.com/qgrUMIz.png

After Syncing

https://i.imgur.com/Q8gY3ZM.png

### Steps to reproduce the bug

Check number of compelted puzzles in account.

go offline on your mobile device, Complete a number of puzzles.

Go back online, complete another puzzle.

check total puzzle count in account

### What did you expect to happen?

if i complete 3 puzzles offline I expect my total puzzle count to go up by 3 when it resyncs

### What happened instead?

The total puzzle count only goes up by 1 regardless of how many offline puzzles were completed.

### Device Info

Samsung S10 Android

### Operating System Version

Android 12

**Comment by veloce** [comment]
Thanks for reporting, looks like a server issue, will forward to Lila repo.

**Comment by lxgr** [comment]
Was this already deployed? I'm currently not seeing any of my offline progress synced to my profile once I come back online (tested on iOS).

**Comment by HaonRekcef** [comment]
It is not deployed yet, on: https://lichess.org/source you can see the last boot and the last commit and those are before the bug was fixed. It should be fixed the next time a new version is deployed.

**Comment by Robmonster** [comment]
thank you, I don't know how the commit references work in order to know which comes before which
