### ISSUE TITLE
Incorrect eval bar, engine gets confused when long castling with check

### ISSUE THREAD

**Issue by gnaomo** [lichess-org/mobile#583]
### What is the problem?

It's black turn, When castling queen side with check the engine thinks that is still black turn, it should be white. The eval bar goes crazy, the suggested moves for white are blank, and the arrows for the best moves are displayed for black instead.

Important note, this happens ONLY if you castle "manually" (by dragging or tapping the king), if you instead select long castle on the engine suggested move, the bug will not manifest itself 

https://github.com/lichess-org/mobile/assets/38522864/94de65a6-9e5a-4306-a43a-a50d49d998cd

### Steps to reproduce the bug

Go to analyze.
Have the engine on 
Follow the annotation on this image
![Screenshot_2024-03-07-16-00-50-13_cbee2060dbe813f67358565f077e6954](https://github.com/lichess-org/mobile/assets/38522864/dfa616f2-d24a-43b1-8c59-209431296bb5)
When you long castle the bug will manifest itself 

### What did you expect to happen?

The engine working correctly

### What happened instead?

The engine working wrong. The eval bar goes crazy, the suggested moves for the opponent are blank, and the arrows for the best moves are displayed for the wrong player instead.

### Device Info

Realme 8 5G 

### Operating System Version

Android 11

### Additional information

I did not test other cases such as, short castling with check, other games, white long castling, other phones, other OS, clearing app data, changing account.

**Comment by EmmetSchuler** [comment]
Experienced this as well, just want to add that the wrong evaluation stems from the way in which one castles. If you tap / drag the king onto the room, it evaluates as normal. But if you tap / drag the king two squares, it will bug out.
