### ISSUE TITLE
Make board larger on landscape tablets by moving buttons from under the board

### ISSUE THREAD

**Issue by anongithubuser12345** [lichess-org/mobile#585]
Compared to the regular lichess app the new one uses the screen size less efficiently. The menu/navigation buttons could be moved to the right of the board, as before.

Regular app:
![old](https://github.com/lichess-org/mobile/assets/162747966/ad9a5082-282b-4345-a808-745a33977e5c)

New app:
![new](https://github.com/lichess-org/mobile/assets/162747966/323fa430-7024-4f24-a6c8-ef1c3c97d805)

Maybe do all you can generally to maximise the size of the board. Even if you can't/won't use the full screen mode you often see watching movies there is space above the board on both apps which could be used.

**Comment by casbarof** [comment]
Also:
* Move list should use more vertical space
* Draw/resign buttons shouldn’t be hidden in the menu. Players should be encouraged to resign instead of letting their time run out, which has sadly become the norm.

**Comment by veloce** [comment]
If people let time run out instead of resigning, I don't think that is because they don't find the button.

**Comment by casbarof** [comment]
Depends on the person. In any case, lichess should make doing the right thing easy.

**Comment by anongithubuser12345** [comment]
Note that I cannot check for changes to this issue because another bug means that it is now impossible to download the Lichess beta app from the app store:
https://github.com/lichess-org/mobile/issues/875
I'm going to guess this is a problem with the manifest or config provided to Google and is not a result of the app using functionality not provided on the target device.
