### ISSUE TITLE
Computer analysis chart game phase is broken

### ISSUE THREAD

**Issue by Mansour-J** [lichess-org/mobile#589]
### What is the problem?

When you have a game where it is focused only one phase of the game("openning", "middle game" or "endgame") the chart cannot understand that the analysis is only for one of the phases.

![image](https://github.com/lichess-org/mobile/assets/12991664/4bf70fab-c4f1-41a9-8170-16eaffe5c1b8)

### Steps to reproduce the bug

e.g if you set up a two bishop and a king to practice mating with two bishop, once the game finished if you request computer analysis the "game phase" is ONLY going to be endgame because you practiced endgame. 

But the chart does not remove middle game and openning label. It shows them on top of endgame which results in an unreadable text.

### What did you expect to happen?

The computer analysis chart in this example should show only "Endgame" text in the chart.

### What happened instead?

![image](https://github.com/lichess-org/mobile/assets/12991664/ad048d2e-8d0c-4589-acd5-b0f82bef4bb5)

### Device Info

Android

### Operating System Version

Doesn't matter

**Comment by julien4215** [comment]
I am not able to reproduce this bug.

Could you give a link to the game or explain or how did you set up an endgame position ?

**Comment by julien4215** [comment]
Not needed anymore. I was able to reproduce and fix the issue.
