### ISSUE TITLE
Missing thumbs up icon

### ISSUE THREAD

**Issue by ZTL-UwU** [lichess-org/mobile#59]
I'm currently working on the user activity feed #24 .
When trying to make the gained x follower entry, I can't find the thumbs up icon in `common/lichess_icons.dart`. 

![Screenshot 2023-02-25 at 12-18-35 GM TSMFTXH (3165)](https://user-images.githubusercontent.com/49156174/221336219-36e3de1d-7cb6-49d6-a3c9-07af7a15b975.png)

**Comment by veloce** [comment]
You have one included in flutter: `Icons.thumb_up`.

**Comment by ZTL-UwU** [comment]
ok, thanks!
