### ISSUE TITLE
UI and Engine Desync

### ISSUE THREAD

**Issue by riccardocescon** [lichess-org/mobile#590]
### What is the problem?

I have experimented this bug while playing puzzle, but i am confident that It would appear in any mode.
I have dragged a look into a position, but the miss-released and release the finger while moving the rook to a different Cell (still valido for the rook move) and graphically It took the last Cell, but logically It took the First Cell, so there Is a non-sync between UI and game

### Steps to reproduce the bug

Click on a piece
Drag a piece to the desired Square (logically)
While releaseing the finger, move the piece to another legale Cell
Done

### What did you expect to happen?

I expected to take the last Cell, where It Is release even if i did It by my mistake

### What happened instead?

Desync between UI and engine

### Device Info

Pixel 6

### Operating System Version

Android 14

**Comment by veloce** [comment]
Thank you for this report but I don't understand what is going on here. 

Please share a video to show the problem you're describing, that will help I think.

**Comment by riccardocescon** [comment]
I tried again but couldn't be able to reproduce the issue, i think we may close the issue then?

**Comment by veloce** [comment]
Alright, if you find a way to reproduce, please reopen and post a video. Thanks!

**Comment by riccardocescon** [comment]
https://github.com/lichess-org/mobile/assets/36532502/a0d8d202-0663-42d5-941b-891cfae72578

Hi @veloce, today i was able to reproduce the issue. I Found out that It does not matter if i drag at the very last second, but seems It randomly moves the piece (rook again in this case) in the wrong Cell. I tried ever single Cell near to the bugged One, but all those works. Just the One on the video has this issue

**Comment by riccardocescon** [comment]
This happens on the game analysis. If It helps here Is the game i Found the bug on the video:
[Event "Rated Rapid game"]
[Site "https://lichess.org/GuO7B97m"]
[Date "2024.03.14"]
[White "RiccardoCescon"]
[Black "lorvan"]
[Result "1-0"]
[WhiteElo "1516"]
[BlackElo "1613"]
[WhiteRatingDiff "+13"]
[BlackRatingDiff "-7"]
[Variant "Standard"]
[TimeControl "600+0"]
[ECO "A11"]
[Opening "English Opening: Caro-Kann Defensive System"]

1. c4 { [%clk 0:10:00.03] } c6 { [%clk 0:10:00.03] } 2. g3 { [%emt 0:00:04.16] [%clk 0:09:55.87] } e5 { [%emt 0:00:03.84] [%clk 0:09:56.19] } 3. Bg2 { [%emt 0:00:01.92] [%clk 0:09:53.95] } Bc5 { [%emt 0:00:02.32] [%clk 0:09:53.87] } 4. e3 { [%emt 0:00:02.48] [%clk 0:09:51.47] } Qf6 { [%emt 0:00:01.84] [%clk 0:09:52.03] } 5. Nc3 { [%emt 0:00:01.44] [%clk 0:09:50.03] } d6 { [%emt 0:00:07.28] [%clk 0:09:44.75] } 6. Nge2 { [%emt 0:00:02.08] [%clk 0:09:47.95] } Ne7 { [%emt 0:00:05.44] [%clk 0:09:39.31] } 7. d4 { [%emt 0:00:09.92] [%clk 0:09:38.03] } exd4 { [%emt 0:00:05.84] [%clk 0:09:33.47] } 8. exd4 { [%emt 0:00:01.12] [%clk 0:09:36.91] } Bb6 { [%emt 0:00:04.96] [%clk 0:09:28.51] } 9. O-O { [%emt 0:00:04.08] [%clk 0:09:32.83] } Bg4 { [%emt 0:00:11.36] [%clk 0:09:17.15] } 10. Ne4 { [%emt 0:00:07.12] [%clk 0:09:25.71] } Qe6 { [%emt 0:00:24.48] [%clk 0:08:52.67] } 11. f3 { [%emt 0:00:15.52] [%clk 0:09:10.19] } Bh3 { [%emt 0:00:02.56] [%clk 0:08:50.11] } 12. Ng5 { [%emt 0:00:07.84] [%clk 0:09:02.35] } Bxg2 { [%emt 0:00:29.76] [%clk 0:08:20.35] } 13. Nxe6 { [%emt 0:00:06.96] [%clk 0:08:55.39] } Bxf1 { [%emt 0:00:01.12] [%clk 0:08:19.23] } 14. Nc7+ { [%emt 0:00:01.6] [%clk 0:08:53.79] } Bxc7 { [%emt 0:00:01.76] [%clk 0:08:17.47] } 15. Qxf1 { [%emt 0:00:03.68] [%clk 0:08:50.11] } O-O { [%emt 0:00:03.76] [%clk 0:08:13.71] } 16. Qh3 { [%emt 0:00:06.88] [%clk 0:08:43.23] } d5 { [%emt 0:00:08.48] [%clk 0:08:05.23] } 17. c5 { [%emt 0:00:16.08] [%clk 0:08:27.15] } Nd7 { [%emt 0:00:02.32] [%clk 0:08:02.91] } 18. Bg5 { [%emt 0:00:06.96] [%clk 0:08:20.19] } Nf6 { [%emt 0:00:10.64] [%clk 0:07:52.27] } 19. Bxf6 { [%emt 0:00:10.96] [%clk 0:08:09.23] } gxf6 { [%emt 0:00:01.6] [%clk 0:07:50.67] } 20. f4 { [%emt 0:00:08.56] [%clk 0:08:00.67] } Kh8 { [%emt 0:00:10] [%clk 0:07:40.67] } 21. Kg2 { [%emt 0:00:10.16] [%clk 0:07:50.51] } Ng6 { [%emt 0:00:01.6] [%clk 0:07:39.07] } 22. Qf5 { [%emt 0:00:08.64] [%clk 0:07:41.87] } Kg7 { [%emt 0:00:05.04] [%clk 0:07:34.03] } 23. h4 { [%emt 0:00:02.64] [%clk 0:07:39.23] } Rae8 { [%emt 0:00:07.12] [%clk 0:07:26.91] } 24. Kf3 { [%emt 0:00:03.12] [%clk 0:07:36.11] } Re4 { [%emt 0:00:13.04] [%clk 0:07:13.87] } 25. h5 { [%emt 0:00:09.28] [%clk 0:07:26.83] } Ne7 { [%emt 0:00:01.68] [%clk 0:07:12.19] } 26. Rh1 { [%emt 0:00:04] [%clk 0:07:22.83] } h6 { [%emt 0:00:23.12] [%clk 0:06:49.07] } 27. Qh3 { [%emt 0:00:10.32] [%clk 0:07:12.51] } Ng8 { [%emt 0:00:07.04] [%clk 0:06:42.03] } 28. Qf1 { [%emt 0:00:06.88] [%clk 0:07:05.63] } Rfe8 { [%emt 0:00:02.72] [%clk 0:06:39.31] } 29. Qd1 { [%emt 0:00:10.4] [%clk 0:06:55.23] } Re3+ { [%emt 0:00:05.36] [%clk 0:06:33.95] } 30. Kf2 { [%emt 0:00:11.12] [%clk 0:06:44.11] } R8e4 { [%emt 0:00:13.52] [%clk 0:06:20.43] } 31. Nc3 { [%emt 0:00:29.04] [%clk 0:06:15.07] } Re8 { [%emt 0:01:23.2] [%clk 0:04:57.23] } 32. Qd2 { [%emt 0:00:48.8] [%clk 0:05:26.27] } Ba5 { [%emt 0:00:07.92] [%clk 0:04:49.31] } 33. a3 { [%emt 0:00:07.12] [%clk 0:05:19.15] } Bxc3 { [%emt 0:00:05.36] [%clk 0:04:43.95] } 34. bxc3 { [%emt 0:00:01.12] [%clk 0:05:18.03] } f5 { [%emt 0:00:02] [%clk 0:04:41.95] } 35. Rb1 { [%emt 0:00:14.96] [%clk 0:05:03.07] } Nf6 { [%emt 0:00:07.6] [%clk 0:04:34.35] } 36. Rxb7 { [%emt 0:00:04.24] [%clk 0:04:58.83] } Ne4+ { [%emt 0:00:01.6] [%clk 0:04:32.75] } 37. Kxe3 { [%emt 0:00:04.16] [%clk 0:04:54.67] } Nxd2+ { [%emt 0:00:00.96] [%clk 0:04:31.79] } 38. Kxd2 { [%emt 0:00:00.96] [%clk 0:04:53.71] } Ra8 { [%emt 0:00:05.36] [%clk 0:04:26.43] } 39. a4 { [%emt 0:00:04.64] [%clk 0:04:49.07] } a5 { [%emt 0:00:00.88] [%clk 0:04:25.55] } 40. Rb6 { [%emt 0:00:02.64] [%clk 0:04:46.43] } Rc8 { [%eval 5.85,25] [%emt 0:00:01.36] [%clk 0:04:24.19] } 41. Kd3 { [%eval 5.82,17] [%emt 0:00:12.18] [%clk 0:04:34.25] } Kf6 42. c4 Ke7 43. cxd5 cxd5 44. Ke3 f6 45. Kf3 Re8 46. g4 Kf7 47. gxf5 Re1 48. c6 Ra1 ( 48... Rd1 ) ( 48... Rb1 ) 49. Rb1 Ra3+ 1-0

**Comment by HaonRekcef** [comment]
Thanks for reporting, I already fixed this in #596
