### ISSUE TITLE
puzzle: support variations for the opponent's moves

### ISSUE THREAD

**Issue by vlsi** [lichess-org/mobile#591]
Currently, lichess plays a single line for the opponent, so it does not verify the player calculated all the moves. The puzzle solution should account all the possible opponent's moves.

WDYT if lichess plays one or three variations for each puzzle? I guess it should accept the solution only in case the player solved all the variations.

**Comment by veloce** [comment]
Thanks for this suggestion. Thing is, this is the mobile repo which does not handle puzzle generation. This is more a question for lichess in general, so I'm gonna close this. You should check first if this feature has been already requested in `lila` repo or in the forums.
