### ISSUE TITLE
puzzle: support time-limited puzzles

### ISSUE THREAD

**Issue by vlsi** [lichess-org/mobile#592]
Currently, there's no time limit for a puzzle, so "puzzle rating" is too vaugue, and the puzzles can get significantly harder than a player can solve in a regular game.

WDYT if there were time-limited puzzles like "6 sec", "1 min", "10 min"?

For instance, when playing 1min bullet, it might be fine to spent 6-10 sec for a single puzzle. When playing 5min blitz, one can probably afford up to 1min (?) for major moves and so on.

**Comment by veloce** [comment]
This feature cannot be considered from the mobile app only, it would require a server change and it would be a feature implemented globally at lichess.

We do already have puzzle storm, which is a puzzle race against time. I don't think that for now timed puzzles are in the roadmap.
