### ISSUE TITLE
Wrong move gets played in the analysis board

### ISSUE THREAD

**Issue by HaonRekcef** [lichess-org/mobile#593]
### What is the problem?

I was analysing the following position: 

![screenshot](https://github.com/lichess-org/mobile/assets/78898963/c54178ba-19b7-4bfe-85e1-7d13fb84ca7c)

[Variant "From Position"]
[FEN "6k1/6P1/8/p2p2KQ/4r3/5R2/PP6/4q3 b - - 0 46"]

46... Qg1+

And I wanted to play the move Qg1+, but Qh1 was played, same problem when I try Qc1+, Qa1 happens.

### Steps to reproduce the bug

1. Copy this into the analysis board: [Variant "From Position"]
[FEN "6k1/6P1/8/p2p2KQ/4r3/5R2/PP6/4q3 b - - 0 46"]

46... Qg1+

2. Try to play Qc1 or Qg1

### What did you expect to happen?

Qg1 gets played

### What happened instead?

Qh1 was played

### Device Info

Pixel 6a

### Operating System Version

Android 14

### Additional information

- I tested it in a game and I was able to play Qg1 in the specific position.
- Qg1 also does not executed when pressing the engine line, Qh1 happens.

**Comment by HaonRekcef** [comment]
I've just identified what causes the bug. The issue occurs when a move is made that could potentially involve castling (e1-g1, e1-c1, e8-g8, e8-c8). Interestingly, this behavior is only observed in the analysis board and not on the game screen.

**Comment by veloce** [comment]
There's a logic only in `Node` to fix alternate castles. 

The bug comes from here and also because castling is not disabled in the position object obtained from the PGN (it should be).
