### ISSUE TITLE
Android system back interaction closes app unexpectedly

### ISSUE THREAD

**Issue by tedzards509** [lichess-org/mobile#599]
### What is the problem?

Android app is closed unexpectedly when using the system back navigation upon reloading one of the screens.

### Steps to reproduce the bug

1. Open a subpage on one of the main four screens (play, puzzles, tools, watch)
2. Go to another one of the main screens using bottom nav bar
3. Go back to the first page
4. Use the Android system back interaction

### What did you expect to happen?

Now the app closes

### What happened instead?

 instead of closing the subpage like it would when not switching to another page and back.

### Device Info

Oneplus 6T and S Tab 9 FE

### Operating System Version

Android 14

### Additional information

I assume this has to do with how the nav tree is reloaded. Might be an issue with Flutter itself. I currently cannot investigate further.

**Comment by veloce** [comment]
I don't understand the third step: go back to the first page, you mean the first page of the tab you went to a subpage? 
How do you do that from another tab?
