### ISSUE TITLE
Cannot move piece in puzzle streak to correct square

### ISSUE THREAD

**Issue by stephanhuebsch** [lichess-org/mobile#602]
### What is the problem?

In puzzle streak, I was not able to move the rook to the correct square, thus making it impossible to solve the puzzle. 

### Steps to reproduce the bug

1. Go to puzzle streak
2. ?

I'm not sure when/why this happens. It happened a few days ago too though, and if I remember correctly, it was also a rook that wasn't able to move to the correct square.

https://github.com/lichess-org/mobile/assets/22399869/b46cf66d-478d-4fc7-bd2a-126b8f8af074

### What did you expect to happen?

Being able to move the rook anywhere.

### What happened instead?

I wasn't able to move the rook anywhere.

### Device Info

Fairphone 4

### Operating System Version

Android 13

**Comment by HaonRekcef** [comment]
Thanks for the report, it should be fixed once my pr #596  is approved and a new version is released.
