### ISSUE TITLE
Feature Request - Chess960 tool for OTB

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#618]
I think a simple Chess960 starting position generator tool would be a really nice addition to the app.

It could be accessible from the Tools page, only a randomizer button is needed and the randomly picked starting position would be displayed with the already set board and piece theme.

I know there are websites for this already, but having this tool besides the existing chess clock tool would be great help and a very useful tool for those who like to play Chess960 over the board.

So even if it's not really high on the priority list of course, I'd love to see something like this in the already great new app! So please consider thinking about this, and thanks a lot in advance!

**Comment by tom-anders** [comment]
Not 100% the feature described in this issue, but you can now use the over the board feature (https://github.com/lichess-org/mobile/pull/924) to generate chess960 positions
