### ISSUE TITLE
Differentiate without color

### ISSUE THREAD

**Issue by DaniSpringer** [lichess-org/mobile#64]
App should indicate UI events visible with the assumption of grayscale

**Comment by veloce** [comment]
I cannot make any sense out of this, sorry. 

Please don't write issues in such a hurry. To make them useful you should describe as precisely as possible the requested feature. See: https://github.com/lichess-org/mobile/blob/main/CONTRIBUTING.md

I'm closing that one, feel free to open another one with a better description.
