### ISSUE TITLE
Porting Issues

### ISSUE THREAD

**Issue by DaniSpringer** [lichess-org/mobile#66]
Not sure if there is a better way than this, but creating a bunch of new issues seems suboptimal.

https://github.com/lichess-org/lichobile/issues?q=is%3Aissue+author%3ADaniSpringer+is%3Aclosed

**Comment by veloce** [comment]
What do you mean? I certainly don't want to have issues from lichobile ported here. This is a different project.

**Comment by DaniSpringer** [comment]
> What do you mean? I certainly don't want to have issues from lichobile ported here. This is a different project.

Except for the many bugs in common :)

**Comment by veloce** [comment]
There will be bugs for sure, issues will come in time :)
