### ISSUE TITLE
iOS victory dialog shows pixelated text

### ISSUE THREAD

**Issue by jruales** [lichess-org/mobile#663]
### What is the problem?

The text in the victory dialog is pixelated. See it for yourself and compare it to the other text, which is not pixelated: 
![image](https://github.com/lichess-org/mobile/assets/1588988/f0b9af70-34cb-4fd4-9372-7046fc81954b)

### Steps to reproduce the bug

Win or lose a game in the iOS beta app

### What did you expect to happen?

Native, non-pixelated text that uses vector-based graphics

### What happened instead?

pixelated text

### Device Info

iPhone 15 Pro

### Operating System Version

iOS 17

**Comment by veloce** [comment]
I also see it... unfortunately I don't think I can do much about it, it looks like an issue in the rendering engine.

**Comment by jruales** [comment]
@veloce perhaps the devicePixelRatio is not being properly set? It seems like the device pixel ratio is 3 for phones with Super Retina Display and 2 for devices with the older Retina Display

**Comment by jruales** [comment]
Never mind. I thought that devicePixelRatio could be changed, but I think it's actually a read-only property
