### ISSUE TITLE
Feature request: scrub through evaluation graph in iOS beta app

### ISSUE THREAD

**Issue by jruales** [lichess-org/mobile#664]
When reviewing a game in the iOS app, currently, the app only allows you to tap on the evaluation graph to jump to a certain point in the game. However, this is very imprecise especially for long games, so it's super difficult to go to a very specific part of the graph. I propose allowing the user to tap-and-drag so that they can make adjustments to the selected point of the evaluation line chart. To me it doesn't matter whether you immediately update the chessboard while scrubbing or not, I just care that you're able to scrub in the graph so that it's easy to get to a specific point in the graph, without having to try to aim multiple taps at the right spot.

**Comment by ijm8710** [comment]
I do admit I prefer drag over tap as well
