### ISSUE TITLE
Suggestion: Make Sign-in button more intuitive to find in iOS app

### ISSUE THREAD

**Issue by jruales** [lichess-org/mobile#665]
For me, it wasn't obvious that the Sign In button would be under the cog icon. The first thing I tried was the icon with the two people because I thought that would be the Profile menu, which usually has a person icon. I think it might be good to have the log in as a top level icon, or maybe use a hamburger menu icon to display the Sign In button? Something more intuitive than the current experience.

**Comment by veloce** [comment]
Fixed now with the new version.
