### ISSUE TITLE
Feature Request - Chessboard hue/brightness/opacity customization

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#667]
Recently a new feature was added to the main Lichess webpage, which allows the users to customize the appearance of the chessboard even more than before. Now it is possible to freely set and modify the hue, brightness and opacity of the already chosen chessboard theme with sliders. The number of ways one could combine the existing board themes and the new settings is obviously huge.

Of course I don't know how difficult this would be to implement in the new app, but if you think about it, this would be a great opportunity to make the app even more customizable for the users. I think it's safe to say that people love to experiment with board themes and colors and various piece sets - just look at how popular some Lichess customization web browser extensions are (for example Userstyles with custom board and piece scripts or Prettier Lichess). Some of them are even recognized by the Lichess team as well (https://lichess.org/page/extend) !!

As always, thanks for reading and responding in advance and please consider adding this amazing new feature to the new app! Thanks!

**Comment by TheHypnotist333** [comment]
Coming from the Prettier Lichess extension this makes the app much more aesthetically inviting. My friends ask me how I got lichess to look like this and when I let them know it's a browser extension not available in the app they are discouraged.

**Comment by NewSupKaizo55** [comment]
Thank you for your amazing work! Closing this 🐴❤️
