### ISSUE TITLE
Can’t play any background audio/video while playing a game

### ISSUE THREAD

**Issue by casbarof** [lichess-org/mobile#669]
### What is the problem?

Any audio playing in the background stops every time a move is made by either side. It then needs to be resumed manually. Same for PiP video.

### Steps to reproduce the bug

1. Start any audio playback, e.g., in the Podcasts app
2. Start a game
3. Audio stops every time a move is made by either side

### What did you expect to happen?

Audio/video continues to play

### What happened instead?

Audio/video stops until resumed manually

### Device Info

iPad Pro M2

### Operating System Version

iPadOS 17.4.1

### Additional information

lichess mobile v1 doesn’t have this problem

**Comment by iamnabink** [comment]
I think, this can be fixed by updating forked `soundpool` package `/ios` configuration.
This can be prevented by calling two simple methods on AVAudioSession sharedInstance in `SwiftSoundpoolplugin`:

```
AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.ambient, options: AVAudioSession.CategoryOptions.mixWithOthers)
AVAudioSession.sharedInstance().setActive(true)
```

**Comment by iamnabink** [comment]
I think, this can be fixed by updating forked `soundpool` plugin `/ios` configuration.
This can be prevented by calling/updating two simple methods on AVAudioSession sharedInstance in `SwiftSoundpoolplugin`:

```
AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.ambient, options: AVAudioSession.CategoryOptions.mixWithOthers)
AVAudioSession.sharedInstance().setActive(true)
```

@veloce what do you think?

**Comment by veloce** [comment]
Will try that.

**Comment by veloce** [comment]
Maybe fixed in https://github.com/lichess-org/mobile/commit/a4b6819bcddfcf91295f00261f6105411ac407ca 
(not tested).

I'm closing it but please reopen if the issue persist in next release.

**Comment by casbarof** [comment]
@veloce Problem still exists in 0.8.10.

**Comment by casbarof** [comment]
Tried again and this time it worked. But I definitely wasn’t hallucinating when it didn’t work earlier today. Resumed the audio several times and it paused after every move.

**Comment by casbarof** [comment]
Just happened again when playing a PiP YouTube video (YouTube app). I don’t know how to reproduce but it keeps happening every now and then.

**Comment by casbarof** [comment]
Happened again. Please reopen.

**Comment by veloce** [comment]
Unfortunately there's not much I can do if you don't reproduce all the time, and cannot predict when this will happen.

**Comment by casbarof** [comment]
Perhaps someone else can figure out how to reproduce this bug consistently. Closing it seems like the wrong action to take.

**Comment by casbarof** [comment]
I’m hitting this bug every time I use the app.

**Comment by casbarof** [comment]
Still happening every day. Seems to be happening the first time I play a PiP video on a given day. Doesn’t go away until lichess app is restarted.
