### ISSUE TITLE
Add search time settings to local analysis

### ISSUE THREAD

**Issue by casbarof** [lichess-org/mobile#670]
### What is the problem?

When locally analyzing a game, analysis of any position stops after a few seconds, typically around depth 26.

### Steps to reproduce the bug

Play a game, then analyze it locally.

### What did you expect to happen?

Infinite analysis.

### What happened instead?

Analysis of any position stops after a few seconds at low depth (~26).

### Device Info

iPad Pro M2

### Operating System Version

iPadOS 17.4.1

### Additional information

I can’t tell if this is a bug or limitation. I don’t see an option to turn on infinite analysis. I always prefer infinite analysis to fixed depth/time analysis. I never want to be served cloud results, which I don’t find useful due to their greatly varying depth and evaluation scores that differ dramatically from local engine at same depth.

**Comment by veloce** [comment]
That is not a bug. But I'll add a settings to control the search time, like in the website.
