### ISSUE TITLE
Feature Request - Change tabs with sideways swipe

### ISSUE THREAD

**Issue by NewSupKaizo55** [lichess-org/mobile#671]
This might sound silly, but sometimes I find myself swiping sideways to change between the tabs and screens in the Lichess app like if it was an other app, even though I know it is not possible to do that currently.

Now this is what inspired me to suggest this as a feature. The idea is that the user could change tabs with a fast sideways swipe gesture with a scroll animation. Always the next tab would show up, like for example swiping right from Home would bring the user to the Puzzles tab, without needing to tap the bottom bar icon. Sometimes it's quite uncomfortable, especially when holding the device in one hand.

One important thing is that this should be disabled on the surface of all chessboards and it should be disabled completely while playing a game on the game screen.

What do you think? Is it too much work to implement? Is it straight up a bad idea?

Thanks in advance for reading and responding!  ...and apologies for posting a lot of feature requests lately :D

**Comment by HaonRekcef** [comment]
I am not sure if this is a viable idea. I haven't seen any apps using this lately, especially since Android and iOS switched to swiping instead of using a back button by default. Can you point to recent apps that still use this?

**Comment by NewSupKaizo55** [comment]
One example I can quickly mention is the Reddit mobile app. With a sideways swipe, you can change between the main feed, popular tab, watch videos tab and latest posts tab. The transition between tabs is smooth, if you stop mid-swipe, you can see content from two tabs at the same time. This can also be done with a dropdown menu at the top.

**Comment by veloce** [comment]
Yes it won't happen because:
- too much work for the added benefit
- standard apps don't work like that and I'd rather stick to standard

We have tons of other things more important to do. So I'm closing it, sorry.
