### ISSUE TITLE
Bottom Menu Item Text wraps

### ISSUE THREAD

**Issue by SamuelBorn** [lichess-org/mobile#681]
![Screenshot_2024-05-14-11-12-13-66_cbee2060dbe813f67358565f077e6954](https://github.com/lichess-org/mobile/assets/58636569/f608495c-a03d-4163-b30e-f5f8632f3f5f)

I am using the lichess app in German.

As you can the word "Einstellungen" (settings) is wrapped in the picture.

I do not find this visually appealing.

Maybe reduce the font size?

**Comment by veloce** [comment]
Thanks for the feedback. I thought this would be handled by flutter, but it's not apparently :)

**Comment by veloce** [comment]
I'd rather not change the font size on this one but force labels to be short. I need to setup a translation project for the app, that will be one of my priorities.
In the meantime we'll use 'Settings'.
