### ISSUE TITLE
Overlay remains when game starts

### ISSUE THREAD

**Issue by gotjen** [lichess-org/mobile#682]
### What is the problem?

The "Waiting for oppoenent" overlay remains after a game has started. I have to click cancel to clear the spinner and begin the game. This happens intermittently. A screenshot of the bug is attached.
![Lichess_overlay_bug](https://github.com/lichess-org/mobile/assets/372588/6c34407c-f8ed-4a22-bf95-cb5d80ecbf53)

### Steps to reproduce the bug

1. Begin game from pool.
2. Await opponent.
3. Half the time, the game begins in the background including the gamestart chime, but the overlay remains.
4. It is possible to not notice the game has begun and accidentally time out on the first move, aborting the game and enraging the Lichess behavior demon.

Work around: tap [X Cancel]. The overlay is cleared and the game is available to play. The game does not abort after pressing cancel.

### What did you expect to happen?

Once I've been matched with opponent, I expect the "waiting" spinner to clear and the game to begin.

### What happened instead?

The overlay remains, blocking gameplay.

### Device Info

Device: Google Pixel 7

### Operating System Version

Android Version: 14

### Additional information

Android Build Number: AP1A.240405.002.B1
Lichess Version: 8.0.0

**Comment by veloce** [comment]
Sorry this is related to the old app, while this repo is for the new beta application.

**Comment by gotjen** [comment]
Thanks. Is there somewhere else it would be helpful to post this?
