### ISSUE TITLE
0.8.8 (808) doesn’t start

### ISSUE THREAD

**Issue by casbarof** [lichess-org/mobile#683]
### What is the problem?

When I start the app, all I get is a black screen with the knight logo. Previous version (0.7.9) works fine.

### Steps to reproduce the bug

Open the app.

### What did you expect to happen?

Works

### What happened instead?

Doesn’t work

### Device Info

iPad Pro M2

### Operating System Version

iPadOS 17.4.1

**Comment by pyrobc** [comment]
Same issue for me. Test flight pushed .8.8 on iPhone, try to open app it goes to white start screen with the black logo but nothing happens.

**Comment by ijm8710** [comment]
Def universal. Posted the same earlier on discord

**Comment by EmmetSchuler** [comment]
Just want to comment that at least for me, the android release is working fine.

**Comment by veloce** [comment]
Fixed by https://github.com/lichess-org/mobile/commit/e7c860ca16f3cc656418621ce8f35547079a0699
