### ISSUE TITLE
The app still says network connectivity unavaible after reconnecting to Internet

### ISSUE THREAD

**Issue by julien4215** [lichess-org/mobile#695]
To reproduce :

1, Open the app while being connected to Internet
2. Close your connection to Internet (you should now see the offline mode of the app)
3. Connect again to Internet (you see that you are still in offline mode despite begin connected)

**Comment by veloce** [comment]
I do reproduce on prod, but I have hard time to reproduce reliably locally.

**Comment by julien4215** [comment]
I should have mentioned that I tested only on prod. I cannot try locally because I don't have a local lila instance on my computer.
