### ISSUE TITLE
App doesn't return to home page on swiping back on a different tab.

### ISSUE THREAD

**Issue by shirsakm** [lichess-org/mobile#696]
When settings or any other tab is open, on swiping back or pressing the back button, the app exits instead of going back to the home page. I consider this to be expected behavior as this is how it worked in the old lichess app, and it also makes intuitive sense to me.

**Comment by veloce** [comment]
So swiping back would return to home tab instead of exiting if we're on another tab. Why not indeed.

Not sure how easy it is to implement though.

**Comment by julien4215** [comment]
I don't find this behavior counter-intuitive personally because you are switching between tabs that have the same importance and that are independent of each other (you can solve a puzzle without having first to play a game but you cannot change your description without going to the settings).

So I would say the actual behavior is more logical even I think the suggested behavior is also acceptable.

**Comment by veloce** [comment]
Perhaps the best way to know if we should do it or not is to compare with other popular apps. 

If they do it, ok. If not we'll close the issue.

**Comment by EmmetSchuler** [comment]
I think the majority of apps I use first take you back to the main page before closing. Examples are Whatsapp, Google photos, Gmail, etc. However, this seems to be when the main purpose of the app is on the first page.
There are some apps that notably don't do it, with examples like GitHub and Google fit.
In my opinion, I think that as the Lichess main screen grows in value, with features like the friends list, potentially blogs (not sure if this is planned), and access to - of course - playing games, it should be prioritized before closing the app itself.
Personally I am more used to returning to the main page of the app, as that's what my apps mainly do, but of course it's just personal preference.

**Comment by ZTL-UwU** [comment]
I found that the youtube app does it so that you return to the previously open tab when you swipe back instead of sending you to the home screen. I think this can be a better approach.
