### ISSUE TITLE
Add a button to delete local databases

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#698]
Lichess app stores games and puzzles in local databases.

Add a button at the bottom of the settings screen to delete them. The button must show a confirm dialog.

EDIT

- [ ] display the amount of storage used in MB

**Comment by amanxnanda** [comment]
@veloce, I would like to work on this one.

**Comment by ASD-coder-design** [comment]
@veloce Could you please assign this defect to me

**Comment by tom-anders** [comment]
> @veloce Could you please assign this issue to me

Someone else is already working on this: https://github.com/lichess-org/mobile/pull/827

Also, we don't assign issues in this project, see the [Contributing guide](https://github.com/lichess-org/mobile/blob/main/CONTRIBUTING.md#what-to-work-on)
