### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by archseer** [lichess-org/mobile#7]
Rather than building an entire app from scratch, why not embrace the PWA standard more? https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps

The website already functions almost like a native app if added to the home screen on iOS. With some work on offline functionality/service workers the analysis engine/analysis board/games vs computer could work without a connection too.

**Comment by archseer** [comment]
Add to home screen and service workers are both available on 97% of mobile devices:
- https://caniuse.com/web-app-manifest
- https://caniuse.com/serviceworkers

**Comment by veloce** [comment]
Yes, thanks for your suggestion. You are free to make your own PWA version.

**Comment by archseer** [comment]
I just wanted to know what your opinion was. Good luck on the mobile app!

**Comment by malaschitz** [comment]
Flutter app could compile to PWA.
