### ISSUE TITLE
Graph in game summary popup is hard to read under light mode

### ISSUE THREAD

**Issue by ZTL-UwU** [lichess-org/mobile#700]
### What is the problem?

the graph in game summary popup is hard to read under light mode.

<img src="https://github.com/lichess-org/mobile/assets/49156174/d700ab87-e20b-44df-8702-b5462c4c2ee7" width="300">

### Steps to reproduce the bug

1. Open a game with computer analysis

### What did you expect to happen?

The graph is readalbe with clear borders.

### What happened instead?

The white poportion of the graph is hard to read.

### Device Info

Redmi K40S

### Operating System Version

Android 13

**Comment by jruales** [comment]
+1. This is also hard to read on iOS. Not enough contrast between the white of the graph and the white of the background.
