### ISSUE TITLE
App broken on Android 10

### ISSUE THREAD

**Issue by BennieD** [lichess-org/mobile#715]
### What is the problem?

Version 0.8.012
Sign in from app not possible.
Anonymous play from quick select and custom game: "sorry, we could not create game. Please try again later."
Join a game: "Could not load challenges"
Puzzles: empty white screen, except for Puzzles header and menu bar at bottom.
Watch: Could not load TV channels; Could not load live streamers.

Android 10 on Samsung Galaxy A3 core

tested on Redmi with Android 12 - works fine

### Steps to reproduce the bug

click on puzzles
click on settings - sign in
click on watch
click on create game - play

### What did you expect to happen?

puzzles online/offline
reroute to lichess to authorise
streams to watch
play an anonymous game

### What happened instead?

White screen
nothing
"Could not load TV channels; Could not load live streamers."
""sorry, we could not create game. Please try again later."

### Device Info

Samsung galaxyn a3 core

### Operating System Version

Android 10

### Additional information

Samsung does not support higher android updates for a3 core.
App worked as expected before latest update.
App claims to be compatible for Android 5 and up, but my suspicion that the problem is the android version, 
might be incorrect.

**Comment by veloce** [comment]
I don't think it's related to an android version, because I also have android 10 and I don't reproduce this issue.

**Comment by BennieD** [comment]
Anything else I can do to test?
Info I can collect?
Could it be device specific? @NewSupKaizo55 what device do use?
Could it be memory availability? 
   My device storage: 13Gb/16GB
                     memory: 711MB/1GB
                     It seems to mean used / total available.
    Lichess Beta usage: storage: 94.45MB
                                    memory: 2.5MB on average in last 3 hours
                                    Permissions: No permissions required (no change from previous version)
                                    Attempt to sign in: no data used
                                    Attempt puzzles: no datat used
                                    Attempt game: no data used
                                    Analysis board usage: no data used
                                    Attempt watch: no data used
                                    Donate link (works fine): No data used by Lichess Beta, Data used by Chrome
                                    About Lichess link (works fine): Ditto
                                    All external links works fine.
Lichess Beta start-up screen is Home, but the options to sign in, etc (I cannot remember the other 2 options) expected does not show.
I am testing my wife's Samsung Galaxy A03 core with Android 13 now, will let you know.

**Comment by NewSupKaizo55** [comment]
The affected device is a ZTE Blade A31 / Android 11, 2GB RAM, Octa-Core 4x1.6 GHz + 4x1.2 GHz. It is my friend's phone who reported to me that the app was working perfectly before the new update without any problems and now all aspects of the app became unusable as in the bug report.

My phone that I currently use is a Xiaomi Redmi Note 10 5G / Android 13 (MIUI 14), 4GB RAM, Octa-Core 2.2 GHz. There are no problems with the app on my phone at all.

Between the two mentioned devices there is a difference in the Android version, the available RAM and the processors. I don't think the RAM or the processors are the cause because the app was working perfectly before the new update on the weaker device too.

Tell me if I can help another way or if I can provide any more information!

**Comment by NewSupKaizo55** [comment]
I got some screenshots now:

![Screenshot_20240525-143918.png](https://github.com/lichess-org/mobile/assets/118524250/0116d73e-cf9b-4714-a6b6-1174733493a0)

![Screenshot_20240525-143928.png](https://github.com/lichess-org/mobile/assets/118524250/ce90e68d-014e-4040-8132-c8d6a5a64261)

![Screenshot_20240525-143934.png](https://github.com/lichess-org/mobile/assets/118524250/7dcf2bee-197a-48c9-a075-e35d94f5ba47)

**Comment by veloce** [comment]
Considering the number of new crash reports I can tell this bug is due to the cronet http client not found which is very weird because no change to that regard has been made between 0.8.10 and 0.8.12.

**Comment by BennieD** [comment]
I'm afraid the problem still persists in v0.8.14
Unfortunately I cannot confirm which version still worked, as I don't know if I missed updates in between.
I learn something from this: as beta tester check the current working v nr before update!
(sorry, I'm inexperienced)
@NewSupKaizo55: can you confirm which version still worked for your friend, and did the 0.8.14 update fix the issue?
I cleared cache and data, and restarted the device - still not working.
