### ISSUE TITLE
Engine suggestion continues to be displayed after move was made

### ISSUE THREAD

**Issue by casbarof** [lichess-org/mobile#717]
### What is the problem?

As shown in the screenshot, after mate by promotion to rook, the engine suggestion (promotion to queen) continued to be displayed in game analysis.

![image](https://github.com/lichess-org/mobile/assets/169491148/86ecb2fc-955f-417c-9392-be18359c229a)

### Steps to reproduce the bug

See screenshot

### What did you expect to happen?

Engine suggestion is no longer displayed after a move has been made

### What happened instead?

Engine suggestion continues to be displayed

### Device Info

iPad Pro M2

### Operating System Version

iOS 17.5

**Comment by veloce** [comment]
Fixed by #724
