### ISSUE TITLE
option to view Lobby tab

### ISSUE THREAD

**Issue by mmh363** [lichess-org/mobile#72]
there are many players who don't play 960 or other variants because of exhausting opponent finding process!

for example :
you create a 960 variant , 10+30 game.
i'm OK with 10+30 , 10+25 , 15+20 ,15+25 , 20+15 and .....
but i'm on mobile app and don't have lobby so i can't see your created game and the only way to pair is when i also create exactly 960 , 10+30 game!!

it's an old feature request :
https://github.com/lichess-org/lichobile/issues/1149

is there any chance to add this feature?
thanks.

**Comment by veloce** [comment]
Legitimate. I don't think we'll add the lobby but being able to easily find an opponent when playing variants is a must have.

**Comment by veloce** [comment]
Closing because we won't make a lobby in the app. We'll make everything possible to be able to find easily games with variant.
