### ISSUE TITLE
Board flickers before and after a game

### ISSUE THREAD

**Issue by anth-git** [lichess-org/mobile#721]
### What is the problem?

Just before a game starts, and immediately after it ends the board shifts slightly down/up

### Steps to reproduce the bug

1. Start a new game
2. When a game starts, a board shifts down a few pixels
3. When a game ends, a board shifts up a few pixels

### What did you expect to happen?

It shouldn't flicker

### What happened instead?

It flickers

### Device Info

LG G7

### Operating System Version

Android 10

**Comment by veloce** [comment]
This is due probably to immersive mode (and only in some devices). This mode is now disabled by default and should be enabled only if having issue with system navigation gestures.

Fixed by #711
