### ISSUE TITLE
[Feature Request] Option to hide opponent's rating only during a game.

### ISSUE THREAD

**Issue by anth-git** [lichess-org/mobile#722]
Currently, there is no option to hide **only** the opponent's rating **only** during a game:

1. "Zen Mode" hides the rating and the material difference.
2. "Show Player Ratings" hides the rating everywhere.

I would like to be able to hide the rating only during a game but still be able to see it when opening the opponent's profile, in games history, etc.

**Comment by veloce** [comment]
I don't really want to add a new settings for this. Zen mode should be the way to go. Perhaps it does not make sense to remove the material diff in zen mode, I'll see if I can change that. But I believe I have followed the website behaviour.

**Comment by anth-git** [comment]
I think most people who use those options do so to not be distracted or intimidated by the opponent's rating, but they would still like to see the rating after the game. 
At least, this is how I would like to use it (but even "notable chess person" like GothamChess installed a Chrome extension to hide the rating). 
I don't see much use in hiding the rating everywhere, and I also don't think anyone is "distracted" by the material difference. In my opinion, the current implementation is too strict and makes this otherwise very useful function basically unusable.

**Comment by veloce** [comment]
Material difference should be shown, I agree. And I'll see about enabling zen mode only if the game is not finished.

**Comment by pyrobc** [comment]
I still see the opponents name and rating when zen mode is enabled. They only disappear after the first move. Would love to never see the rating even before the first move. 

And yes. Material difference should be able to be seen in zen.
