### ISSUE TITLE
app stuck at startup on logo screen

### ISSUE THREAD

**Issue by xraynaud** [lichess-org/mobile#727]
### What is the problem?

Since about the last 2 updates, the app is stuck at startup on the lichess logo screen. I have tried to uninstall reinstall the app but the behaviour is the same. The old lichess app works as expected. 
My phone is a Samsung A13

### Steps to reproduce the bug

Click on the app icon

### What did you expect to happen?

The app starts.

### What happened instead?

I can see the lichess logo but nothing happens

### Device Info

Samsung Galaxy A13

### Operating System Version

Android 14, Samsung One UI 6.0

### Additional information

i don't know if this can be related to #715 but in contrast to the OP the app does not start at all on my phone.

**Comment by veloce** [comment]
I think it's related. Probably due to https://github.com/dart-lang/http/issues/1213

There's a 0.8.15 version in review on play store. I'm closing it because it is suppose to fix it. Please reopen if the problem persist once you got the 0.8.15.

**Comment by xraynaud** [comment]
Hi, updated to 0.8.16 this morning and the problem is still there. I'd like to send you logs ,but I have no idea on how to obtain logs on an android phone...

**Comment by veloce** [comment]
Yes I mistakenly associated this problem with the cronet issue, but it is not.

Cronet issue is fixed now but there are known issues with flutter.

**Comment by veloce** [comment]
Can you tell me the last app version where it worked pls?

**Comment by xraynaud** [comment]
I think the problem appeared with version 0.8.13 but I am not fully sure. Is there a way to get the apk of the previous versions somewhere for me to check ?

**Comment by veloce** [comment]
You can in release page, try the 0.8.10:

https://github.com/lichess-org/mobile/releases/tag/v0.8.10

**Comment by xraynaud** [comment]
I can confirm that 0.8.10 works. I also wanted to try 0.8.12 but the
link on github leads to an error 404.

Le lundi 03 juin 2024 à 02:23 -0700, Vincent Velociter a écrit :
> You can in release page, try the 0.8.10:
> https://github.com/lichess-org/mobile/releases/tag/v0.8.10
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

-- 
Xavier Raynaud ***@***.***>

**Comment by veloce** [comment]
And to be sure... could you try to also install directly the APK from release 0.8.16 on GitHub? It is a universal APK contrary to what you get from the play store.
I cannot test on a Galaxy A13, but on a galaxy A11 it works with that APK.

**Comment by Kaloseidoscopeo** [comment]
Sorry for prying in, I have the same problem as the user above, 0.8.10 does not work
, 0.8.12 either

The problem arose when a I had to uninstall because of space, when I installed again 0.8.16 it stuck on the splash screen.

Device is Moto G23 Android 13

**Comment by xraynaud** [comment]
So, I did a little more digging, but it is more complicated than what I found at the beginning:
- v0.8.12 does not work on my phone. If it is connected to my lichess account (e.g. app upgraded from 0.8.10), the app gets stuck at the logo screen. If it is not connected, the app start, but I only have the top and bottom buttons and nothing on the main window. I suppose this is related to #715. 
- v0.8.16 corrects the problem, BUT only if I "Erase all data" of app (i.e. long press on app icon, click on the small app at top left of window, storage/erase all  data). This works with both the github and the play store version. Simply reinstalling the app (i.e. unsistall app and then install from play store) does not work. You have to "erase all data" prior the first launch. You can than connect to lichess account and play. I have to confirm this  tomorrow after the app is put to sleep by the system but "Erase all data" seems to be needed only the first time after install.

**Comment by veloce** [comment]
Thanks for all the digging! About the v0.8.12, you're right that is related to #715 .

About the "erase all data", I'm not sure yet why it is need over a simple reinstall, because that should already delete the local storage.

**Comment by veloce** [comment]
Probably related to #736

**Comment by veloce** [comment]
Do you confirm it is fixed with 0.8.17 @xraynaud ?

**Comment by xraynaud** [comment]
As I did not notice that the app had updated itself, I believe so. Thank you!

**Comment by veloce** [comment]
Ok closing, then.
