### ISSUE TITLE
Quick list of 5 inaccuracies that can be corrected/improved

### ISSUE THREAD

**Issue by Tevajs** [lichess-org/mobile#750]
### What is the problem?

1) Limitation of the rating range: only +- 50, 0 is not allowed.
2) Themes: no transparent, system and white makes no difference.
3) Join the game: Incomprehensible distribution by modes, ratings and time. Cannot configure
4) Vibration during captures and moves during the game. It's not clear how to turn it off.
5) The application has been cut down, but... This is a beta, I'll make a discount on it. The tournament aspect is completely missing

### Steps to reproduce the bug

Lichess BETA

### What did you expect to happen?

1) Ability to set +-0
2) Аdding a transparent background
3)  Ability to configure rating filters and search modes
4) Adding a setting that allows you to enable or disable this feature
5) Adding aspects like tournaments, teams..

### What happened instead?

Nothing

### Device Info

OPPO A21

### Operating System Version

Android 14

**Comment by veloce** [comment]
Thanks for the feedback. Github issues are useful to report bugs or write well detailed feature requests, but not the place for such feedback. 
You can use lichess forums for this, or the discussion tab.
