### ISSUE TITLE
Allow the Rating Range to begin from +-0 instead of +-50

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#751]
Report from the Forum:
The old Mobile app allowed you to set rating ranges starting from +-0.
The new app begins its minimum range from +-50
Is there a reason for this discrepancy? I think we should allow for more flexibility in the rating range system.

**Comment by veloce** [comment]
The reason was when I implemented that, I used the website as reference, and at that time, unless I hallucinated, we couldn't start from +-0.

I'm always using the website as reference and not the old app.
