### ISSUE TITLE
Missing German translations

### ISSUE THREAD

**Issue by AlphaYui** [lichess-org/mobile#753]
### What is the problem?

At various points in the app the German translation is missing. As the app language cannot be changed, I am unable to test if this applies to other languages as well or is specific to German.

#### Screenshot 1:
1. Search for a new game
2. The text "Waiting for opponent to join" on the waiting screen isn't translated.

#### Screenshot 2:
1. Open a finished game from the home page
2. Open the hamburger menu in the bottom left
3. The menu elements "Show result" and "Share game URL" aren't translated.

#### Screenshot 3:
1. Open a game from the home page
2. Open the settings menu in the top right
3. The menu points "Haptic feedback" and "Blindfold" aren't translated.

#### Screenshot 4:
1. Click the new game button on the home page
2. Click the "Other time control" button
3. The tab "Join a game" in the top bar isn't translated.

#### Screenshot 5:
1. Open the puzzles page
2. The description of Themes and Puzzle Storm aren't translated.

#### Screenshot 6:
1. Open Puzzle Storm
2. Tap "About Storm" in the bottom left.
3. The long description text in the popup isn't translated.

#### Screenshot 7:
1. Go to Tools -> Analysis board
2. "Leave empty for initial position" is not translated.

#### Screenshot 8:
1. Go to Settings -> Game behavior
2. The options "Haptic feedback", "Immersive mode" and its description aren't translated.

#### Screenshot 9:
1. Open the home page.
2. The greeting text at the very top isn't translated.

### What did you expect to happen?

I expected the text to be translated into German.

### What happened instead?

Some parts of the text are in English while others are correctly translated into German.

### Device Info

Samsung Galaxy A70

### Operating System Version

Android 11

### Additional information

Screenshot 1: ![Screenshot_1](https://github.com/lichess-org/mobile/assets/5251203/aeadff68-1c51-4e74-a2be-1d3ba438e996)
Screenshot 2: ![Screenshot_2](https://github.com/lichess-org/mobile/assets/5251203/cc49c4bb-02e3-4065-9beb-bed5a6892544)
Screenshot 3: ![Screenshot_3](https://github.com/lichess-org/mobile/assets/5251203/cba67b75-9e6b-43d4-a896-47b1a9223b51)
Screenshot 4: ![Screenshot_4](https://github.com/lichess-org/mobile/assets/5251203/4965f68f-dcaf-490f-b6bb-5b716d1268e7)
Screenshot 5: ![Screenshot_5](https://github.com/lichess-org/mobile/assets/5251203/2617612d-ff88-44c5-b17f-021f49bd1bbd)
Screenshot 6: ![Screenshot_6](https://github.com/lichess-org/mobile/assets/5251203/65a675db-2b33-41ba-b9f9-dca5d021da3f)
Screenshot 7: ![Screenshot_7](https://github.com/lichess-org/mobile/assets/5251203/1d730438-796f-4db7-89b3-8e048a25f6d5)
Screenshot 8: ![Screenshot_8](https://github.com/lichess-org/mobile/assets/5251203/7ab8477b-1242-42c5-975b-e509edf428a1)
Screenshot 9: ![Screenshot_9](https://github.com/lichess-org/mobile/assets/5251203/755064ee-b80b-4ab5-a1f5-8d2ea200dede)

**Comment by tom-anders** [comment]
Most of these are already fixed via https://github.com/lichess-org/mobile/pull/826, and https://github.com/lichess-org/mobile/pull/857 adds translations for some that I missed the first time.

Note that I did not add a translation for the puzzle storm description, since the string is takes from lichess.org which does not have a translation for this either currently, so we'll need to wait for that

**Comment by veloce** [comment]
Closing at this is tracked elsewhere.
