### ISSUE TITLE
Disable piece animation by default in bullet time controls

### ISSUE THREAD

**Issue by csaavedra** [lichess-org/mobile#757]
### What is the problem?

In bullet games I would expect the piece movement to be as fast as in the web and legacy mobile app. Instead it's slow as in longer time control games, which is very confusing.

### Steps to reproduce the bug

Play bullet. Make moves.

### What did you expect to happen?

Pieces should move very fast to the destination squares.

### What happened instead?

Pieces move very slowly.

### Device Info

Irrelevant

### Operating System Version

Android

### Additional information

This is from the beta app installed from Android's app store, a couple of days ago. I won't be playing bullet with this app again until this is resolved, so if it was fixed since then I don't know.

**Comment by veloce** [comment]
Unfortunately "fast" and "slow" don't mean much.
You could perceive move as being slower for various reasons but in fact they aren't slower.

First thing you can do is trying to be more descriptive. Make a video if you can, explaining why it feels slower.

**Comment by csaavedra** [comment]
I realize now why this might not be 100% clear. I am talking in particular to "two tapping" piece movement. You tap on the piece, and then tap on the target square. In classical/rapid/etc there is an animation where the piece moves from origin to target in what is about half a second. In the web and legacy UI app, however, in bullet time controls the movement is immediate.

Here are two screencasts from the web UI. The first one is from a bullet game.

[Screencast from 2024-06-09 14-02-03.webm](https://github.com/lichess-org/mobile/assets/2523171/8d3d27e8-3ec8-4f69-966d-36b524441809)

The second one is from a blitz game, also web UI:

[Screencast from 2024-06-09 14-02-27.webm](https://github.com/lichess-org/mobile/assets/2523171/3d653d6a-22a7-4ca1-b0cc-7b2db3910d96)

You can clearly see what I am talking about here. In the bullet game there is no animation, movement is immediate. In the blitz game, there is an animation. In the new mobile app, bullet pieces move at the same rate as in the second video when moved as I descrived in the first paragraph. That is the problem.

Is it clear now?

**Comment by veloce** [comment]
So you just need to disable move animations, there's a settings for that.

I don't think animations are disabled by time control in the website. So guess you had them already disabled in web and old mobile.

**Comment by csaavedra** [comment]
The video I made is from a new browser session in incognito mode, not logged in. I never changed any settings. I am pretty sure these are defaults.

**Comment by csaavedra** [comment]
> I don't think animations are disabled by time control in the website.

Also, it would take you 30 seconds to test that what you are saying is not correct, opening an incognito session and starting a bullet game.
