### ISSUE TITLE
Move Notation preference setting not followed in new app

### ISSUE THREAD

**Issue by LukeyPmoney** [lichess-org/mobile#759]
### What is the problem?

In the new app, the list of moves is always in letter notation when playing a game, but the analysis board (both the separate tool or within a game) always shows moves in figurine notation. Also, this preference setting can only be updated on the website, not in the app.

### Steps to reproduce the bug

On the website, click/tap profile icon -> preferences -> display. Change the Move Notation setting to the opposite of what it was and save.
Next, start a game in the lichess app and make a non-pawn move. Click analysis icon or switch to analysis board tool and make a non-pawn move.

### What did you expect to happen?

Both in an active game and on the analysis board, the move notation preference setting should be respected. Also, this preference should be editable within the app instead of only on website.

### What happened instead?

In-game in the new lichess app: game moves notation is in letter form regardless of move notation setting. Switch to analysis board, either the separate tool or within a game: game moves and moves within analysis lines are always in figurine notation, regardless of move notation preference setting.

### Device Info

Samsung Galaxy S7

### Operating System Version

Android 8.0.0

**Comment by eliogilvy** [comment]
@veloce which api call handles this? I'm looking at api/account/preferences and not seeing anything... I see it in
[Scala file](https://github.com/lichess-org/lila/blob/master/modules/pref/src/main/Pref.scala) but am not seeing the field when talking to the api/account/preferences.

**Comment by awan1** [comment]
Verified on Android 14, Pixel 8
