### ISSUE TITLE
Puzzles: show next correct move

### ISSUE THREAD

**Issue by FR86** [lichess-org/mobile#761]
I quite liked the way that the old app only gave you the next correct move in a puzzle when you tapped "show solution". That enabled me to think about the next move in the sequence until I had the puzzle fully solved, even though it was counted as wrong.
Would it be feasible to add a "show next move" button in addition to the "show solution" that is there, currently?

**Comment by veloce** [comment]
Or the show solution could just advance to the next move instead of playing the whole sequence.

**Comment by FR86** [comment]
Sure, that would work for me. I'm just not sure how discoverable that makes multi-move solutions, that took me a while to figure out in the old app.

**Comment by ijm8710** [comment]
I would very very much like this.
