### ISSUE TITLE
Stuck offline "lichess.org is not reachable. Failed to fetch"

### ISSUE THREAD

**Issue by AdrienBI** [lichess-org/mobile#764]
### What is the problem?

The Android mobile app is not able to retrieve data from the server.
Home screen show "progress circle" indefinitely.
Puzzle screen fails and displays the message "lichess.org is not reachable. Failed to fetch"
Login and all the features requiring network do the same.

Offline game against Stockfish is working.

### Steps to reproduce the bug

Open the app : home screen not able to retrieve info from the server
Try any feature requiring network : it will fail and display the message "lichess.org is not reachable. Failed to fetch"

### What did you expect to happen?

I should be able to login and use the network game

### What happened instead?

I'm stuck with the offline game.

### Device Info

Samsung Galaxy A5 2016

### Operating System Version

Android 7.0

### Additional information

I think the problem is related to my old (but up-to-date) Android version.
I think is it related to SSL and/or certificate used to establish the connection to the lichess server.

This is a common issue for old Android device. There are few threads on the lichess forum : https://www.google.com/search?q=lichess+failed+to+fetch

**Comment by AdrienBI** [comment]
A good alternative may be to use a web browser like Chrome, instead of the app.
We have to uninstall the lichess app, otherwise the web browser will switch to the app on game startup.
It seems I'm able to play with Chrome.

**Comment by veloce** [comment]
Wrong repo, this is about the old app: lichess.org/lichobile.
