### ISSUE TITLE
Accuracy Metric

### ISSUE THREAD

**Issue by BrendanEMahon** [lichess-org/mobile#77]
The accuracy metric is useful and present on the site.  Currently, the mobile app only shows average centipawn loss.  Please display the accuracy metric in the mobile app as well.

**Comment by veloce** [comment]
You should be more specific, it'd gives you more chances to see your request fulfilled. Where is that accuracy metric in the site for instance?

**Comment by meenbeese** [comment]
I think he may be referring to this:![image](https://user-images.githubusercontent.com/114044633/229238220-717110a4-027f-45c7-a917-c9332bf5e945.png)

**Comment by rhenandias** [comment]
I believe that @BrendanEMahon intentions would be to publish in the current app repository ([Lichobile](https://github.com/lichess-org/lichobile)), this repository refers to the new version of the app still under development, and that does not count with the possibility of performing analysis yet

**Comment by veloce** [comment]
Done.
