### ISSUE TITLE
Opt-out Piece magnification

### ISSUE THREAD

**Issue by shuvashish76** [lichess-org/mobile#770]
I understand V2 is an newer app and eventually features will be added it...just wanted to point out that magnification is on by default & there is no option to disable it.
Actually it's a nice feature for slower time controls but it's very bad for faster time controls as it creates unnecessary animations hence required unintended attention for it.

Option to disable it just like our old app would be nice.
![liiiiiiiiiichhess_magnified_pieces](https://github.com/lichess-org/mobile/assets/48226312/fdeabf1f-1757-4b60-a2f5-4e579a7774cb)

**Comment by KartikWatts** [comment]
@veloce Hi.  Would love to start contributing to the mobile repo with this issue. Kindly assign me if feasible. Regards

**Comment by veloce** [comment]
We don't assign issues. Feel free to start working on it, and you can make a draft PR if you're not finished and want to indicate other you're working on this.

**Comment by tom-anders** [comment]
@KartikWatts are you still planning to work on this? Otherwise I'd take a go

**Comment by KartikWatts** [comment]
@tom-anders Couldn't start working on it yet. Sure, you can take this up. Regards.

**Comment by tom-anders** [comment]
Thanks! I've seen that this feature has been requested multiple times over at https://lichess.org/forum/team-lichess-beta-testers, so I'll try to get it into the next official release if possible.
