### ISSUE TITLE
Can’t view imported games

### ISSUE THREAD

**Issue by steinitz** [lichess-org/mobile#777]
### What is the problem?

When choosing from the games popup e.g. “rated”, “losses”, “imported”, the “imported” option doesn’t show imported games.  Instead it shows all Lichess “native” games.

### Steps to reproduce the bug

1. Drop down the user menu
2. Choose games
3. Click the game-type selector e.g. “draws”, “wins”
4. Select “imported”

### What did you expect to happen?

See imported games

### What happened instead?

See all Lichess native games and not imported games

### Device Info

iPad Pro M1

### Operating System Version

IOS 17.5.1

### Additional information

This feature works correctly on the web version

**Comment by veloce** [comment]
Wrong repo, this bug describes a feature present in the old mobile app (lichess-org/lichobile).

**Comment by xkrchnav** [comment]
> Can you please clarify?  The feature, and the bug, exist in the latest version mobile app from the Apple iOS Store.  Are you saying this repo is for an old mobile app?

Yes, you need to use something like https://play.google.com/store/apps/details?id=org.lichess.mobileV2 at least this is how it's named in Google play.

**Comment by steinitz** [comment]
I remain unsure of how to report this bug, which occurs on the latest iOS version of Lichess.  This Lichess mobile repository seems the most active, seems recent so seems the right place to report the bug.  Can you please confirm that this repository is used to build the latest iOS version?

I’m not soliciting information about obsolete mobile versions or Android versions.  I’d just like to get this bug, which occurs in the latest Lichess iOS version, on record.

Am I missing something obvious that’s eliciting discussion about old versions and Android?

**Comment by xkrchnav** [comment]
You should report this in lichoble app as suggested by author in first reply:
https://github.com/lichess-org/lichobile

This is repo for new V2 app.

**Comment by steinitz** [comment]
Ah, I think I finally understand: the app on the iOS app store is the “old mobile app”.  This repo is for an unreleased “v2” mobile app.  Right?

And I now see that at least three people have reported this bug in the “old mobile app” repo.

I apologize for the noise.  Lichess is a mighty gift to the chess world.  Thank you beautiful contributors.

**Comment by ijm8710** [comment]
I think a better way to reply back to your post @steinitz is that the version you are using is most likely not being developed anymore.

There's a new beta that's a complete rewrite that's been in the works for a while

So a better move might be (in this GitHub) to file a feature request to have ability to see a differentiation of imported games. That way it'll potentially be added down the line in the new app as opposed to filing a ticket for the old app that will prob never be worked on

**Comment by steinitz** [comment]
Thanks for your advice @ijm8710.  I see what you're saying.

For now, I'll sit tight and wait for the new version to drop, then see what's what.

**Comment by ijm8710** [comment]
Should be communicated in discord how to join the beta. Apps at a point where while it's still in beta, it's already more developed than the old app and is pretty along
