### ISSUE TITLE
El texto se sale del borde de la pantalla 

### ISSUE THREAD

**Issue by ArleyFelipe** [lichess-org/mobile#782]
![Screenshot_20240615_131815](https://github.com/lichess-org/mobile/assets/172576153/de2838c3-7848-427d-840a-23d5ef2484d2)

**Comment by ArleyFelipe** [comment]
I really want to thank you for this new app, it was about time for an update.

I would like for more colors to be added to the board in the future, more styles of pieces, a bit more minimalist.

You should also add the ability to play with the chess bot offline, chess studies offline as well (at least the PGNs), and many more things.

Without a doubt, the best app.🌀

**Comment by HaonRekcef** [comment]
I think this can be closed. The the 'find the best-move' text can be two lines now.
