### ISSUE TITLE
Puzzle history

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#79]
Offline puzzle history, using a new SQLite table.

We should store only the last n (2?) months of history. Deleting old items should be done at startup time, when opening the database, or with a cron job.

On main puzzle tab screen, only show the last 10 items. Tapping the "..." goes to the full history screen.

Tablet support needed here. See leaderboard screen for an example.

![Puzzle history](https://user-images.githubusercontent.com/423393/226102188-daa18b8b-ab18-42d2-ba25-3caceccb17ca.png)

**Comment by nav-28** [comment]
closed with #211
