### ISSUE TITLE
Unable to challenge other players to a correspondence game

### ISSUE THREAD

**Issue by HaonRekcef** [lichess-org/mobile#801]
### What is the problem?

Unable to challenge other players to a correspondence game or a game without time limit

### Steps to reproduce the bug

1. Go to a profile
2. Challenge the player to a correspondence or or a game without time limit

### What did you expect to happen?

The player gets challenged

### What happened instead?

nothing happens

### Device Info

-

### Operating System Version

-

**Comment by veloce** [comment]
Good catch! We should probably disable correspondence challenge until this is implemented (and create an issue about it).
