### ISSUE TITLE
Option to change Auto-Queen in Game Settings

### ISSUE THREAD

**Issue by HaonRekcef** [lichess-org/mobile#802]
At the moment, it is not possible to change the auto-queen setting from the game screen. While playing on the website, you can disable auto-queen by pressing Alt, even if it is enabled in the global settings. In my opinion, there should be an option to disable auto-queen in the game settings, perhaps without overwriting the global settings.

**Comment by veloce** [comment]
Like in the game screen settings (top right gear icon) but that would apply only to the current game without changing the global one? If so, that should be easy to do.
