### ISSUE TITLE
Feature request: stat pages to display average accuracy for each respective variant

### ISSUE THREAD

**Issue by ijm8710** [lichess-org/mobile#818]
I would absolutely love this. 

I also feel that "games played in a row" and "max time spent playing" are absolutely useless sections.

**Comment by ijm8710** [comment]
@veloce would you be open to accepting this as a pr? The way I see it, some combination of:

- avg variant accuracy can share the row with rating deviation (this probably makes the most sense)
- or combining progression last 12 with rating deviation on same row
- or moving progression over last 12 on the same row with the rating itself

**Comment by veloce** [comment]
I think it's not possible to do this right now. The thing is, that depends on the server to have that logic. It is a server issue to submit, so in Lila: https://github.com/lichess-org/lila
