### ISSUE TITLE
Weird behavior between new Home widget settings and background color.

### ISSUE THREAD

**Issue by ohjunseung** [lichess-org/mobile#839]
### What is the problem?

Home widget setting change also changes the background color to default device color on next application start, vice versa.

### Steps to reproduce the bug

1. Open app
2. Change home widget selection/settings.
3. Save changes
4. Re-open App (background got changed)
5. Change background color
7. Re-open App (widget selection/settings reset to default)

### What did you expect to happen?

Background color settings don't get affected by home widget settings change. vice versa

### What happened instead?

Home widget setting change the background color to default device color on next application start, and vice versa.

### Device Info

Samsung A33 5G

### Operating System Version

Android 14

### Additional information

https://github.com/lichess-org/mobile/assets/53179765/51d786e6-a636-4bad-a665-4db990e8f511

**Comment by veloce** [comment]
Thanks for the report.
