### ISSUE TITLE
Puzzle streak stuck on draw mode

### ISSUE THREAD

**Issue by stillmtndewfan** [lichess-org/mobile#845]
### What is the problem?

When playing puzzle streak draw mode is stuck on and I am unable to select pieces.

### Steps to reproduce the bug

1. start puzzle streak
2. solve 2 or 3 puzzles
3. hold screen while next puzzle loads
4. Stuck in draw mode until exiting puzzle streak

### What did you expect to happen?

When using only 1 finger to touch the screen I expected to select/move pieces

### What happened instead?

Arrows were drawn or circles were placed.

### Device Info

Pixel 6

### Operating System Version

Android 14

**Comment by EmmetSchuler** [comment]
Can confirm with this.
Also want to add that sometimes you don't even need to touch the screen to have issues with moving pieces.
After completing a puzzle, wait a couple seconds into the next puzzle and I cannot move any of the pieces (this is without touching the screen in the meantime). However it doesn't attempt to draw either.

**Comment by ArleyFelipe** [comment]
How I can enable draw mode?

**Comment by stillmtndewfan** [comment]
Draw mode is supposed to be a two finger tool.  You press one finger to an empty square and use your second finger to draw arrows or mark squares.

**Comment by veloce** [comment]
I can't reproduce. I'm trying to hold a finger to the board while the next puzzle is loading but it doesn't lock the board in draw mode.

Can you add more precise steps on how you achieve to reproduce this bug? Thanks.

**Comment by steptro** [comment]
Also shouldn't the arrows be removed after a move and after completing a puzzle?

**Comment by NewSupKaizo55** [comment]
The taps are visible on the screen. 

1. Open Puzzle Streak
2. Solve a puzzle
3. Hold down any square while the new puzzle loads (this can be any other square or just accidentally keep holding the piece you moved last)
4. When the new puzzle is shown, the drawing mode is enabled already

https://github.com/lichess-org/mobile/assets/118524250/2f8525ca-17c3-47ed-8f51-db5526898660

**Comment by veloce** [comment]
Well I tried to do that: hold a piece while the next puzzle loads but I could not reproduce the bug.

But I have found one cause for the other bug, where the pieces are completely stuck.
