### ISSUE TITLE
Puzzle stuck on arrow drawing mode

### ISSUE THREAD

**Issue by cavollopollo** [lichess-org/mobile#848]
### What is the problem?

Problem happened twice already. After completing a puzzle, and moving to the next puzzle, in two occasions the next puzzle was stuck on arrow drawing mode (see screenshot), with no option to disable it and actually make a move.
![IMG_6211](https://github.com/lichess-org/mobile/assets/23168198/00d4c03f-a9bd-4a17-bf33-968ef2fb4b09)

### Steps to reproduce the bug

Not easy to reproduce I think. In 2 cases the app was stuck with this arrow drawing mode.
Restarting the app fixed the problem.

Investigation can probably start from knowing what triggers the arrow mode on / off, and checking why the event to turn it off does not execute. (could be some connection problem / error handling problem?)

### What did you expect to happen?

The next puzzle should allow users to make moves.

### What happened instead?

The app is stuck in ‘arrow drawing mode’, see screenshot

### Device Info

iPhone pro 14

### Operating System Version

Latest iOS

**Comment by veloce** [comment]
Already fixed.
