### ISSUE TITLE
Character encoding issues in leaderboard.

### ISSUE THREAD

**Issue by PunchCakee** [lichess-org/mobile#85]
![Screenshot_20230321_001932](https://user-images.githubusercontent.com/80383169/226468534-c4a0799d-4755-45f9-a2fe-bee4b662938a.jpg)

As seen above there is an issue regarding the character encoding.

Reproduce:
Home -> leaderboard -> Danya06-2014

**Comment by ohjunseung** [comment]
maybe just use utf8.decode() on the response body like this one
https://github.com/lichess-org/mobile/blob/1af31cbc04e2ca31b9af78f6cfa7ee7c73024636/lib/src/model/user/user_repository.dart#L67

**Comment by veloce** [comment]
Fixed.
