### ISSUE TITLE
In offline mode it is impossible to make a move in a puzzle

### ISSUE THREAD

**Issue by gyermolenko** [lichess-org/mobile#851]
### What is the problem?

In offline mode it is impossible to make a move in a puzzle

### Steps to reproduce the bug

1. Open app in the Offline mode
2. Select any puzzle (let's say Mates in 2) and try to select or move any piece

### What did you expect to happen?

I should be able to select a piece and move it. Or select and unselect it.

### What happened instead?

Two kinds of behavior, seemingly random occurance. Either
a) can't select anything at all, no selections, no movement
or
b) "touch" draws a circle on a touched square

### Device Info

Pixel 7

### Operating System Version

Android 14

### Additional information

App version: I've just encountered it after upgrade to v0.9.2, and haven't seen it in v0.8.18
Workaround: go back to puzzle dashboard and then back to the puzzle.

**Comment by veloce** [comment]
Same bug as #845 ; fixed in 0.9.3
