### ISSUE TITLE
Draw Arrow Circle rendering bug

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#852]
### What is the problem?

Just a slight issue, when holding down to draw an arrow, and then moving the arrow back to the original square (to make it a circle) now has a rendering error.

### Steps to reproduce the bug

Go to any chess board
Hold your finger and slowly increase the arrow length
Don't let go and bring the arrow back to the original square and release

### What did you expect to happen?

A Circle should appear

### What happened instead?

A buggy arrow
![Screenshot_20240712-081717](https://github.com/user-attachments/assets/2d49ebda-770a-418a-b936-1231d805688e)

### Device Info

Pixel 6

### Operating System Version

Android 14

**Comment by veloce** [comment]
Let's say it's not a bug, but a feature to draw odd shapes 😁

**Comment by tom-anders** [comment]
Should be closed with https://github.com/lichess-org/flutter-chessground/commit/363d9d7979f1c74a2ca4900fcedb72066bebb46d
