### ISSUE TITLE
Feature request: option to change move input method

### ISSUE THREAD

**Issue by whl64** [lichess-org/mobile#855]
Currently, either drag and drop or 2 taps are supported input methods. It would be nice to have the option to disable one.

**Comment by EmmetSchuler** [comment]
+1 for this, I think it would help against unintentional misclicks

**Comment by tom-anders** [comment]
I've started to work on this today. I assume we do **not** want to sync this setting with the Web UI, do we? I'd imagine many users want different settings depending in whether they're playing with a mouse or touch screen

**Comment by whl64** [comment]
I agree that it makes sense to not sync this setting.
