### ISSUE TITLE
King in check board highlight

### ISSUE THREAD

**Issue by PunchCakee** [lichess-org/mobile#86]
![Screenshot_20230321_161827](https://user-images.githubusercontent.com/80383169/226618250-107c38e7-a6fe-4041-a873-8b7596065aa7.jpg)

Black is in check but the red mark on the king does not show.

This issue also applies for white.

Steps to reproduce:
Go to puzzles.
Get in check as black.

**Comment by veloce** [comment]
This is not a bug, more a feature request. I won't necessarily implement it.

**Comment by PunchCakee** [comment]
I dont know if its a bug or not but as lichess player i expect a red mark to appear on the king that is checked like the website and the capacitor app.

**Comment by veloce** [comment]
Make a pull request if you like.

**Comment by Mansour-J** [comment]
> I dont know if its a bug or not but as lichess player i expect a red mark to appear on the king that is checked like the website and the capacitor app.

+1 I believe it's important to have consistent behavior.

**Comment by veloce** [comment]
Done in https://github.com/lichess-org/mobile/commit/84a0ccc3b3935ddbb589d1f2fdd9110b64ee9857
