### ISSUE TITLE
Tap and move - deselecting issue 

### ISSUE THREAD

**Issue by Lorrid** [lichess-org/mobile#860]
### What is the problem?

When tapping a piece to move it, if my finger moves even a millimeter, game deselects the piece. This happens a lot in faster time control games, because my fingers move faster. But I checked in puzzles too, my finger doesn't leave the square. I know it shouldn't be like this because it doesn't happen in old app or chess.com app. 

### Steps to reproduce the bug

1. Tap a piece and move your finger just slightly, stay in the square. (as if you are playing a bullet game) 
2. When you tap again to move the piece, it won't because it was de selected when you moved your finger slightly. 

### What did you expect to happen?

I expected to move the piece as I could in the old app. 

### What happened instead?

Couldn't move the pice because it was deselected. 

### Device Info

Samsung galaxy s20+

### Operating System Version

Android 13

**Comment by tom-anders** [comment]
Looks like this could be solved by increasing [_kDragDistanceThreshold](https://github.com/lichess-org/flutter-chessground/blob/main/lib/src/widgets/board.dart#L20)

With https://github.com/lichess-org/mobile/pull/864 a solution would also to simply disable drag input

**Comment by veloce** [comment]
You didn't mention the app version @Lorrid ; 

I don't this we should increate the drag distance threshold. If you don't want to use drag, I think #864 is the best solution indeed.

**Comment by tom-anders** [comment]
> You didn't mention the app version @Lorrid ;
> 
> I don't this we should increate the drag distance threshold. If you don't want to use drag, I think #864 is the best solution indeed.

Since #864 is merge now, I think this issue can be closed as well
