### ISSUE TITLE
Unexpected arrows

### ISSUE THREAD

**Issue by vada4367** [lichess-org/mobile#862]
If i place two fingers on display, i draw arrows and circles. But it is super uncomfortable! Delete this possibility, or create button for arrows mode. It will be great, if you make some one setting. Sorry about my english, I'm 15 yo from Ru

https://github.com/user-attachments/assets/62ab26d8-1a1c-4266-8440-fc56099b5bb5

**Comment by veloce** [comment]
Yes a settings to enabled it is planned.
