### ISSUE TITLE
Zero unit should be plural

### ISSUE THREAD

**Issue by py660** [lichess-org/mobile#886]
### What is the problem?

The unit for 0 (or unloaded data) is singular, while the unit should actually be plural. When data isn't loaded, the unit should still be plural (e.g. "? player" vs "? players) since the unknown quantity placeholder is in itself plural.

### Steps to reproduce the bug

![Screenshot_20240726_214141](https://github.com/user-attachments/assets/9dfd9084-5e58-4d84-a831-6d4c21af484a)

![Screenshot_20240726_213411](https://github.com/user-attachments/assets/ce1e5837-b02b-4023-90ef-ebaabc9433b6)

### What did you expect to happen?

Plural units

### What happened instead?

Singular units

### Device Info

S21 Ultra

### Operating System Version

Android 14 OneUI 6.1

**Comment by tom-anders** [comment]
@veloce FYI, I'll take a look at this, looks like another localization issue maybe

**Comment by veloce** [comment]
Just to be sure, what is your app version @py660 ?

**Comment by tom-anders** [comment]
Ah yes I quickly checked the code, this was already fixed in #808, so issue can be closed

**Comment by HaonRekcef** [comment]
Probably we should include the app version number in the github issue form

**Comment by py660** [comment]
> Just to be sure, what is your app version @py660 ? 

I just downloaded it from Google play: 0.8.17
