### ISSUE TITLE
Strange inversion of pieces, suddenly opponent king moved next to my queen

### ISSUE THREAD

**Issue by michaelmaguire** [lichess-org/mobile#888]
### What is the problem?

While playing suddenly pieces appeared to swap, and my opponents king moved right next to my queen.

I took the "king" with my queen, but the game kept going, apparently without a king for my opponent for a while, however eventually pieces swapped again and my opponent had a king once more.

![Screenshot_20240726-235237](https://github.com/user-attachments/assets/51372145-8552-41b5-90ef-a6891476812a)

### Steps to reproduce the bug

Started a game on Android. Made a few moves.

### What did you expect to happen?

Chess play should proceed normally

### What happened instead?

My opponent's king made a weird move

### Device Info

Pixel 8 Pro

### Operating System Version

Android 14

### Additional information

https://lichess.org/xF9ac7zQ/black#31

**Comment by veloce** [comment]
Sorry, wrong repo. This is for the [old mobile app](https://github.com/lichess-org/lichobile).
