### ISSUE TITLE
No sound played when a game starts

### ISSUE THREAD

**Issue by tom-anders** [lichess-org/mobile#890]
### What is the problem?

Both the old app and lichess.org play the "bell" sound when a new game starts (e.g. after finding a game via the game matrix, or when your next pairing in a tournament is found). This is currently missing from the new app.

### Steps to reproduce the bug

1. Open App
2. Press any time control in the game matrix (e.g. 5+0)
3. Wait for opponent
4. Once opponent is found, no bell sound is played

### App version

0.9.3

### Device Info

Pixel 4a, Android

### Additional information

Note that the bell sound is already played when a game is finished.

The correct place to implement this is probably somewhere in `game_controller.dart`? We could play the sound when receiving a new game with `game.status == started` and `game.steps.length == 0`.

**Comment by veloce** [comment]
Do we really want this in the app?

I can understand the reason of the bell sound on a desktop, since the user might be looking at another tab or application. But in the context of the application it is not really possible right now do to sth else while waiting for a game so the bell sounds redundant to me.

**Comment by tom-anders** [comment]
I saw this on the lichess beta group https://lichess.org/forum/team-lichess-beta-testers/mobile-app-alpha?page=11

> Play a sound when exiting from the "Waiting for opponent to join..." screen, because an opponent has been found. Sometimes searching for an opponent can be a long wait. You cannot be staring at the screen all the time while waiting, so you get lots of aborted games because you missed the silent arrival of new opponent, risking the ban for too many aborted games

Once we support tournaments I think this becomes even more important, waiting for the next tournament game (in my experience) can sometimes take much longer than waiting in the normal game queue.

**Comment by veloce** [comment]
Right, I agree it makes sense to add it :)
