### ISSUE TITLE
Wrong alignment in hello widget

### ISSUE THREAD

**Issue by Mauritz8** [lichess-org/mobile#893]
### What is the problem?

The name is not aligned with the rest of the text. Potentially introduced in https://github.com/lichess-org/mobile/commit/0ce1e58c8e9713a66f11d3392cc5d56d83ad9c82.
![image](https://github.com/user-attachments/assets/ee28b2cb-a9e1-4c9e-9fc0-61c9593ab314)

### Steps to reproduce the bug

1. Be logged in as a user that has a flair
2. Go to the home screen

### App version

v0.9.3 (I think the bug was introduced after the release)

### Device Info

Android emulator

**Comment by veloce** [comment]
Already fixed in https://github.com/lichess-org/mobile/commit/c8d4f2a387b9998403b812e7dc84d2ed3da47ee2
