### ISSUE TITLE
Berserk icon  not showing in game list

### ISSUE THREAD

**Issue by vaibhavsection** [lichess-org/mobile#895]
If tournament game played with berserk mode then that game in game list not shown with berserk icon.

**Comment by vaibhavsection** [comment]
![Screenshot_2024-08-02-09-28-30-07_86d667449b00b848f46d695606363a65](https://github.com/user-attachments/assets/aa06741c-42eb-48c9-934f-f120077b60f6)

Like this 👆

**Comment by vaibhavsection** [comment]
![Screenshot_2024-08-02-09-28-30-07_86d667449b00b848f46d695606363a65](https://github.com/user-attachments/assets/264cf4fb-9df6-4de3-8e22-95061889d818)

**Comment by veloce** [comment]
Sorry, this is for the old app. Repo: lichess-org/lichobile.
