### ISSUE TITLE
Enable shape drawing by default

### ISSUE THREAD

**Issue by glasszay** [lichess-org/mobile#899]
## My reasoning

- Helps people discover that it's possible on mobile (no one is going to find an option to enable it in settings).
- People who currently use it will think it's removed.

## Problem 

I understand some may not want arrows. Also, it can be confusing if you trigger it by accident. For these cases, it's more likely that the user tries to find an option to disable it. Whereas the other way around (disabled) most won't ever use it.

## Solution

Rename toggle label to "Shape drawing" and set enabled as default. Possibly down the line, make an explanation on how to use it in settings.

**Comment by tom-anders** [comment]
Would it maybe help to improve visibility of this setting by adding a toggle to the board settings during a game? (gear icon in the top right corner, already contains some other settings like zen mode and haptic feedback)

**Comment by glasszay** [comment]
Yes, it would definitely help

**Comment by veloce** [comment]
Yes you're right, I'll do as you suggest.
