### ISSUE TITLE
Feature request: draw shapes also on live board

### ISSUE THREAD

**Issue by adsche** [lichess-org/mobile#908]
Hi,

great job on #833! However, that only seems to work on the analysis board?

I'd love to be able to draw arrows in games as well (maybe correspondence only?) without switching to analysis.

What do you/others think? It is possible on the website.

**Comment by EmmetSchuler** [comment]
You can enable it under board options

**Comment by tom-anders** [comment]
IIRC there was also a recent commit that will enable shape drawing by default for all boards again

**Comment by adsche** [comment]
Ohh, awesome, thanks!

Although it was a bit hard to find: I thought the board settings were what comes up when tapping the cog top right while at the board. Would it make sense to add the switch there as well?

**Comment by tom-anders** [comment]
Yep, that was also implemented as part of https://github.com/lichess-org/mobile/issues/899 I think :)
