### ISSUE TITLE
premove isn't instant

### ISSUE THREAD

**Issue by purepani** [lichess-org/mobile#909]
### What is the problem?

I have been playing a good amount of bullet, and I find that I often run out of time while making pre-moves at the end of a game. This doesn't ever happen with the mobile website or desktop, where 0 time is taken.

### Steps to reproduce the bug

Play a +0 game.
Premove near the end of the game
Lose on time.

### App version

0.9.6

### Device Info

pixel 6 android 15

**Comment by veloce** [comment]
Thanks for the report. I think there is indeed something to improve there.
