### ISSUE TITLE
[Feature] Add board editor in Lichess mobile v2

### ISSUE THREAD

**Issue by olivertzeng** [lichess-org/mobile#911]

**Comment by tom-anders** [comment]
I implemented the board editor in https://github.com/lichess-org/mobile/pull/865, it just hasn't made it into an official release yet (0.10.x probably...?)

**Comment by olivertzeng** [comment]
Alright nice thanks bro
 Sent from Proton Mail for iOS 
於 週六, 8月 10, 2024 時間 15:07, Tom Praschan ***@***.***&gt; 寫道：  I implemented the board editor in #865, it just hasn't made it into an official release yet (0.10.x probably...?)
