### ISSUE TITLE
Wrong pieces scaling

### ISSUE THREAD

**Issue by d-enk** [lichess-org/mobile#914]
### What is the problem?

Non-consistent scaling

### Steps to reproduce the bug

https://github.com/user-attachments/assets/4c2a84ac-feaf-4090-aece-8dfaeb2350d0

### App version

v0.9.7

### Device Info

one plus 10 pro, Android 14

**Comment by veloce** [comment]
Thanks for the report. Resizing the view should be disabled, I thought it was the case, but obviously it is not.
