### ISSUE TITLE
Games history imported games shows online played games instead

### ISSUE THREAD

**Issue by yesseruser** [lichess-org/mobile#916]
### What is the problem?

In Games under my username in menu, the "X imported games" drop-down item shows the same list as "X games".
I've tried going to Imported games from other lists and it shows the same thing X games. (Not the list I was on before)

### Steps to reproduce the bug

1. Tap the menu icon in top left
2. Tap your name
3. Tap Games
4. Tap the "X games" drop-down and choose "X imported games"
5. Observe the issue.

### App version

8.0.0

### Device Info

Pixel 7 (Android 14)

### Additional information

As you can see in the image below, I have the imported games menu selected but it shows a ranked game.

![Screenshot_20240811-172245](https://github.com/user-attachments/assets/454fb170-682b-46d8-97b0-2a4431789ff9)

**Comment by EmmetSchuler** [comment]
Wrong repo, this one is for the beta app.
Recommend posting this in https://github.com/lichess-org/lichobile

**Comment by veloce** [comment]
Wrong repo: this is the old app found in lichess-org/lichobile.
