### ISSUE TITLE
Chess engine integration

### ISSUE THREAD

**Issue by jalpp** [lichess-org/mobile#93]
Hey Lichess devs, I made a chess engine in dart with beginner ELO strength it's written in Dart and free for use so if Lichess mobile will like to integrate it, note it has the engine logic, so can be used for testing/integration. not sure if it is needed right now, but I thought to reach out if needed in future.

https://github.com/jalpp/DartChessEngine

Thanks!

**Comment by veloce** [comment]
Hi! Thanks for sharing this. I don't think we need such an engine right now but I keep that in mind. Is it an UCI engine?

**Comment by jalpp** [comment]
Thanks, nope not right now but I’m working on it, though it has enough methods to return chess moves for both sides, I thought to share it here for testing purposes.

**Comment by veloce** [comment]
Closing since we'll only use stockfish.
