### ISSUE TITLE
Imprecise time in clock tool

### ISSUE THREAD

**Issue by ldeso** [lichess-org/mobile#932]
### What is the problem?

The clock tool does not measure time in a precise manner. For example, if a player taps the clock fast enough, the time will not go down.

### Steps to reproduce the bug

1. Open the clock tool.
2. Tap each side successively very fast.

### Expected behavior

Each player's time should slowly go down.

### Observed behavior

Their time doesn't change.

### App version

0.9.7

### Device Info

Pixel 6a / Android 14

### Additional information

Starting the clock creates a job that periodically updates the time ([countdown_clock.dart#L71-L81](https://github.com/lichess-org/mobile/blob/v0.9.7/lib/src/widgets/countdown_clock.dart#L71-L81)) with:

```dart
timeLeft = timeLeft - _stopwatch.elapsed;
```

I suspect the problem is that `timeLeft` is not being updated when stopping the clock ([countdown_clock.dart#L85-L91](https://github.com/lichess-org/mobile/blob/v0.9.7/lib/src/widgets/countdown_clock.dart#L85-L91)). This results in some time not being accounted for between the last periodic update of `timeLeft` and the moment a player stops the clock by tapping the screen. Over the course of an entire game, this can accumulate and lead to **a drift of several seconds**. Furthermore, this can lead to a player **not losing on time** if their time ends but they tap the clock before the next `timeLeft` update.

To make the clock more precise, `timeLeft` should also be updated when stopping the clock to switch to the next player, i.e. after `_stopwatch.stop()` ([countdown_clock.dart#L87](https://github.com/lichess-org/mobile/blob/v0.9.7/lib/src/widgets/countdown_clock.dart#L87)). This new logic should take into account that `timeLeft` may become negative.

This may need to be changed as well in [correspondence_clock_widget.dart](https://github.com/lichess-org/mobile/blob/v0.9.7/lib/src/view/game/correspondence_clock_widget.dart), but I am not familiar with the codebase and I am not sure what this file is for.

**Comment by tom-anders** [comment]
Good catch! 

> To make the clock more precise, timeLeft should also be updated when stopping the clock to switch to the next player, i.e. after _stopwatch.stop() ([countdown_clock.dart#L87](https://github.com/lichess-org/mobile/blob/v0.9.7/lib/src/widgets/countdown_clock.dart#L87)). This new logic should take into account that timeLeft may become negative.

Yeah that sounds reasonable, you can open a PR if you want to (a regression test would also be nice to have) - Note that the app's main developer @veloce is on vacation this week, so it might take some time until you'll get a Review.

> This may need to be changed as well in [correspondence_clock_widget.dart](https://github.com/lichess-org/mobile/blob/v0.9.7/lib/src/view/game/correspondence_clock_widget.dart), but I am not familiar with the codebase and I am not sure what this file is for.

I think in that case it's not necessary, as for online games the server is the single source of truth for a player's time (the clock counts down, but all the timing logic actually happens on the server).

**Comment by ldeso** [comment]
I only found this because I encountered the same issue when coding [my own chess clock app](https://github.com/ldeso/blitz)!

Thanks for the reply, I will try to make a PR in the coming weeks. If someone else wants to do it before me, please feel free.

**Comment by veloce** [comment]
PR is welcome, thanks for the report @ldeso
