### ISSUE TITLE
Integrating Streaming Tab in mobile app

### ISSUE THREAD

**Issue by Wishy-S** [lichess-org/mobile#946]
Currently the streaming tab is not configured in the mobile application, if someone is interested in working on it, feel free to ping me 

@veloce Please share your review if this is essential in mobile applications or it will just increase the overhead for it.

**Comment by veloce** [comment]
What is the streaming tab?

**Comment by Wishy-S** [comment]
![Screenshot_20240830-223123.png](https://github.com/user-attachments/assets/2b979eff-775a-4b92-abc9-21dd11acb6ea)

Streamers tab under 'Watch' which we have right now under the web version.

For which the below URL points: https://lichess.org/streamer/edit?u=testUserName

Note: testUserName might not be a valid username

**Comment by veloce** [comment]
We have streamers already.

**Comment by Wishy-S** [comment]
@veloce for mobile application I don't think we have streamers
