### ISSUE TITLE
Black screen during the chess game for Chessnut Evo owners

### ISSUE THREAD

**Issue by mistertase** [lichess-org/mobile#952]
I have a chess computer called Chessnut Evo. It has a fully built-in Android tablet with display and so on.
Because I really enjoy playing chess using the Lichess Android mobile apps, it will be useful for me to be able to play chess with the screen being black, in order not to be distracted by the animation on it and to save battery power.
I was suggested to use the blindfold chess option.
I installed the new beta app but still haven't figured out how to play offline.
So I tested the blindfold chess idea on the old Lichess app.
It didn't work at all because Chessnut Evo uses some kind of screen scanning technology (Chessnut Vision is its name) that recognizes the chessboard and chess pieces in Lichess and lights up the corresponding squares on Chessnut Evo.
In my blindfolded chess test, the Chessnut Evo illuminates all of the chess pieces' squares as if they were not placed there. This is normal behavior because Chessnut Vision does not detect any pieces on the Lichess board.
In the case of standard chess, everything is as it should be (look at the attached image).
Please implement a black screen option during the chess game in both Lichess apps or at least in the new one so you can make Chessnut Evo owners happy. At the same time, it will help us save battery power.
I strongly believe that, in future, there will be more chess computers like Chessnut Evo and this feature will be useful for all of them.

Thanks a lot.
![blindfold](https://github.com/user-attachments/assets/74348817-6453-4071-8a82-a26ed576bcb8)

**Comment by veloce** [comment]
Apologies in advance, but I don't think we'll be able to do what you ask. The main reason is that would be a device-only option. The app is shipped to the store and we supports thousands of devices through Android. If we start to make an option for one specific device, we would never stop.

There must be some ways to improve your experience using some workarounds:
- dim the screen light
- disable animation in the app settings
- etc.
