### ISSUE TITLE
Fix Zen Mode to hide items after game finishes

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#964]
### What is the problem?

Currently Zen mode only removes player names and ratings during an active game. Once the game finishes the ratings and player names are revealed. This functionality should only appear when selecting the 'in game only' mode, yet currently it applies even on normal Zen mode.
On the website selecting regular Zen mode should constantly hide players and ratings

### Steps to reproduce the bug

Go to settings
Select the normal Zen mode
Play a game, and notice players and ratings are hidden 
Expected: once the game ends ratings and players should remain hidden, just like on the website.
What happened: The info is revealed, as if you had selected the 'in game only' option.

### App version

0.9.7

### Device Info

Pixel 6 and Android 14

**Comment by tom-anders** [comment]
On a related note: it looks like zen mode also does not apply to the "Recent Games" widget in the home screen. I can take a look both issues (unless somebody else wants to have a go)

**Comment by tom-anders** [comment]
> On a related note: it looks like zen mode also does not apply to the "Recent Games" widget in the home screen.

Oh wait, mixed up "zen mode" and "hide ratings" options here. The latter _does_ affect the recent games widget (but zen mode does and should not), so behavior is actually correct here
