### ISSUE TITLE
Improve Premove Functionality

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#967]
Mentioned in the forum, the current Premove implementation can be confusing at times. 
Currently, when selecting a Premove you have to click on an empty square to cancel, and not any of your pieces. This makes sense, in order to be able to 'chain' premoves in a game. 

However if you tap the same piece that you are premoving, you'd expect it to cancel, but instead the app treats it as 'touching a piece' and doesn't cancel the premove, making it very confusing to the player. There are no times when you would need to Premove the same piece on the same square.

I know that Veloce is currently working on the premove functionality, so if this is a planned fix I'll close this.

**Comment by veloce** [comment]
Already been fixed in 0.10.0.
