### ISSUE TITLE
Latest update is not compatible with Android 10

### ISSUE THREAD

**Issue by ArleyFelipe** [lichess-org/mobile#972]
- - https://github.com/user-attachments/assets/70104f5f-e67d-47bc-9f03-53b421798f12

**Comment by ArleyFelipe** [comment]
The app crashes or freezes on a blank screen when I try to open it, I'm using a Huawei Mate 10 Pro with Android 10

**Comment by mmhh76** [comment]
Same thing on Samsung galaxy with Android 13.

**Comment by tom-anders** [comment]
I was experiencing similar issues, after some investigation and discussion on Discord a workaround was found: https://discord.com/channels/280713822073913354/807722604478988348/1280909126842454036

So should be fixed in 0.10.1 hopefully
