### ISSUE TITLE
When viewing a game from the opening explorer, it covers the top row of the board (1 or 8).

### ISSUE THREAD

**Issue by aslyamov** [lichess-org/mobile#976]
### What is the problem?

When I open a game from the opening database on my iPad to landscape mode, the line overlaps the top row (1 or 8)

### Steps to reproduce the bug

1. Open new Lichess app
2. Rotate the screen on your iPad
3. Open tab "Tools"
4. Open "Opening explorer"
5. Open any game

https://github.com/user-attachments/assets/7769ebc5-9628-42af-90a5-5b9dda174b29

### App version

0.10.0

### Device Info

iPad Pro 2022 / iPadOS 17.6.1

**Comment by veloce** [comment]
Thanks for the detailed report. It has already been fixed in 8aba342b3a9075c5b857e69b81aa1635dccb05c2.
