### ISSUE TITLE
Add the option to remove the shadow for dragged pieces

### ISSUE THREAD

**Issue by EmmetSchuler** [lichess-org/mobile#977]
It seems that some users on the forum dislike the shadow that appears when they drag pieces, because they are used to dragging on the website without one.
As we already have a toggle for piece magnification, I think this is relevant to certain users.

**Comment by anthisse** [comment]
When you mean shadow, do you mean the round circle that appears when dragging the piece over another square? Or instead do you mean the translucent piece that is displayed in the original square when dragging the piece?

**Comment by EmmetSchuler** [comment]
I'm referring to the grey circle under the dragged piece

**Comment by anthisse** [comment]
Opening a pull request now; I will start to work on this.

**Comment by ijm8710** [comment]
This just feels like people being way too uptight. Feels unnecessary imo

**Comment by EmmetSchuler** [comment]
Maybe not the most necessary, that's true. But a lot of people are coming from the website where there isn't a shadow. Someone made a feedback post about it so I guess there's at least a userbase for it.

**Comment by anthisse** [comment]
Upon further inspection, it seems that the circle comes from flutter-chessground; it's being drawn by _DragAvatar in board.dart here: https://github.com/lichess-org/flutter-chessground/blob/25de90896c8e00a825efaf174850d5b44a9c9048/lib/src/widgets/board.dart#L781

It doesn't appear to have an interface to turn it off unfortunately. To add the functionality, another bool (perhaps called showPieceShadow) inside of ChessboardSettings needs be added with associated mutators and accessors to set _DragAvatar to always be null when false.
