### ISSUE TITLE
Mobile l10n

### ISSUE THREAD

**Issue by veloce** [lichess-org/mobile#98]
Right now the app is translated using [Lila translations](https://github.com/lichess-org/lila/tree/master/translation/source), which are themselves coming from [crowdin](https://crowdin.com/project/lichess).

We need to create another crowdin project to handle translations that are specific to the mobile app.

The `update-arb-from-crowdin.mjs` script need to be updated to fetch the new mobile translations.

**Comment by tom-anders** [comment]
@veloce Just a heads-up for bookkeeping, this issue is now closed via https://github.com/lichess-org/mobile/pull/826. (I mentioned this in the commit message, but apparently Github did not close this issue automatically, probably because I don't have the necessary rights)

**Comment by veloce** [comment]
Thanks for the heads up!
