### ISSUE TITLE
Correspondence game not updated after minimizing the application

### ISSUE THREAD

**Issue by miguelvg27** [lichess-org/mobile#981]
### What is the problem?

Correspondence game not updated after minimizing the application and opening it back after an opponent move

### Steps to reproduce the bug

1. Open ongoing correspondance game
2. Make a move
3. Minimize the application while in the game
4. Opponent makes move
5. Reopen application (opening the app or touching the notification itself)
6. Game not updated

### App version

0.10.1

### Device Info

iPhone 12, iOS 17.6.1

### Additional information

Video attached:

https://github.com/user-attachments/assets/1b3b68bd-26f2-4155-bb97-5eb0406b9db6

**Comment by ijm8710** [comment]
This is a helpful video as more evidence for Veloce of what's being reported in #640
