### ISSUE TITLE
Captured Piece stay on boars not vanished 

### ISSUE THREAD

**Issue by vaibhavsection** [lichess-org/mobile#982]
### What is the problem?

Captured piece stay on board,not vanished after next move.

### Steps to reproduce the bug

Play any game 
After game finished
Click on analysis 
After some moves captured pieces not vanished stay on board it vanished after any other pieces or pawn come on that place.

### App version

0.10.1

### Device Info

OnePlus 7t/Android 12

### Additional information

https://github.com/user-attachments/assets/5177f30f-af6c-4b3c-ba6a-d2bf82a17cdf

**Comment by veloce** [comment]
Thanks for the report, are you able to reproduce the bug?

**Comment by vaibhavsection** [comment]
Actually this bug exist only one time after game finished,
But now try to analyse game it works well.
I Don't understand wierd thing going on.

**Comment by vaibhavsection** [comment]
It happen again to my device.

Uploading Record_2024-09-06-17-23-42_cbee2060dbe813f67358565f077e6954.mp4…


But exist immediately after game finished,
If try to analyse game from game list it works ok

**Comment by vaibhavsection** [comment]
> It happen again to my device.
> 
> Uploading Record_2024-09-06-17-23-42_cbee2060dbe813f67358565f077e6954.mp4…
> 
> But exist immediately after game finished, If try to analyse game from game list it works ok

Double knight in analysis.
Wierd things happen

**Comment by vaibhavsection** [comment]
It happen again to my device.(Double knight)



But exist immediately after game finished,
If try to analyse game from game list it works ok.

**Comment by vaibhavsection** [comment]
Wierd things happen with pieces if analys game **immediately after game finish** 
(Piece can't vanished)

https://github.com/user-attachments/assets/258da9e5-6b18-4a66-99de-1f4a77d93883

**Comment by vaibhavsection** [comment]
Actually this bug exist only one time after game finished,
But now try to analyse game from game list it works well.
I Don't understand wierd thing going on.

**Comment by vaibhavsection** [comment]
> Thanks for the report, are you able to reproduce the bug?

Update the reproduce method

**Comment by veloce** [comment]
I'm highly confident that I've fixed the bug with the above commit. But I haven't tested, so if you reproduce again after next release please reopen.

**Comment by vaibhavsection** [comment]
Ok
