### ISSUE TITLE
Load position buttons are hard to read

### ISSUE THREAD

**Issue by ijm8710** [lichess-org/mobile#986]
Especially in dark mode

**Comment by veloce** [comment]
Screenshot, or better description? because here we have to guess...

**Comment by ijm8710** [comment]
> Screenshot, or better description? because here we have to guess...

Sure @veloce admittedly I was being lazy but thought you'd just look at the screen 😜![image](https://github.com/user-attachments/assets/d54910ae-9466-4b13-8fc6-10ae0f4a2b5c)

White mode ain't great either but dark is illegible

**Comment by ijm8710** [comment]
The more I think about it I guess this may be intentional because they become legible once you paste the import.

I guess I got confused because why try to show the button at all at first if you don't want it to be read.

But if this is intentional, feel free to close

**Comment by veloce** [comment]
I think it was a regression with the new flutter version. Now I just changed the style of the buttons, and it looks better now imo.
