### ISSUE TITLE
Cupertino text and button color 

### ISSUE THREAD

**Issue by sen1van** [lichess-org/mobile#99]
Apparently Cupertino takes the color from the Material 3 theme for the color of some buttons and text (at least with a dark theme)

<img src="https://user-images.githubusercontent.com/80615886/227921350-f3941fe4-4469-4da4-b166-ac0cc8ce19be.png" width="200" height="420"><img src="https://user-images.githubusercontent.com/80615886/227921508-c44fb0ed-155c-4b04-b80f-705ca5e0783f.png" width="200" height="420">
<img src="https://user-images.githubusercontent.com/80615886/227921833-f7df2af6-170c-4db1-9df5-5bf019bc2ee1.png" width="200" height="420"><img src="https://user-images.githubusercontent.com/80615886/227921772-424226ff-0e83-4dcb-ad0c-fb92d3eb6aea.png" width="200" height="420">

<sub>It's not noticeable, but at first I thought I was going crazy :) <sub>

**Comment by veloce** [comment]
I don't see it, am I missing something?

**Comment by veloce** [comment]
Oh! I see it now, the first one is very slightly brown! 

I'll see what I can do.
