### ISSUE TITLE
Opening explorer previous & next buttons unexpected behaviour

### ISSUE THREAD

**Issue by qwool** [lichess-org/mobile#994]
### What is the problem?

The "Next" button remembers the first move picked rather than the most recent one

### Steps to reproduce the bug

1. Go to opening explorer
2. Pick a move
3. Press the "Previous" button
4. Pick another move and go back again
5. Press "Next"
6. The button will always navigate to the first move picked rather than the most recent one

### App version

0.10.1

### Device Info

IOS 17.6

**Comment by ijm8710** [comment]
Nice catch!I repro too

**Comment by veloce** [comment]
It follows the same behavior as in the analysis board screen: the first created variation takes precedence. But here it is definitely not what we want, so will fix.
